// 2단계: wiki 카드의 원문 경로(`sources[].path`) 주입.
//
// 배경: 1단계로 카드 본문·title·Read 가능한 카드 경로가 주입되게 됐지만, 카드에서 원문으로
// 가는 링크가 없어 카드가 막다른 길이었다(wikiOnly 아키텍처의 전제가 "카드에 원문 링크가
// 있으니 raw 검색이 불필요"다). 이 파일이 고정하는 것 세 묶음:
//   (1) emit/parse 쌍이 갈리지 않는다 — flow mapping 규칙은 yaml_scalars가 SSOT다.
//       이 저장소는 규칙이 갈려 두 번 조용히 깨졌다(title 8/731장 오염, qmd:auto 마커).
//   (2) `sources[].path`는 **모델 제공 값**이다 — traversal·미존재·개행을 주입하지 않는다.
//   (3) 개수 상한·중복 제거·진단 카운터. 무흔적 실패 금지.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir, homedir } from 'node:os';
import { join, isAbsolute, dirname } from 'node:path';
import { removeTemp } from './helpers/temp.mjs';

const PROMPT = 'config layout decision 내용을 알려줘';
const SOURCE_PREFIX = '  ↳ ';

function runRecall(payload, env = {}) {
  return execFileSync('python3', ['core/recall.py'], {
    input: JSON.stringify(payload),
    encoding: 'utf8',
    env: { ...process.env, ...env },
  });
}

function contextOf(payload, env = {}) {
  const out = runRecall(payload, env).trim();
  if (!out) return null;
  return JSON.parse(out).hookSpecificOutput.additionalContext;
}

function sourceLines(ctx) {
  return ctx.split('\n').filter((l) => l.startsWith(SOURCE_PREFIX)).map((l) => l.slice(SOURCE_PREFIX.length));
}

// 가장 **마지막** selection 줄을 본다(한 로그에 여러 번 실행하는 테스트가 있다).
function selection(logPath) {
  const lines = readFileSync(logPath, 'utf8').trim().split('\n').map(JSON.parse)
    .filter((l) => l.event === 'qmd_recall_selection');
  return lines[lines.length - 1];
}

// 카드 1장. sources 는 실제 compile 산출물과 같은 flow mapping 표기를 쓴다.
function card(title, summary, sourceEntries = [], status = 'verified') {
  const fm = [
    `title: "${title}"`,
    `status: ${status}`,
    'createdBy: qmd-auto-context',
    'reviewed: false',
    'sources:',
    ...(sourceEntries.length ? sourceEntries.map((e) => `  - ${e}`) : ['  - {kind: unknown}']),
    'triggers:',
    '  - "post_tool_source"',
  ].join('\n');
  return [
    '---', fm, '---', '',
    '> Auto-generated by qmd-auto-context from conversation/work context. Review, edit, or delete if wrong.',
    '',
    '<!-- qmd:auto:start id="main" sourceHash="deadbeef" -->',
    '## Summary',
    summary,
    '<!-- qmd:auto:end -->',
    '',
  ].join('\n');
}

function fileEntry(path) {
  return `{kind: "file", path: "${path}"}`;
}

function project(dir, { settings = {}, cards = {}, raw = {} } = {}) {
  mkdirSync(join(dir, '.auto-context', 'wiki', 'decisions'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-wiki', 'proj-docs'],
    collectionPaths: { 'proj-wiki': '.auto-context/wiki', 'proj-docs': 'docs' },
    collectionRoles: { 'proj-wiki': 'wiki', 'proj-docs': 'raw' },
    recallStrategy: 'wikiOnly',
    topN: 3,
    ...settings,
  }));
  for (const [name, body] of Object.entries(cards)) {
    writeFileSync(join(dir, '.auto-context', 'wiki', 'decisions', name), body);
  }
  for (const [rel, body] of Object.entries(raw)) {
    const target = join(dir, rel);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, body);
  }
}

function withProject(opts, fn) {
  const dir = mkdtempSync(join(tmpdir(), 'qmd-src-'));
  project(dir, opts);
  const fixture = join(dir, 'fixture.json');
  const log = join(dir, 'recall.jsonl');
  const write = (results) => writeFileSync(fixture, JSON.stringify({ results }));
  const run = (payload = {}) => contextOf(
    { prompt: PROMPT, cwd: dir, ...payload },
    { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log },
  );
  try {
    return fn({ dir, fixture, log, write, run });
  } finally {
    removeTemp(dir);
  }
}

// python 헬퍼. `arg` 를 주면 argv[1] 로 넘어간다(JS 문자열을 python 리터럴로 끼워 넣다가
// 인용부호가 겹치는 것을 피한다 — 이 파일은 sources 표기 자체를 다루므로 인용부호가 많다).
function py(code, arg) {
  const args = ['-c', ['import json, sys', 'sys.path.insert(0, "core")', ...code].join('\n')];
  if (arg !== undefined) args.push(arg);
  return JSON.parse(execFileSync('python3', args, { encoding: 'utf8' }));
}

// ─────────────────────────────────────────────────────────────────────────────
// (1) emit/parse SSOT
// ─────────────────────────────────────────────────────────────────────────────

test('flow mapping 왕복: 특수문자·개행·유니코드·구분자를 담아도 emit→parse 가 원값을 돌려준다', () => {
  const r = py([
    'import yaml_scalars as ys',
    'cases = [',
    '  {"kind": "file", "path": "docs/a.md"},',
    '  {"kind": "file", "path": "쉼표, 그리고 \\"인용\\" 과 백슬래시 \\\\ 경로.md"},',
    '  {"kind": "file", "path": "line\\nbreak.md", "collection": "c"},',
    '  {"kind": "url", "path": "https://x/y?a=1,b=2"},',
    '  {"path": "}중괄호{.md"},',
    '  {"path": "탭\\there.md"},',
    ']',
    'out = []',
    'for case in cases:',
    '    text = ys.dump_flow_mapping(case)',
    '    back, issue = ys.load_flow_mapping(text)',
    '    out.append({"text": text, "ok": back == case, "issue": issue})',
    'print(json.dumps(out, ensure_ascii=False))',
  ]);
  for (const row of r) {
    assert.equal(row.ok, true, `왕복 실패: ${row.text}`);
    assert.equal(row.issue, '', `왕복에 문제 신호가 붙으면 안 됨: ${row.text}`);
    assert.equal(row.text.split('\n').length, 1, `표기가 여러 줄이면 frontmatter 를 벗어난다: ${row.text}`);
  }
});

test('emit 표기는 표준 YAML 이다 (PyYAML 대조 — 런타임 의존이 아니라 테스트에서만)', () => {
  const r = py([
    'import yaml_scalars as ys',
    'try:',
    '    import yaml',
    'except ImportError:',
    '    print(json.dumps({"skipped": True})); raise SystemExit(0)',
    'cases = [',
    '  {"kind": "file", "path": "docs/a.md"},',
    '  {"kind": "file", "path": "쉼표, \\"인용\\", 백슬래시 \\\\ 와 개행\\n."},',
    '  {"path": "}b{"}, {"path": "  공백  유지  "},',
    ']',
    'out = []',
    'for case in cases:',
    '    text = ys.dump_flow_mapping(case)',
    '    out.append({"text": text, "same": yaml.safe_load(text) == case})',
    'print(json.dumps({"skipped": False, "rows": out}, ensure_ascii=False))',
  ]);
  if (r.skipped) return;
  for (const row of r.rows) assert.equal(row.same, true, `PyYAML 이 다르게 읽음: ${row.text}`);
});

test('wiki_compile 이 쓴 sources 를 recall 이 그대로 읽는다 (쓰기/읽기 SSOT 왕복)', () => {
  // 규칙이 두 벌로 갈리는 순간 조용히 깨지는 클래스다. 실제 writer 함수의 산출물을
  // 실제 reader 함수로 되읽어 고정한다.
  const r = py([
    'import recall, wiki_compile, yaml_scalars',
    'page = wiki_compile.markdown_page(',
    '  {"title": "왕복", "suggestedType": "concept",',
    '   "sources": [{"kind": "file", "path": "docs/쉼표, \\"인용\\".md"}, {"nope!": "x"}]},',
    '  "본문.", "verified", [], "deadbeef")',
    'block = page[3:page.index("\\n---", 3)]',
    'entries = recall.frontmatter_source_entries(block)',
    'parsed = [yaml_scalars.load_flow_mapping(e) for e in entries]',
    'print(json.dumps({"entries": entries, "paths": [p.get("path", "") for p, _ in parsed],',
    '                  "issues": [i for _, i in parsed]}, ensure_ascii=False))',
  ]);
  // path 없는 항목(`{"nope!": "x"}`)은 원문 추적에 쓸 수 없어 writer 가 버린다.
  assert.equal(r.entries.length, 1, 'writer 가 쓴 항목 수를 reader 가 그대로 본다');
  assert.equal(r.paths[0], 'docs/쉼표, "인용".md', '값이 역이스케이프돼 원래 경로가 복원된다');
  assert.deepEqual(r.issues, [''], 'writer 산출물에는 파싱 문제가 없어야 한다');
});

// ─────────────────────────────────────────────────────────────────────────────
// (2) 주입 e2e — 카드 경로와 원문 경로가 둘 다 Read 가능해야 한다
// ─────────────────────────────────────────────────────────────────────────────

test('원문 경로가 주입되고 카드 경로·원문 경로가 모두 실제로 존재한다 (데몬 plain 형식)', () => {
  withProject({
    cards: { 'card.md': card('설정 레이아웃 결정', '설정은 settings.json 한 곳에서만 읽는다.', [fileEntry('docs/current/a.md')]) },
    raw: { 'docs/current/a.md': '원문 본문\n' },
  }, ({ dir, log, write, run }) => {
    // 데몬 라이브는 `qmd://` 없이 `collection/path` 로도 돌려준다.
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/current/a.md']);
    const cardPath = ctx.split('\n').find((l) => l.startsWith('- [')).match(/] (\S+) - /)[1];
    for (const rel of [cardPath, ...sourceLines(ctx)]) {
      assert.equal(isAbsolute(rel), false, 'cwd 하위면 상대경로로 낸다(1단계 카드 경로와 같은 규칙)');
      assert.ok(existsSync(join(dir, rel)), `주입 경로가 열려야 한다: ${rel}`);
    }
    const sel = selection(log);
    assert.equal(sel.sources_injected, 1);
    assert.equal(sel.source_entries, 1);
    assert.equal(sel.sources_dropped, 0);
    assert.deepEqual(sel.source_drop_reasons, {});
  });
});

test('qmd:// 형식 결과와 plain 형식 결과가 섞여도 동일하게 동작한다', () => {
  // fixture 가 라이브 형식을 반영하지 않아 "테스트는 통과, 라이브만 깨짐" 사고가 두 번 있었다.
  withProject({
    cards: {
      'a.md': card('카드 A', 'A 본문.', [fileEntry('docs/a.md')]),
      'b.md': card('카드 B', 'B 본문.', [fileEntry('docs/b.md')]),
    },
    raw: { 'docs/a.md': 'a\n', 'docs/b.md': 'b\n' },
  }, ({ log, write, run }) => {
    write([
      { file: 'qmd://proj-wiki/decisions/a.md', title: 'Summary', score: 1 },
      { file: 'proj-wiki/decisions/b.md', title: 'Summary', score: 0.5 },
    ]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/a.md', 'docs/b.md'], '두 형식 모두 원문 경로를 얻는다');
    assert.equal(selection(log).sources_injected, 2);
  });
});

test('cwd 가 프로젝트 하위 디렉터리여도 원문 경로가 열린다 (base 는 cwd 가 아니라 project root)', () => {
  // sources[].path 는 project root 상대 POSIX 다(wiki_compile_enqueue._source_record).
  // cwd 를 base 로 쓰면 하위 디렉터리 세션에서 정상 소스가 미존재/traversal 로 오판된다.
  // HOME 하위에 만들어야 config 부모 탐색(HOME 경계)이 하위 cwd 에서도 동작한다.
  const base = mkdtempSync(join(homedir(), '.qmd-src-e2e-'));
  const dir = join(base, '한글 프로젝트');
  mkdirSync(dir, { recursive: true });
  project(dir, {
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/원문 문서.md')]) },
    raw: { 'docs/원문 문서.md': 'a\n' },
  });
  const sub = join(dir, 'docs', '깊은 폴더');
  mkdirSync(sub, { recursive: true });
  const fixture = join(dir, 'fixture.json');
  writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }] }));
  try {
    for (const cwd of [dir, sub]) {
      const ctx = contextOf({ prompt: PROMPT, cwd }, { QMD_QUERY_FIXTURE: fixture });
      const [line] = sourceLines(ctx);
      assert.ok(line, `cwd=${cwd} 에서 원문 경로가 주입돼야 함`);
      const resolved = isAbsolute(line) ? line : join(cwd, line);
      assert.ok(existsSync(resolved), `cwd=${cwd} 원문 경로가 실제 파일이어야 함: ${line}`);
      // cwd 하위면 상대, 밖이면 절대 — 1단계 카드 경로와 같은 규칙.
      assert.equal(isAbsolute(line), cwd !== dir, `표시 규칙 불일치: ${line}`);
    }
  } finally {
    removeTemp(base);
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// (3) 모델 제공 값 검증 — traversal / 미존재 / 개행
// ─────────────────────────────────────────────────────────────────────────────

test('traversal 경로는 주입하지 않는다 (프로젝트 파일로 위장 금지)', () => {
  withProject({
    cards: {
      'card.md': card('카드', '본문.', [
        fileEntry('../../../etc/passwd'),
        fileEntry('/etc/hosts'),
        fileEntry('docs/ok.md'),
      ]),
    },
    raw: { 'docs/ok.md': 'ok\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/ok.md']);
    assert.doesNotMatch(ctx, /passwd|hosts/);
    assert.equal(selection(log).source_drop_reasons.outside_root, 2);
  });
});

test('프로젝트 밖을 가리키는 심볼릭 링크도 걸린다 (resolve 후 판정)', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/link.md')]) },
  }, ({ dir, log, write, run }) => {
    execFileSync('ln', ['-s', '/etc/hosts', join(dir, 'docs', 'link.md')]);
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), []);
    assert.equal(selection(log).source_drop_reasons.outside_root, 1);
  });
});

test('존재하지 않는 원문 경로는 주입하지 않는다 (stale 링크로 모델이 헛돌지 않게)', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/gone.md'), fileEntry('docs')]) },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), [], '미존재 파일과 디렉터리 모두 제외');
    assert.equal(selection(log).source_drop_reasons.missing, 2);
    assert.match(ctx, /본문\./, '원문 경로가 없어도 카드 주입은 정상');
  });
});

test('경로에 개행이 있으면 주입 프레임이 깨지지 않는다 (한 줄 강제 — 1단계와 같은 클래스)', () => {
  withProject({
    cards: {
      'card.md': card('카드', '본문.', [
        '{kind: "file", path: "docs/we\\nird.md"}',
        fileEntry('docs/ok.md'),
      ]),
    },
    raw: { 'docs/ok.md': 'ok\n' },
  }, ({ dir, log, write, run }) => {
    // 파일 이름에 개행을 담을 수 있는 파일시스템이면 실제로 만들어, "존재하지만 한 줄로
    // 표시할 수 없는" 경로까지 덮는다. 못 만드는 환경에서는 미존재 경로로 검증된다.
    let created = false;
    try {
      writeFileSync(join(dir, 'docs', 'we\nird.md'), 'x\n');
      created = true;
    } catch { /* 파일시스템이 거부 */ }
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/ok.md']);
    assert.equal(ctx.split('\n').filter((l) => l.startsWith('- [')).length, 1, '프레임 항목은 1건');
    assert.doesNotMatch(ctx, /^ird\.md/m, '개행 뒤 조각이 새 줄로 새면 안 된다');
    const reasons = selection(log).source_drop_reasons;
    assert.equal(created ? reasons.not_inline : reasons.missing, 1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// (3-2) 리뷰 라운드: 타입 안정성 · kind 게이트 · 길이 상한 · 형태별 사유
// ─────────────────────────────────────────────────────────────────────────────

test('비문자 path 는 왕복에서 문자열이 되지 않는다 (writer 가 항목을 버린다)', () => {
  // `{"path": False}` 가 인용 없이 `path: false` 로 나가면 되읽어 문자열 "false" 가 되고,
  // `false` 라는 이름의 파일이 있으면 그것이 원문으로 주입되며 진단은 정상으로 남는다.
  const r = py([
    'import wiki_compile as wc, yaml_scalars as ys, recall',
    'page = wc.markdown_page({"title": "t", "sources": [',
    '  {"kind": "file", "path": False}, {"kind": "file", "path": 12},',
    '  {"kind": "file", "path": None}, {"kind": "slack"}, {"kind": "file", "path": "  "},',
    '  {"kind": "file", "path": "docs/ok.md"}]}, "s", "verified", [], "h")',
    'block = page[3:page.index("\\n---", 3)]',
    'entries = recall.frontmatter_source_entries(block)',
    'print(json.dumps({"entries": entries,',
    '                  "bool_emit": ys.dump_flow_mapping({"kind": "file", "path": False}),',
    '                  "int_emit": ys.dump_flow_mapping({"path": 12})}, ensure_ascii=False))',
  ]);
  assert.deepEqual(r.entries, ['{kind: "slack"}', '{kind: "file", path: "docs/ok.md"}'],
    'path 가 비문자·공백인 항목은 버리고, path 가 없는 출처 레코드는 그대로 쓴다');
  assert.doesNotMatch(r.bool_emit, /false/, 'emit 이 비문자 값을 내면 왕복 타입이 깨진다');
  assert.equal(r.int_emit, '', '쓸 수 있는 값이 없으면 빈 표기(호출부가 센티넬을 쓴다)');
});

test('kind 가 file 이 아닌 소스는 제외하고 사유를 kind_not_file 로 남긴다', () => {
  // 라이브 실측: kind 분포 file 874 / url 1 / slack 1. 예전엔 그 2건이 `missing` 으로
  // 집계돼 사유가 틀렸고, 3단계 source_missing 정책의 신호를 오염시켰다.
  withProject({
    cards: {
      'card.md': card('카드', '본문.', [
        '{kind: "url", path: "https://github.com/x/y/pull/1"}',
        '{kind: "slack", path: "https://x.slack.com/archives/C1/p1"}',
        '{kind: "url", path: "docs/looks-local.md"}',
        '{path: "docs/no-kind.md"}',
        fileEntry('docs/ok.md'),
      ]),
    },
    raw: { 'docs/ok.md': 'ok\n', 'docs/looks-local.md': 'x\n', 'docs/no-kind.md': 'x\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/ok.md']);
    assert.doesNotMatch(ctx, /looks-local|no-kind|github|slack/,
      'kind 가 file 이 아니면 로컬 경로 모양이어도 주입하지 않는다');
    const reasons = selection(log).source_drop_reasons;
    assert.equal(reasons.kind_not_file, 4);
    assert.equal(reasons.missing, undefined, 'url/slack 이 missing 으로 오집계되면 안 된다');
  });
});

test('wiki_verify_worker 와 kind 판정이 갈리지 않는다 (같은 file 집합)', () => {
  const r = py([
    'import recall, wiki_verify_worker, inspect',
    'src = inspect.getsource(wiki_verify_worker.load_sources)',
    'print(json.dumps({"kind": recall.SOURCE_KIND_FILE, "worker_uses": "kind\\") != \\"file\\"" in src}))',
  ]);
  assert.equal(r.kind, 'file');
  assert.equal(r.worker_uses, true, 'verify worker 가 같은 kind 집합을 쓴다');
});

test('상한을 넘는 경로는 존재하더라도 버린다 (자르면 못 여는 경로가 된다)', () => {
  const deep = Array.from({ length: 8 }, (_, i) => `dir${i}${'x'.repeat(20)}`).join('/');
  const long = `docs/${deep}/file.md`;
  assert.ok(long.length > 200, `테스트 경로가 상한을 넘어야 함: ${long.length}`);
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry(long), fileEntry('docs/ok.md')]) },
    raw: { [long]: 'x\n', 'docs/ok.md': 'ok\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/ok.md']);
    assert.doesNotMatch(ctx, /dir0/, '절단된 경로가 주입되면 없는 파일을 열게 된다');
    assert.equal(selection(log).source_drop_reasons.too_long, 1);
  });
});

test('상한은 실제 주입되는 표시 문자열 기준이다 (절대 표시로 넘으면 drop)', () => {
  // 같은 카드가 cwd=project 에서는 상대경로로 통과하고, 하위 cwd 에서는 절대 표시가
  // 상한을 넘어 drop 된다 — 토큰 예산은 주입 문자열의 함수이므로 의도된 비대칭이다.
  const base = mkdtempSync(join(homedir(), '.qmd-src-cap-'));
  try {
    // 절대 표시가 딱 상한을 넘도록 상대 경로 길이를 base 길이에서 역산한다.
    const relLen = Math.min(190, 201 - base.length - 1);
    assert.ok(relLen > 20, `임시 경로가 너무 길어 검증 불가: ${base.length}`);
    const name = 'a'.repeat(relLen - 'docs/'.length - '.md'.length);
    const rel = `docs/${name}.md`;
    project(base, {
      cards: { 'card.md': card('카드', '본문.', [fileEntry(rel)]) },
      // cwd 를 소스와 다른 하위 디렉터리로 두어야 표시가 절대경로가 된다.
      raw: { [rel]: 'x\n', 'sub/keep.md': 'x\n' },
    });
    const sub = join(base, 'sub');
    const fixture = join(base, 'fixture.json');
    const log = join(base, 'recall.jsonl');
    writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }] }));
    const env = { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log };
    assert.deepEqual(sourceLines(contextOf({ prompt: PROMPT, cwd: base }, env)), [rel],
      'cwd=project 에서는 상대 표시가 상한 안이라 주입된다');
    const ctx = contextOf({ prompt: PROMPT, cwd: sub }, env);
    assert.deepEqual(sourceLines(ctx), [], '하위 cwd 에서는 절대 표시가 상한을 넘어 drop');
    assert.equal(selection(log).source_drop_reasons.too_long, 1);
  } finally {
    removeTemp(base);
  }
});

test('sources: [ ... ] 한 줄 flow 시퀀스는 사유를 남긴다 (무흔적 실패 금지)', () => {
  const dir = mkdtempSync(join(tmpdir(), 'qmd-src-'));
  try {
    project(dir);
    // frontmatter 를 직접 조립한다(우리 writer 는 이 형태를 쓰지 않는다).
    writeFileSync(join(dir, '.auto-context', 'wiki', 'decisions', 'card.md'), [
      '---', 'title: "카드"', 'status: verified',
      'sources: [{kind: "file", path: "docs/a.md"}]',
      '---', '', '<!-- qmd:auto:start id="main" sourceHash="h" -->', '## Summary',
      '본문.', '<!-- qmd:auto:end -->', '',
    ].join('\n'));
    writeFileSync(join(dir, 'docs', 'a.md'), 'a\n');
    const fixture = join(dir, 'fixture.json');
    const log = join(dir, 'recall.jsonl');
    writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }] }));
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log });
    assert.deepEqual(sourceLines(ctx), []);
    const sel = selection(log);
    assert.equal(sel.source_entries, 1, '항목 수가 0 이면 "소스 없는 카드"와 구분되지 않는다');
    assert.deepEqual(sel.source_drop_reasons, { inline_sequence: 1 });
  } finally {
    removeTemp(dir);
  }
});

test('sources: [] 는 정상적인 "소스 없음" 표기라 사유를 만들지 않는다', () => {
  const dir = mkdtempSync(join(tmpdir(), 'qmd-src-'));
  try {
    project(dir);
    writeFileSync(join(dir, '.auto-context', 'wiki', 'decisions', 'card.md'), [
      '---', 'title: "카드"', 'status: verified', 'sources: []', '---', '',
      '<!-- qmd:auto:start id="main" sourceHash="h" -->', '## Summary', '본문.',
      '<!-- qmd:auto:end -->', '',
    ].join('\n'));
    const fixture = join(dir, 'fixture.json');
    const log = join(dir, 'recall.jsonl');
    writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }] }));
    contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log });
    const sel = selection(log);
    assert.equal(sel.source_entries, 0);
    assert.deepEqual(sel.source_drop_reasons, {});
  } finally {
    removeTemp(dir);
  }
});

test('sources: 줄의 잔여 4분기 — 항목이 아닌 것은 사유를 만들지 않는다', () => {
  // 예전엔 `[]` 이외의 모든 잔여를 항목화해 `sources: # 주석` 정상 카드가 허위
  // `parse_failed` 를, `sources: [] # 없음` 이 `inline_sequence` 를 남겼다. 주입 손실은
  // 없지만 3단계가 source_missing 정책을 정할 때 읽는 신호에 없는 실패가 섞인다.
  const cases = [
    ['sources:', ['  - {kind: "file", path: "docs/a.md"}'], 1, {}, 1],
    ['sources: # 원문 목록', ['  - {kind: "file", path: "docs/a.md"}'], 1, {}, 1],
    ['sources: []', [], 0, {}, 0],
    ['sources: [] # 없음', [], 0, {}, 0],
    ['sources: [{kind: "file", path: "docs/a.md"}]', [], 1, { inline_sequence: 1 }, 0],
  ];
  for (const [head, tail, entries, reasons, injected] of cases) {
    const dir = mkdtempSync(join(tmpdir(), 'qmd-src-res-'));
    try {
      project(dir);
      writeFileSync(join(dir, 'docs', 'a.md'), 'a\n');
      writeFileSync(join(dir, '.auto-context', 'wiki', 'decisions', 'card.md'), [
        '---', 'title: "카드"', 'status: verified', head, ...tail, '---', '',
        '<!-- qmd:auto:start id="main" sourceHash="h" -->', '## Summary', '본문.',
        '<!-- qmd:auto:end -->', '',
      ].join('\n'));
      const fixture = join(dir, 'fixture.json');
      const log = join(dir, 'recall.jsonl');
      writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }] }));
      const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log });
      assert.equal(sourceLines(ctx).length, injected, `주입 수 불일치: ${head}`);
      const sel = selection(log);
      assert.equal(sel.source_entries, entries, `항목 수 불일치: ${head}`);
      assert.deepEqual(sel.source_drop_reasons, reasons, `사유 불일치: ${head}`);
    } finally {
      removeTemp(dir);
    }
  }
});

test('비인용 plain scalar 안의 인용부호는 값의 일부다 (인용은 스칼라 선두에서만 시작)', () => {
  // 예전엔 어디서든 인용을 열어 `{path: a"b, kind: c}` 의 `,` 를 값 안으로 삼켜 kind 를
  // 잃었다. 결과는 fail-closed 였지만 사유가 kind_not_file/missing 으로 오표기됐다.
  const cases = {
    quote_in_plain: '{path: a"b, kind: file}',
    apostrophe_in_plain: "{path: a'b, kind: file}",
    quoted_value_with_comma: '{path: ", kind: x", kind: file}',
    single_quote_escape: "{path: 'it''s, ok', kind: file}",
    colon_in_plain_key: '{path:x: docs/a.md, kind: file}',
    colon_in_value: '{path: docs/a:b.md, kind: file}',
  };
  const r = py([
    'import yaml_scalars as ys',
    'out = {}',
    'for name, entry in json.loads(sys.argv[1]).items():',
    '    fields, issue = ys.load_flow_mapping(entry)',
    '    out[name] = {"fields": fields, "issue": issue}',
    'print(json.dumps(out, ensure_ascii=False))',
  ], JSON.stringify(cases));
  assert.deepEqual(r.quote_in_plain.fields, { path: 'a"b', kind: 'file' }, '값 중간 " 는 값의 일부');
  assert.deepEqual(r.apostrophe_in_plain.fields, { path: "a'b", kind: 'file' });
  assert.deepEqual(r.quoted_value_with_comma.fields, { path: ', kind: x', kind: 'file' },
    '선두 인용부호는 여전히 인용을 열어 값 안의 , 를 보호한다');
  assert.deepEqual(r.single_quote_escape.fields, { path: "it's, ok", kind: 'file' },
    "single-quoted 안의 '' 는 이스케이프이므로 인용을 닫지 않는다");
  assert.equal(r.colon_in_plain_key.fields.path, undefined,
    '구분자가 아닌 : 로 키를 자르면 없는 경로를 만들어 사유가 오표기된다');
  assert.deepEqual(r.colon_in_value.fields, { path: 'docs/a:b.md', kind: 'file' },
    'plain scalar 는 : 를 담을 수 있다');
});

test('PyYAML 차분 퍼즈: 비교 가능한 입력에서 불일치 0 (런타임 의존 아님 — 테스트에서만)', () => {
  // 리뷰 라운드에서 두 파서가 모두 수락한 11,243건 중 242건이 불일치했고 전부 "인용부호를
  // 스칼라 중간에서 열었다"가 원인이었다. 이 테스트가 그 수렴을 고정한다.
  // 비교 제외(원리적으로 다른 도메인, 각각 근거 있음):
  //   - `{` 로 시작하지 않는 입력: block mapping 미지원이 **의도**다(사유로 남긴다)
  //   - 개행이 든 입력: 항목은 항상 frontmatter 한 줄이라 발생 불가(PyYAML 은 개행을 접는다)
  //   - str 아닌 값(리스트/숫자/None): 이 파서의 도메인이 아니다(문자열만 돌려준다)
  //   - 중복 키: 우리는 first-wins(frontmatter 규약 — 뒤에 끼워 넣은 키가 앞을 못 덮는다),
  //     PyYAML 은 last-wins. 의도된 divergence다
  const r = py([
    'import random',
    'import yaml_scalars as ys',
    'try:',
    '    import yaml',
    'except ImportError:',
    '    print(json.dumps({"skipped": True})); raise SystemExit(0)',
    'ALPHA = list(chr(123) + chr(125) + chr(91) + chr(93) + chr(34) + ",:# abkindpathfile.md0/-" + chr(39) + chr(92) + chr(9))',
    'ALPHA += [chr(34) * 2, chr(39) * 2, chr(92) * 2, "kind", "path", ": ", ", "]',
    'rnd = random.Random(20260730)',
    'def gen(limit=14):',
    '    return "".join(rnd.choice(ALPHA) for _ in range(rnd.randint(1, limit)))',
    'def dup_keys(text):',
    '    items, issue = ys._scan_flow_mapping(text)',
    '    if issue:',
    '        return False',
    '    keys = []',
    '    for item in items:',
    '        key, sep, _ = ys._split_key_value(item)',
    '        if sep:',
    '            keys.append(ys.load_with_issue(key)[0])',
    '    return len(keys) != len(set(keys))',
    'compared = 0',
    'mismatch = []',
    'for i in range(int(sys.argv[1])):',
    '    text = chr(123) + gen() + chr(125) if i % 2 == 0 else chr(123) + "kind: " + gen(8) + ", path: " + gen(8) + chr(125)',
    '    if "\\n" in text:',
    '        continue',
    '    try:',
    '        theirs = yaml.safe_load(text)',
    '    except Exception:',
    '        continue',
    '    if not isinstance(theirs, dict):',
    '        continue',
    '    if not all(isinstance(k, str) and isinstance(v, str) for k, v in theirs.items()):',
    '        continue',
    '    if dup_keys(text):',
    '        continue',
    '    expect = {k: v for k, v in theirs.items() if ys.SAFE_KEY_RE.fullmatch(k)}',
    '    ours, _issue = ys.load_flow_mapping(text)',
    '    compared += 1',
    '    if ours != expect and len(mismatch) < 5:',
    '        mismatch.append({"text": text, "ours": ours, "yaml": expect})',
    '    elif ours != expect:',
    '        mismatch.append({"text": text})',
    'print(json.dumps({"skipped": False, "compared": compared, "mismatch": mismatch}, ensure_ascii=False))',
  ], '60000');
  if (r.skipped) return;
  assert.ok(r.compared > 3000, `비교 표본이 너무 적다: ${r.compared}`);
  assert.deepEqual(r.mismatch, [], `PyYAML 과 불일치: ${JSON.stringify(r.mismatch.slice(0, 5))}`);
});

test('형태별 파싱: 표준 YAML 인용 키·주석은 읽고, 지원하지 않는 형태는 형태별 사유를 남긴다', () => {
  // 카드의 sources 는 사람과 dedup/review resolver 가 손으로 이식한다(CLAUDE.md 계약).
  // 표준 YAML 로 쓴 형태를 못 읽으면 그 카드의 원문 링크가 통째로 사라지므로, 인용 키와
  // 주석은 읽는다. block mapping·여러 줄 flow 는 파서를 두 벌로 만들지 않고 사유만 남긴다.
  const forms = {
    emit: '{kind: "file", path: "docs/a.md"}',
    quoted_keys: '{"kind": "file", "path": "docs/a.md"}',
    single_quotes: "{kind: 'file', path: 'docs/a.md'}",
    trailing_comment: '{kind: "file", path: "docs/a.md"}  # 주석',
    trailing_garbage: '{kind: "file"} oops',
    multiline: '{kind: "file",',
    truncated_quote: '{kind: "file", path: "docs/a.md}',
    block_mapping: 'kind: file',
    inline_sequence: '[{kind: "file", path: "docs/a.md"}]',
    empty_mapping: '{}',
  };
  const r = py([
    'import recall, yaml_scalars as ys',
    'out = {}',
    'for name, entry in json.loads(sys.argv[1]).items():',
    '    fields, issue = ys.load_flow_mapping(entry)',
    '    out[name] = {"path": fields.get("path", ""),',
    '                 "reason": recall.source_parse_reason(entry, issue) if issue else ""}',
    'print(json.dumps(out, ensure_ascii=False))',
  ], JSON.stringify(forms));
  for (const name of ['emit', 'quoted_keys', 'single_quotes', 'trailing_comment']) {
    assert.equal(r[name].path, 'docs/a.md', `${name} 은 읽어야 한다`);
    assert.equal(r[name].reason, '');
  }
  assert.equal(r.block_mapping.reason, 'block_mapping');
  assert.equal(r.inline_sequence.reason, 'inline_sequence');
  assert.equal(r.multiline.reason, 'multiline_flow');
  assert.equal(r.truncated_quote.reason, 'parse_failed', '잘린 값은 여러 줄 flow 와 구분한다');
  assert.equal(r.trailing_garbage.reason, 'parse_failed');
  assert.equal(r.empty_mapping.reason, 'parse_failed');
});

test('표준 YAML 인용 키 카드도 실제로 주입된다 (왕복 e2e)', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', ['{"kind": "file", "path": "docs/a.md"}']) },
    raw: { 'docs/a.md': 'a\n' },
  }, ({ write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    assert.deepEqual(sourceLines(run()), ['docs/a.md']);
  });
});

test('sources 가 없는 카드({kind: unknown})는 안전하게 빈 결과를 낸다', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문이다.') },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), []);
    assert.doesNotMatch(ctx, /↳/, '원문 경로가 없으면 안내에도 ↳ 가 등장하지 않는다');
    assert.match(ctx, /요약으로 충분하면 파일을 열지 말고, 부족할 때만 위 경로를 Read\./, '1단계 안내문 그대로');
    const sel = selection(log);
    assert.equal(sel.source_entries, 1);
    assert.equal(sel.sources_injected, 0);
    assert.deepEqual(sel.source_drop_reasons, { no_path: 1 });
  });
});

test('망가진 sources 표기는 파싱 실패로 세고 나머지 항목을 살린다 (fail-open)', () => {
  withProject({
    cards: {
      'card.md': card('카드', '본문.', [
        '{kind: "file", path: "docs/open.md}',   // 인용부호가 열린 채 끝난다
        'docs/plain.md',                          // flow mapping 이 아니다
        fileEntry('docs/ok.md'),
      ]),
    },
    raw: { 'docs/ok.md': 'ok\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/ok.md'], '이상 항목이 나머지를 죽이지 않는다');
    assert.equal(selection(log).source_drop_reasons.parse_failed, 2);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// (4) 개수 상한 · 중복 제거 · 설정
// ─────────────────────────────────────────────────────────────────────────────

test('카드당 상한(기본 3)을 넘는 원문 경로는 잘리고 over_cap 으로 남는다', () => {
  const names = ['a', 'b', 'c', 'd', 'e'];
  withProject({
    cards: { 'card.md': card('카드', '본문.', names.map((n) => fileEntry(`docs/${n}.md`))) },
    raw: Object.fromEntries(names.map((n) => [`docs/${n}.md`, `${n}\n`])),
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/a.md', 'docs/b.md', 'docs/c.md']);
    const sel = selection(log);
    assert.equal(sel.inject_source_paths_per_card, 3);
    assert.equal(sel.source_drop_reasons.over_cap, 2);
  });
});

test('상한 도달과 조사 예산 소진은 다른 사유로 남는다 (over_cap vs over_scan_budget)', () => {
  // 상한 도달은 "설정을 올리면 늘어난다", 조사 예산 소진은 "앞쪽 항목이 대량으로 버려졌다"
  // 는 뜻이다 — 뭉치면 로그로 둘을 구분할 수 없다.
  withProject({
    settings: { injectSourcePathsPerCard: 1 },
    // 앞의 2건이 버려지므로 채택 1건 전에 조사 예산(1×2)이 먼저 소진된다.
    cards: {
      'scan.md': card('스캔', '본문.', [
        fileEntry('docs/gone1.md'), fileEntry('docs/gone2.md'), fileEntry('docs/ok.md'),
      ]),
    },
    raw: { 'docs/ok.md': 'ok\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/scan.md', title: 'Summary', score: 1 }]);
    assert.deepEqual(sourceLines(run()), []);
    const reasons = selection(log).source_drop_reasons;
    assert.equal(reasons.missing, 2);
    assert.equal(reasons.over_scan_budget, 1);
    assert.equal(reasons.over_cap, undefined, '조사 예산 소진이 상한 도달로 뭉쳐지면 안 된다');
  });
  withProject({
    settings: { injectSourcePathsPerCard: 1 },
    cards: { 'cap.md': card('상한', '본문.', [fileEntry('docs/a.md'), fileEntry('docs/b.md')]) },
    raw: { 'docs/a.md': 'a\n', 'docs/b.md': 'b\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/cap.md', title: 'Summary', score: 1 }]);
    assert.deepEqual(sourceLines(run()), ['docs/a.md']);
    const reasons = selection(log).source_drop_reasons;
    assert.equal(reasons.over_cap, 1);
    assert.equal(reasons.over_scan_budget, undefined);
  });
});

test('injectSourcePathsPerCard: 0 이면 sources 유무와 무관하게 출력이 바이트 동일하다', () => {
  // 2단계가 1단계 출력에 순증 0 임을 고정한다(끈 프로젝트의 회귀 가드).
  const results = [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }];
  const render = (entries) => {
    const dir = mkdtempSync(join(tmpdir(), 'qmd-src-off-'));
    try {
      project(dir, {
        settings: { injectSourcePathsPerCard: 0 },
        cards: { 'card.md': card('카드', '본문이다.', entries) },
        raw: { 'docs/a.md': 'a\n' },
      });
      const fixture = join(dir, 'fixture.json');
      writeFileSync(fixture, JSON.stringify({ results }));
      return contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    } finally {
      removeTemp(dir);
    }
  };
  const withSources = render([fileEntry('docs/a.md')]);
  const withoutSources = render([]);
  assert.equal(withSources, withoutSources, '끈 상태의 출력은 1단계와 바이트 동일해야 한다');
  assert.doesNotMatch(withSources, /↳/);
});

test('injectSourcePathsPerCard 로 상한을 조절하고 0 이면 원문 경로 주입을 끈다', () => {
  const cards = { 'card.md': card('카드', '본문.', [fileEntry('docs/a.md'), fileEntry('docs/b.md')]) };
  const raw = { 'docs/a.md': 'a\n', 'docs/b.md': 'b\n' };
  const results = [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }];
  withProject({ settings: { injectSourcePathsPerCard: 1 }, cards, raw }, ({ write, run }) => {
    write(results);
    assert.deepEqual(sourceLines(run()), ['docs/a.md']);
  });
  withProject({ settings: { injectSourcePathsPerCard: 0 }, cards, raw }, ({ log, write, run }) => {
    write(results);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), []);
    assert.doesNotMatch(ctx, /↳/);
    const sel = selection(log);
    assert.equal(sel.inject_source_paths_per_card, 0);
    // QMD_RECALL_LOG가 켜져 있으면 상한 0에서도 **분류만** 돌린다 — 그래야 3단계의
    // cards_all_sources_missing이 이 설정에 의해 죽지 않는다(카드는 여전히 캐논으로
    // 주입된다). 주입은 여전히 0이고 출력은 바이트 동일하다(위 두 단정).
    assert.equal(sel.source_entries, 2, '진단 로그가 켜진 동안은 항목을 분류한다(주입은 0)');
    assert.equal(sel.sources_injected, 0);
    assert.equal(sel.cards_all_sources_missing, 0, '두 원문이 다 살아 있으므로 0');
  });
});

test('같은 원문을 여러 카드가 가리키면 한 번만 주입한다 (순위 높은 카드 아래)', () => {
  withProject({
    cards: {
      'a.md': card('카드 A', 'A 본문.', [fileEntry('docs/shared.md')]),
      'b.md': card('카드 B', 'B 본문.', [fileEntry('docs/shared.md'), fileEntry('docs/only-b.md')]),
    },
    raw: { 'docs/shared.md': 's\n', 'docs/only-b.md': 'b\n' },
  }, ({ log, write, run }) => {
    write([
      { file: 'proj-wiki/decisions/a.md', title: 'Summary', score: 1 },
      { file: 'proj-wiki/decisions/b.md', title: 'Summary', score: 0.5 },
    ]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/shared.md', 'docs/only-b.md']);
    const lines = ctx.split('\n');
    assert.ok(lines.indexOf(`${SOURCE_PREFIX}docs/shared.md`) < lines.findIndex((l) => l.includes('카드 B')),
      '중복은 순위가 높은 카드 아래에 남는다');
    const sel = selection(log);
    assert.equal(sel.sources_injected, 2);
    assert.equal(sel.source_drop_reasons.duplicate, 1);
  });
});

test('한 카드 안의 중복 항목도 한 번만 주입한다', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/a.md'), fileEntry('./docs/a.md')]) },
    raw: { 'docs/a.md': 'a\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    assert.deepEqual(sourceLines(run()), ['docs/a.md']);
    assert.equal(selection(log).source_drop_reasons.duplicate, 1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// (5) 안내문 — 카드 본문이 먼저, 원문은 대조가 필요할 때만
// ─────────────────────────────────────────────────────────────────────────────

test('안내문이 ↳ 를 설명하고 "카드 먼저, 원문은 대조시" 우선순위를 담는다', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/a.md')]) },
    raw: { 'docs/a.md': 'a\n' },
  }, ({ write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    const guide = ctx.split('\n').find((l) => l.includes('요약으로 충분하면'));
    assert.match(guide, /`  ↳` 원문 경로를 Read\.$/, '원문은 마지막 우선순위');
    assert.match(guide, /요약으로 충분하면 파일을 열지 말고/, '카드 본문이 먼저');
    assert.match(guide, /부족할 때만 위 경로를, 카드와 대조가 필요할 때만/, '3단 우선순위');
    // 안내문은 매 프롬프트에 붙는다 — 새 문장을 추가하지 않고 기존 문장의 마지막 절만 바꾼다.
    assert.equal(ctx.split('\n').filter((l) => l.includes('충분하면')).length, 1);
  });
});

test('본문이 없고 원문 경로만 있는 경우에도 ↳ 안내가 붙는다', () => {
  withProject({
    settings: { injectSummaryMaxChars: 0 },
    cards: { 'card.md': card('카드', '본문은 주입되지 않는다.', [fileEntry('docs/a.md')]) },
    raw: { 'docs/a.md': 'a\n' },
  }, ({ write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/a.md']);
    assert.doesNotMatch(ctx, /본문은 주입되지 않는다/);
    assert.match(ctx, /`  ↳`로 시작하는 줄은 바로 위 항목 카드가 근거로 삼은 원문 경로다/);
    assert.match(ctx, /대조가 필요할 때만 Read\./);
  });
});

test('raw role 결과에는 원문 경로 줄이 붙지 않는다 (wiki 카드 전용)', () => {
  withProject({
    settings: { recallStrategy: 'flat' },
    raw: { 'docs/outside.md': '---\nstatus: verified\nsources:\n  - {kind: "file", path: "docs/a.md"}\n---\n본문\n', 'docs/a.md': 'a\n' },
  }, ({ write, run }) => {
    write([{ file: 'proj-docs/outside.md', title: 'Outside', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), []);
    assert.doesNotMatch(ctx, /↳/);
  });
});

test('cards_all_sources_missing: 살아 있는 원문이 있으면 세지 않는다 (주입 목록으로 판정하지 않는다)', () => {
  const cards = {
    // 살아 있는 원문 1 + 소실 1 → "전부 소실"이 아니다.
    'partial.md': card('부분 소실', '본문 A.', [fileEntry('docs/live.md'), fileEntry('docs/gone.md')]),
    // 소실만 → 전부 소실.
    'dead.md': card('전멸', '본문 B.', [fileEntry('docs/vanished.md')]),
    // 같은 원문을 가리켜 카드 사이 중복 제거로 주입 목록이 비는 카드.
    'dup.md': card('중복', '본문 C.', [fileEntry('docs/live.md')]),
  };
  const raw = { 'docs/live.md': 'l\n' };
  const results = [
    { file: 'proj-wiki/decisions/partial.md', title: 'Summary', score: 1 },
    { file: 'proj-wiki/decisions/dead.md', title: 'Summary', score: 0.5 },
    { file: 'proj-wiki/decisions/dup.md', title: 'Summary', score: 0.33 },
  ];
  for (const settings of [{}, { injectSourcePathsPerCard: 0 }]) {
    withProject({ settings, cards, raw }, ({ log, write, run }) => {
      write(results);
      run();
      // 주입 목록(`_wiki_sources`)으로 판정하면 partial/dup 까지 세어 3이 된다 —
      // 살아 있는 파일 소스 수를 따로 세야 한다(관측 전용 모드에서는 목록이 항상 빈다).
      assert.equal(selection(log).cards_all_sources_missing, 1,
        `설정 ${JSON.stringify(settings)} 에서 전멸 카드만 세어야 한다`);
    });
  }
});
