// 2단계: wiki 카드의 원문 경로(`sources[].path`) 주입.
//
// 배경: 1단계로 카드 본문·title·Read 가능한 카드 경로가 주입되게 됐지만, 카드에서 원문으로
// 가는 링크가 없어 카드가 막다른 길이었다(wikiOnly 아키텍처의 전제가 "카드에 원문 링크가
// 있으니 raw 검색이 불필요"다). 이 파일이 고정하는 것 세 묶음:
//   (1) emit/parse 쌍이 갈리지 않는다 — flow mapping 규칙은 yaml_scalars가 SSOT다.
//       이 저장소는 규칙이 갈려 두 번 조용히 깨졌다(title 8/731장 오염, qmd:auto 마커).
//   (2) `sources[].path`는 **모델 제공 값**이다 — traversal·미존재·개행을 주입하지 않는다.
//   (3) 개수 상한·중복 제거·진단 카운터. 무흔적 실패 금지.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir, homedir } from 'node:os';
import { join, isAbsolute, dirname } from 'node:path';

const PROMPT = 'config layout decision 내용을 알려줘';
const SOURCE_PREFIX = '  ↳ ';

function runRecall(payload, env = {}) {
  return execFileSync('python3', ['core/recall.py'], {
    input: JSON.stringify(payload),
    encoding: 'utf8',
    env: { ...process.env, ...env },
  });
}

function contextOf(payload, env = {}) {
  const out = runRecall(payload, env).trim();
  if (!out) return null;
  return JSON.parse(out).hookSpecificOutput.additionalContext;
}

function sourceLines(ctx) {
  return ctx.split('\n').filter((l) => l.startsWith(SOURCE_PREFIX)).map((l) => l.slice(SOURCE_PREFIX.length));
}

function selection(logPath) {
  return readFileSync(logPath, 'utf8').trim().split('\n').map(JSON.parse)
    .find((l) => l.event === 'qmd_recall_selection');
}

// 카드 1장. sources 는 실제 compile 산출물과 같은 flow mapping 표기를 쓴다.
function card(title, summary, sourceEntries = [], status = 'verified') {
  const fm = [
    `title: "${title}"`,
    `status: ${status}`,
    'createdBy: qmd-auto-context',
    'reviewed: false',
    'sources:',
    ...(sourceEntries.length ? sourceEntries.map((e) => `  - ${e}`) : ['  - {kind: unknown}']),
    'triggers:',
    '  - "post_tool_source"',
  ].join('\n');
  return [
    '---', fm, '---', '',
    '> Auto-generated by qmd-auto-context from conversation/work context. Review, edit, or delete if wrong.',
    '',
    '<!-- qmd:auto:start id="main" sourceHash="deadbeef" -->',
    '## Summary',
    summary,
    '<!-- qmd:auto:end -->',
    '',
  ].join('\n');
}

function fileEntry(path) {
  return `{kind: "file", path: "${path}"}`;
}

function project(dir, { settings = {}, cards = {}, raw = {} } = {}) {
  mkdirSync(join(dir, '.auto-context', 'wiki', 'decisions'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-wiki', 'proj-docs'],
    collectionPaths: { 'proj-wiki': '.auto-context/wiki', 'proj-docs': 'docs' },
    collectionRoles: { 'proj-wiki': 'wiki', 'proj-docs': 'raw' },
    recallStrategy: 'wikiOnly',
    topN: 3,
    ...settings,
  }));
  for (const [name, body] of Object.entries(cards)) {
    writeFileSync(join(dir, '.auto-context', 'wiki', 'decisions', name), body);
  }
  for (const [rel, body] of Object.entries(raw)) {
    const target = join(dir, rel);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, body);
  }
}

function withProject(opts, fn) {
  const dir = mkdtempSync(join(tmpdir(), 'qmd-src-'));
  project(dir, opts);
  const fixture = join(dir, 'fixture.json');
  const log = join(dir, 'recall.jsonl');
  const write = (results) => writeFileSync(fixture, JSON.stringify({ results }));
  const run = (payload = {}) => contextOf(
    { prompt: PROMPT, cwd: dir, ...payload },
    { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log },
  );
  try {
    return fn({ dir, fixture, log, write, run });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function py(code) {
  return JSON.parse(execFileSync('python3', ['-c', ['import json, sys', 'sys.path.insert(0, "core")', ...code].join('\n')], { encoding: 'utf8' }));
}

// ─────────────────────────────────────────────────────────────────────────────
// (1) emit/parse SSOT
// ─────────────────────────────────────────────────────────────────────────────

test('flow mapping 왕복: 특수문자·개행·유니코드·구분자를 담아도 emit→parse 가 원값을 돌려준다', () => {
  const r = py([
    'import yaml_scalars as ys',
    'cases = [',
    '  {"kind": "file", "path": "docs/a.md"},',
    '  {"kind": "file", "path": "쉼표, 그리고 \\"인용\\" 과 백슬래시 \\\\ 경로.md"},',
    '  {"kind": "file", "path": "line\\nbreak.md", "collection": "c"},',
    '  {"kind": "url", "path": "https://x/y?a=1,b=2"},',
    '  {"path": "}중괄호{.md"},',
    '  {"path": "탭\\there.md"},',
    ']',
    'out = []',
    'for case in cases:',
    '    text = ys.dump_flow_mapping(case)',
    '    back, issue = ys.load_flow_mapping(text)',
    '    out.append({"text": text, "ok": back == case, "issue": issue})',
    'print(json.dumps(out, ensure_ascii=False))',
  ]);
  for (const row of r) {
    assert.equal(row.ok, true, `왕복 실패: ${row.text}`);
    assert.equal(row.issue, '', `왕복에 문제 신호가 붙으면 안 됨: ${row.text}`);
    assert.equal(row.text.split('\n').length, 1, `표기가 여러 줄이면 frontmatter 를 벗어난다: ${row.text}`);
  }
});

test('emit 표기는 표준 YAML 이다 (PyYAML 대조 — 런타임 의존이 아니라 테스트에서만)', () => {
  const r = py([
    'import yaml_scalars as ys',
    'try:',
    '    import yaml',
    'except ImportError:',
    '    print(json.dumps({"skipped": True})); raise SystemExit(0)',
    'cases = [',
    '  {"kind": "file", "path": "docs/a.md"},',
    '  {"kind": "file", "path": "쉼표, \\"인용\\", 백슬래시 \\\\ 와 개행\\n."},',
    '  {"path": "}b{"}, {"path": "  공백  유지  "},',
    ']',
    'out = []',
    'for case in cases:',
    '    text = ys.dump_flow_mapping(case)',
    '    out.append({"text": text, "same": yaml.safe_load(text) == case})',
    'print(json.dumps({"skipped": False, "rows": out}, ensure_ascii=False))',
  ]);
  if (r.skipped) return;
  for (const row of r.rows) assert.equal(row.same, true, `PyYAML 이 다르게 읽음: ${row.text}`);
});

test('wiki_compile 이 쓴 sources 를 recall 이 그대로 읽는다 (쓰기/읽기 SSOT 왕복)', () => {
  // 규칙이 두 벌로 갈리는 순간 조용히 깨지는 클래스다. 실제 writer 함수의 산출물을
  // 실제 reader 함수로 되읽어 고정한다.
  const r = py([
    'import recall, wiki_compile, yaml_scalars',
    'page = wiki_compile.markdown_page(',
    '  {"title": "왕복", "suggestedType": "concept",',
    '   "sources": [{"kind": "file", "path": "docs/쉼표, \\"인용\\".md"}, {"nope!": "x"}]},',
    '  "본문.", "verified", [], "deadbeef")',
    'block = page[3:page.index("\\n---", 3)]',
    'entries = recall.frontmatter_source_entries(block)',
    'parsed = [yaml_scalars.load_flow_mapping(e) for e in entries]',
    'print(json.dumps({"entries": entries, "paths": [p.get("path", "") for p, _ in parsed],',
    '                  "issues": [i for _, i in parsed]}, ensure_ascii=False))',
  ]);
  assert.equal(r.entries.length, 2, 'writer 가 쓴 항목 수를 reader 가 그대로 본다');
  assert.equal(r.paths[0], 'docs/쉼표, "인용".md', '값이 역이스케이프돼 원래 경로가 복원된다');
  // 안전하지 않은 키만 있던 항목은 writer 가 `{kind: unknown}` 센티넬로 쓴다.
  assert.equal(r.entries[1], '{kind: unknown}');
  assert.deepEqual(r.issues, ['', ''], 'writer 산출물에는 파싱 문제가 없어야 한다');
});

// ─────────────────────────────────────────────────────────────────────────────
// (2) 주입 e2e — 카드 경로와 원문 경로가 둘 다 Read 가능해야 한다
// ─────────────────────────────────────────────────────────────────────────────

test('원문 경로가 주입되고 카드 경로·원문 경로가 모두 실제로 존재한다 (데몬 plain 형식)', () => {
  withProject({
    cards: { 'card.md': card('설정 레이아웃 결정', '설정은 settings.json 한 곳에서만 읽는다.', [fileEntry('docs/current/a.md')]) },
    raw: { 'docs/current/a.md': '원문 본문\n' },
  }, ({ dir, log, write, run }) => {
    // 데몬 라이브는 `qmd://` 없이 `collection/path` 로도 돌려준다.
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/current/a.md']);
    const cardPath = ctx.split('\n').find((l) => l.startsWith('- [')).match(/] (\S+) - /)[1];
    for (const rel of [cardPath, ...sourceLines(ctx)]) {
      assert.equal(isAbsolute(rel), false, 'cwd 하위면 상대경로로 낸다(1단계 카드 경로와 같은 규칙)');
      assert.ok(existsSync(join(dir, rel)), `주입 경로가 열려야 한다: ${rel}`);
    }
    const sel = selection(log);
    assert.equal(sel.sources_injected, 1);
    assert.equal(sel.source_entries, 1);
    assert.equal(sel.sources_dropped, 0);
    assert.deepEqual(sel.source_drop_reasons, {});
  });
});

test('qmd:// 형식 결과와 plain 형식 결과가 섞여도 동일하게 동작한다', () => {
  // fixture 가 라이브 형식을 반영하지 않아 "테스트는 통과, 라이브만 깨짐" 사고가 두 번 있었다.
  withProject({
    cards: {
      'a.md': card('카드 A', 'A 본문.', [fileEntry('docs/a.md')]),
      'b.md': card('카드 B', 'B 본문.', [fileEntry('docs/b.md')]),
    },
    raw: { 'docs/a.md': 'a\n', 'docs/b.md': 'b\n' },
  }, ({ log, write, run }) => {
    write([
      { file: 'qmd://proj-wiki/decisions/a.md', title: 'Summary', score: 1 },
      { file: 'proj-wiki/decisions/b.md', title: 'Summary', score: 0.5 },
    ]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/a.md', 'docs/b.md'], '두 형식 모두 원문 경로를 얻는다');
    assert.equal(selection(log).sources_injected, 2);
  });
});

test('cwd 가 프로젝트 하위 디렉터리여도 원문 경로가 열린다 (base 는 cwd 가 아니라 project root)', () => {
  // sources[].path 는 project root 상대 POSIX 다(wiki_compile_enqueue._source_record).
  // cwd 를 base 로 쓰면 하위 디렉터리 세션에서 정상 소스가 미존재/traversal 로 오판된다.
  // HOME 하위에 만들어야 config 부모 탐색(HOME 경계)이 하위 cwd 에서도 동작한다.
  const base = mkdtempSync(join(homedir(), '.qmd-src-e2e-'));
  const dir = join(base, '한글 프로젝트');
  mkdirSync(dir, { recursive: true });
  project(dir, {
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/원문 문서.md')]) },
    raw: { 'docs/원문 문서.md': 'a\n' },
  });
  const sub = join(dir, 'docs', '깊은 폴더');
  mkdirSync(sub, { recursive: true });
  const fixture = join(dir, 'fixture.json');
  writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }] }));
  try {
    for (const cwd of [dir, sub]) {
      const ctx = contextOf({ prompt: PROMPT, cwd }, { QMD_QUERY_FIXTURE: fixture });
      const [line] = sourceLines(ctx);
      assert.ok(line, `cwd=${cwd} 에서 원문 경로가 주입돼야 함`);
      const resolved = isAbsolute(line) ? line : join(cwd, line);
      assert.ok(existsSync(resolved), `cwd=${cwd} 원문 경로가 실제 파일이어야 함: ${line}`);
      // cwd 하위면 상대, 밖이면 절대 — 1단계 카드 경로와 같은 규칙.
      assert.equal(isAbsolute(line), cwd !== dir, `표시 규칙 불일치: ${line}`);
    }
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// (3) 모델 제공 값 검증 — traversal / 미존재 / 개행
// ─────────────────────────────────────────────────────────────────────────────

test('traversal 경로는 주입하지 않는다 (프로젝트 파일로 위장 금지)', () => {
  withProject({
    cards: {
      'card.md': card('카드', '본문.', [
        fileEntry('../../../etc/passwd'),
        fileEntry('/etc/hosts'),
        fileEntry('docs/ok.md'),
      ]),
    },
    raw: { 'docs/ok.md': 'ok\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/ok.md']);
    assert.doesNotMatch(ctx, /passwd|hosts/);
    assert.equal(selection(log).source_drop_reasons.outside_root, 2);
  });
});

test('프로젝트 밖을 가리키는 심볼릭 링크도 걸린다 (resolve 후 판정)', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/link.md')]) },
  }, ({ dir, log, write, run }) => {
    execFileSync('ln', ['-s', '/etc/hosts', join(dir, 'docs', 'link.md')]);
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), []);
    assert.equal(selection(log).source_drop_reasons.outside_root, 1);
  });
});

test('존재하지 않는 원문 경로는 주입하지 않는다 (stale 링크로 모델이 헛돌지 않게)', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/gone.md'), fileEntry('docs')]) },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), [], '미존재 파일과 디렉터리 모두 제외');
    assert.equal(selection(log).source_drop_reasons.missing, 2);
    assert.match(ctx, /본문\./, '원문 경로가 없어도 카드 주입은 정상');
  });
});

test('경로에 개행이 있으면 주입 프레임이 깨지지 않는다 (한 줄 강제 — 1단계와 같은 클래스)', () => {
  withProject({
    cards: {
      'card.md': card('카드', '본문.', [
        '{kind: "file", path: "docs/we\\nird.md"}',
        fileEntry('docs/ok.md'),
      ]),
    },
    raw: { 'docs/ok.md': 'ok\n' },
  }, ({ dir, log, write, run }) => {
    // 파일 이름에 개행을 담을 수 있는 파일시스템이면 실제로 만들어, "존재하지만 한 줄로
    // 표시할 수 없는" 경로까지 덮는다. 못 만드는 환경에서는 미존재 경로로 검증된다.
    let created = false;
    try {
      writeFileSync(join(dir, 'docs', 'we\nird.md'), 'x\n');
      created = true;
    } catch { /* 파일시스템이 거부 */ }
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/ok.md']);
    assert.equal(ctx.split('\n').filter((l) => l.startsWith('- [')).length, 1, '프레임 항목은 1건');
    assert.doesNotMatch(ctx, /^ird\.md/m, '개행 뒤 조각이 새 줄로 새면 안 된다');
    const reasons = selection(log).source_drop_reasons;
    assert.equal(created ? reasons.not_inline : reasons.missing, 1);
  });
});

test('sources 가 없는 카드({kind: unknown})는 안전하게 빈 결과를 낸다', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문이다.') },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), []);
    assert.doesNotMatch(ctx, /↳/, '원문 경로가 없으면 안내에도 ↳ 가 등장하지 않는다');
    assert.match(ctx, /요약으로 충분하면 파일을 열지 말고, 부족할 때만 위 경로를 Read\./, '1단계 안내문 그대로');
    const sel = selection(log);
    assert.equal(sel.source_entries, 1);
    assert.equal(sel.sources_injected, 0);
    assert.deepEqual(sel.source_drop_reasons, { no_path: 1 });
  });
});

test('망가진 sources 표기는 파싱 실패로 세고 나머지 항목을 살린다 (fail-open)', () => {
  withProject({
    cards: {
      'card.md': card('카드', '본문.', [
        '{kind: "file", path: "docs/open.md}',   // 인용부호가 열린 채 끝난다
        'docs/plain.md',                          // flow mapping 이 아니다
        fileEntry('docs/ok.md'),
      ]),
    },
    raw: { 'docs/ok.md': 'ok\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/ok.md'], '이상 항목이 나머지를 죽이지 않는다');
    assert.equal(selection(log).source_drop_reasons.parse_failed, 2);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// (4) 개수 상한 · 중복 제거 · 설정
// ─────────────────────────────────────────────────────────────────────────────

test('카드당 상한(기본 3)을 넘는 원문 경로는 잘리고 over_cap 으로 남는다', () => {
  const names = ['a', 'b', 'c', 'd', 'e'];
  withProject({
    cards: { 'card.md': card('카드', '본문.', names.map((n) => fileEntry(`docs/${n}.md`))) },
    raw: Object.fromEntries(names.map((n) => [`docs/${n}.md`, `${n}\n`])),
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/a.md', 'docs/b.md', 'docs/c.md']);
    const sel = selection(log);
    assert.equal(sel.inject_source_paths_per_card, 3);
    assert.equal(sel.source_drop_reasons.over_cap, 2);
  });
});

test('injectSourcePathsPerCard 로 상한을 조절하고 0 이면 원문 경로 주입을 끈다', () => {
  const cards = { 'card.md': card('카드', '본문.', [fileEntry('docs/a.md'), fileEntry('docs/b.md')]) };
  const raw = { 'docs/a.md': 'a\n', 'docs/b.md': 'b\n' };
  const results = [{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }];
  withProject({ settings: { injectSourcePathsPerCard: 1 }, cards, raw }, ({ write, run }) => {
    write(results);
    assert.deepEqual(sourceLines(run()), ['docs/a.md']);
  });
  withProject({ settings: { injectSourcePathsPerCard: 0 }, cards, raw }, ({ log, write, run }) => {
    write(results);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), []);
    assert.doesNotMatch(ctx, /↳/);
    const sel = selection(log);
    assert.equal(sel.inject_source_paths_per_card, 0);
    assert.equal(sel.source_entries, 0, '끈 경우엔 항목을 읽지도 않는다(추가 비용 0)');
  });
});

test('같은 원문을 여러 카드가 가리키면 한 번만 주입한다 (순위 높은 카드 아래)', () => {
  withProject({
    cards: {
      'a.md': card('카드 A', 'A 본문.', [fileEntry('docs/shared.md')]),
      'b.md': card('카드 B', 'B 본문.', [fileEntry('docs/shared.md'), fileEntry('docs/only-b.md')]),
    },
    raw: { 'docs/shared.md': 's\n', 'docs/only-b.md': 'b\n' },
  }, ({ log, write, run }) => {
    write([
      { file: 'proj-wiki/decisions/a.md', title: 'Summary', score: 1 },
      { file: 'proj-wiki/decisions/b.md', title: 'Summary', score: 0.5 },
    ]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/shared.md', 'docs/only-b.md']);
    const lines = ctx.split('\n');
    assert.ok(lines.indexOf(`${SOURCE_PREFIX}docs/shared.md`) < lines.findIndex((l) => l.includes('카드 B')),
      '중복은 순위가 높은 카드 아래에 남는다');
    const sel = selection(log);
    assert.equal(sel.sources_injected, 2);
    assert.equal(sel.source_drop_reasons.duplicate, 1);
  });
});

test('한 카드 안의 중복 항목도 한 번만 주입한다', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/a.md'), fileEntry('./docs/a.md')]) },
    raw: { 'docs/a.md': 'a\n' },
  }, ({ log, write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    assert.deepEqual(sourceLines(run()), ['docs/a.md']);
    assert.equal(selection(log).source_drop_reasons.duplicate, 1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// (5) 안내문 — 카드 본문이 먼저, 원문은 대조가 필요할 때만
// ─────────────────────────────────────────────────────────────────────────────

test('안내문이 ↳ 를 설명하고 "카드 먼저, 원문은 대조시" 우선순위를 담는다', () => {
  withProject({
    cards: { 'card.md': card('카드', '본문.', [fileEntry('docs/a.md')]) },
    raw: { 'docs/a.md': 'a\n' },
  }, ({ write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    const guide = ctx.split('\n').find((l) => l.includes('요약으로 충분하면'));
    assert.match(guide, /`  ↳` 원문 경로를 Read\.$/, '원문은 마지막 우선순위');
    assert.match(guide, /요약으로 충분하면 파일을 열지 말고/, '카드 본문이 먼저');
    assert.match(guide, /부족할 때만 위 경로를, 카드와 대조가 필요할 때만/, '3단 우선순위');
    // 안내문은 매 프롬프트에 붙는다 — 새 문장을 추가하지 않고 기존 문장의 마지막 절만 바꾼다.
    assert.equal(ctx.split('\n').filter((l) => l.includes('충분하면')).length, 1);
  });
});

test('본문이 없고 원문 경로만 있는 경우에도 ↳ 안내가 붙는다', () => {
  withProject({
    settings: { injectSummaryMaxChars: 0 },
    cards: { 'card.md': card('카드', '본문은 주입되지 않는다.', [fileEntry('docs/a.md')]) },
    raw: { 'docs/a.md': 'a\n' },
  }, ({ write, run }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), ['docs/a.md']);
    assert.doesNotMatch(ctx, /본문은 주입되지 않는다/);
    assert.match(ctx, /`  ↳`로 시작하는 줄은 바로 위 항목 카드가 근거로 삼은 원문 경로다/);
    assert.match(ctx, /대조가 필요할 때만 Read\./);
  });
});

test('raw role 결과에는 원문 경로 줄이 붙지 않는다 (wiki 카드 전용)', () => {
  withProject({
    settings: { recallStrategy: 'flat' },
    raw: { 'docs/outside.md': '---\nstatus: verified\nsources:\n  - {kind: "file", path: "docs/a.md"}\n---\n본문\n', 'docs/a.md': 'a\n' },
  }, ({ write, run }) => {
    write([{ file: 'proj-docs/outside.md', title: 'Outside', score: 1 }]);
    const ctx = run();
    assert.deepEqual(sourceLines(ctx), []);
    assert.doesNotMatch(ctx, /↳/);
  });
});
