// 주입이 실제 정보를 담는지 검증한다.
//
// 배경: 라이브 실측에서 주입되는 정보가 0이었다. 세 겹으로 끊겨 있었다 —
// (1) 경로가 collection prefix가 붙은 형태(`proj-wiki/decisions/x.md`)라 어떤 base로도
// 열리지 않았고, (2) title이 데몬이 준 첫 섹션 헤딩(`Summary`)이었고, (3) 본문이
// 아예 조립되지 않았다. 이 파일은 그 셋과 상한·경계(wikiOnly raw 누출, fail-closed)를
// 함께 고정한다.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, isAbsolute } from 'node:path';

function runRecall(payload, env = {}) {
  return execFileSync('python3', ['core/recall.py'], {
    input: JSON.stringify(payload),
    encoding: 'utf8',
    env: { ...process.env, ...env },
  });
}

function contextOf(payload, env = {}) {
  const out = runRecall(payload, env).trim();
  if (!out) return null;
  return JSON.parse(out).hookSpecificOutput.additionalContext;
}

const PROMPT = 'config layout decision 내용을 알려줘';

// verified 카드 1장을 가진 wiki 프로젝트. 카드 본문은 실제 compile 산출물과 같은
// 구조(frontmatter + 상투구 + qmd:auto 블록)를 쓴다.
function card(frontmatter, summary, manual = '') {
  return [
    '---',
    frontmatter,
    '---',
    '',
    '> Auto-generated by qmd-auto-context from conversation/work context. Review, edit, or delete if wrong.',
    '',
    '<!-- qmd:auto:start id="main" sourceHash="deadbeef" -->',
    '## Summary',
    summary,
    '<!-- qmd:auto:end -->',
    manual,
    '',
  ].join('\n');
}

function project(dir, { settings = {}, cards = {}, raw = {} } = {}) {
  mkdirSync(join(dir, '.auto-context', 'wiki', 'decisions'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-wiki', 'proj-docs'],
    collectionPaths: { 'proj-wiki': '.auto-context/wiki', 'proj-docs': 'docs' },
    collectionRoles: { 'proj-wiki': 'wiki', 'proj-docs': 'raw' },
    recallStrategy: 'wikiOnly',
    topN: 3,
    ...settings,
  }));
  for (const [name, body] of Object.entries(cards)) {
    writeFileSync(join(dir, '.auto-context', 'wiki', 'decisions', name), body);
  }
  for (const [name, body] of Object.entries(raw)) {
    writeFileSync(join(dir, 'docs', name), body);
  }
}

function withProject(opts, fn) {
  const dir = mkdtempSync(join(tmpdir(), 'qmd-inject-'));
  project(dir, opts);
  const fixture = join(dir, 'fixture.json');
  const write = (results) => writeFileSync(fixture, JSON.stringify({ results }));
  try {
    return fn({ dir, fixture, write });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const VERIFIED_FM = [
  'title: "카드 정식 제목 — 설정 레이아웃 결정"',
  'status: verified',
  'createdBy: qmd-auto-context',
  'reviewed: false',
  'verifiedBy: claude',
].join('\n');

test('주입에 카드 본문이 포함되고 frontmatter title이 쓰인다 (섹션 헤딩 Summary가 title로 새지 않음)', () => {
  withProject({
    cards: { 'card.md': card(VERIFIED_FM, '설정은 .auto-context/settings.json 한 곳에서만 읽는다.') },
  }, ({ dir, fixture, write }) => {
    // 데몬이 주는 title은 frontmatter title이 아니라 첫 섹션 헤딩이다 — 라이브 재현.
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    assert.ok(ctx);
    assert.match(ctx, /설정은 \.auto-context\/settings\.json 한 곳에서만 읽는다\./, '카드 본문이 주입돼야 함');
    assert.match(ctx, / - 카드 정식 제목 — 설정 레이아웃 결정/, 'frontmatter title 사용');
    assert.doesNotMatch(ctx, /- Summary/, '데몬이 준 섹션 헤딩이 title로 새면 안 됨');
    assert.doesNotMatch(ctx, /## Summary/, 'Summary 헤딩 자체는 주입하지 않음(중복 라벨)');
    assert.doesNotMatch(ctx, /Auto-generated by qmd-auto-context/, '상투구는 주입하지 않음');
    assert.match(ctx, /요약으로 충분하면 파일을 열지 말고/, '요약/원문 구분 안내');
  });
});

test('주입 경로는 project root 기준으로 실제 존재하는 파일을 가리킨다', () => {
  withProject({
    cards: { 'card.md': card(VERIFIED_FM, '경로 해석 검증용 본문이다.') },
  }, ({ dir, fixture, write }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    const bullet = ctx.split('\n').find((l) => l.startsWith('- '));
    const path = bullet.replace(/^- \[[^\]]*\] /, '').split(' - ')[0];
    assert.equal(path, '.auto-context/wiki/decisions/card.md', 'project root 상대 경로');
    assert.ok(!isAbsolute(path), '홈 경로가 노출되는 절대경로를 쓰지 않는다');
    assert.ok(existsSync(join(dir, path)), `주입 경로가 실제 파일이어야 함: ${path}`);
  });
});

// cwd가 project root의 하위 디렉터리인 세션(project root 상대경로가 모델 cwd에서는
// 안 열리는 경우). 함수 단위로 검증하는 이유: hook 전체 경로로 재현하려면 프로젝트를
// HOME 하위에 만들어야 한다(config 부모 탐색이 HOME 경계까지만 올라간다) — tmpdir은
// HOME 밖이라 하위 cwd에서 설정 자체를 못 찾고 이 분기까지 도달하지 않는다.
test('display_card_path: cwd 하위면 상대경로, 그 밖이면 절대경로 (../ 사슬 회피)', () => {
  const out = execFileSync('python3', ['-c', [
    'import json, sys, pathlib',
    'sys.path.insert(0, "core")',
    'import recall',
    // 프로덕션에서 path는 resolve_wiki_result_path가 이미 resolve()한 값이다(동일 조건).
    'card = pathlib.Path("/tmp/p/.auto-context/wiki/decisions/x.md").resolve()',
    'print(json.dumps({',
    '  "at_root": recall.display_card_path(card, "/tmp/p"),',
    '  "at_subdir": recall.display_card_path(card, "/tmp/p/docs"),',
    '}))',
  ].join('\n')], { encoding: 'utf8' });
  const r = JSON.parse(out);
  assert.equal(r.at_root, '.auto-context/wiki/decisions/x.md', 'cwd == project root → 상대경로');
  assert.ok(isAbsolute(r.at_subdir), `하위 cwd에서는 절대경로: ${r.at_subdir}`);
  assert.doesNotMatch(r.at_subdir, /\.\./, '../ 사슬을 만들지 않는다');
});

test('auto:end 밖 수동 섹션(dedup 병합 고유 사실)도 주입된다', () => {
  const manual = [
    '',
    '## 병합된 고유 사실',
    '- 레거시 .auto-context.json 경로는 v0.7에서 이동됐다.',
    '',
    '<!-- merged from decisions/other.md by wiki-dedup 2026-07-29 -->',
  ].join('\n');
  withProject({
    cards: { 'card.md': card(VERIFIED_FM, '설정 레이아웃 결론 본문.', manual) },
  }, ({ dir, fixture, write }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    assert.match(ctx, /설정 레이아웃 결론 본문\./);
    assert.match(ctx, /레거시 \.auto-context\.json 경로는 v0\.7에서 이동됐다\./, '수동 섹션 포함');
    assert.doesNotMatch(ctx, /merged from decisions\/other\.md/, 'HTML 주석(출처 메타)은 제외');
  });
});

test('injectSummaryMaxChars 상한이 적용되고 초과분은 절단 표시와 함께 잘린다', () => {
  const long = Array.from({ length: 12 }, (_, i) => `문장${i} 이것은 상한 검증을 위한 충분히 긴 서술이다.`).join(' ');
  withProject({
    settings: { injectSummaryMaxChars: 120 },
    cards: { 'card.md': card(VERIFIED_FM, long) },
  }, ({ dir, fixture, write }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    assert.ok(ctx.length < long.length, '상한이 실제로 줄여야 함');
    assert.match(ctx, /… \(이하 생략\)$/m, '절단 표시');
    const body = ctx.split('\n').find((l) => l.startsWith('  문장0'));
    assert.ok(body.trim().length <= 120 + '… (이하 생략)'.length, `본문 길이 상한 초과: ${body.length}`);
    assert.match(body, /이다\.… \(이하 생략\)$/, '문장 경계에서 자른다');
  });
});

test('injectSummaryMaxChars: 0 → 본문 주입을 끄고 경로+title만 남긴다', () => {
  withProject({
    settings: { injectSummaryMaxChars: 0 },
    cards: { 'card.md': card(VERIFIED_FM, '본문은 주입되지 않아야 한다.') },
  }, ({ dir, fixture, write }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    assert.doesNotMatch(ctx, /본문은 주입되지 않아야 한다/);
    assert.doesNotMatch(ctx, /요약으로 충분하면/, '본문이 없으면 안내도 붙지 않는다');
    assert.match(ctx, /\.auto-context\/wiki\/decisions\/card\.md - 카드 정식 제목/, '경로+title은 유지');
  });
});

test('wikiOnly: raw 결과는 본문도 카드 경로도 얻지 못한다 (raw 누출 금지)', () => {
  withProject({
    raw: { 'outside.md': '---\nstatus: verified\n---\n# Outside\nraw 원문 본문은 절대 주입되면 안 된다.\n' },
    cards: { 'card.md': card(VERIFIED_FM, 'wiki 카드 본문만 나와야 한다.') },
  }, ({ dir, fixture, write }) => {
    write([
      { file: 'proj-docs/outside.md', title: 'Outside', score: 1 },
      { file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 0.5 },
    ]);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    assert.match(ctx, /wiki 카드 본문만 나와야 한다\./);
    assert.doesNotMatch(ctx, /raw 원문 본문은 절대 주입되면 안 된다/, 'raw 본문 누출');
    assert.doesNotMatch(ctx, /outside\.md/, 'wikiOnly에서 raw 결과 자체가 나오면 안 됨');
  });
});

test('flat + raw role 결과에는 본문이 붙지 않는다 (본문 주입은 wiki 카드 전용)', () => {
  withProject({
    settings: { recallStrategy: 'flat' },
    raw: { 'outside.md': '---\nstatus: verified\n---\n# Outside\nraw 원문 본문은 절대 주입되면 안 된다.\n' },
  }, ({ dir, fixture, write }) => {
    write([{ file: 'proj-docs/outside.md', title: 'Outside', score: 1 }]);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    assert.match(ctx, /outside\.md - Outside/, 'raw는 예전 포맷(데몬 title) 유지');
    assert.doesNotMatch(ctx, /raw 원문 본문은 절대 주입되면 안 된다/);
    assert.doesNotMatch(ctx, /요약으로 충분하면/);
  });
});

test('recallVerifiedOnly:false — 미검수 카드도 본문과 함께 배지·인용 금지 안내가 유지된다', () => {
  const generatedFm = [
    'title: "미검수 카드 제목"',
    'status: generated',
    'createdBy: qmd-auto-context',
    'reviewed: false',
  ].join('\n');
  withProject({
    settings: { compile: { recallVerifiedOnly: false } },
    cards: { 'gen.md': card(generatedFm, '미검수 카드의 본문이다.') },
  }, ({ dir, fixture, write }) => {
    write([{ file: 'proj-wiki/decisions/gen.md', title: 'Summary', score: 1 }]);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir }, { QMD_QUERY_FIXTURE: fixture });
    assert.match(ctx, /gen\.md - 미검수 카드 제목 \(미검수\)/, '배지가 title 뒤에 유지');
    assert.match(ctx, /단독 캐논 근거로 인용 금지/, '인용 금지 안내 유지');
    assert.match(ctx, /미검수 카드의 본문이다\./, '본문은 그대로 주입');
  });
});

test('카드 파일 해석 실패는 기존 fail-closed 동작을 유지한다 (본문·경로 없이 drop)', () => {
  withProject({
    cards: { 'card.md': card(VERIFIED_FM, '있는 카드.') },
  }, ({ dir, fixture, write }) => {
    // 디스크에 없는 카드 → resolve 실패 → 미검수 fail-close → recallVerifiedOnly 기본값에서 drop.
    write([{ file: 'proj-wiki/decisions/missing.md', title: 'Summary', score: 1 }]);
    const log = join(dir, 'recall.log');
    const out = runRecall({ prompt: PROMPT, cwd: dir },
      { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log }).trim();
    assert.equal(out, '', '해석 실패 카드는 surface하지 않는다');
    const lines = execFileSync('cat', [log], { encoding: 'utf8' }).trim().split('\n').map(JSON.parse);
    const sel = lines.find((l) => l.event === 'qmd_recall_selection' && l.reason);
    assert.equal(sel.reason, 'no_results_after_filter', '기존 reason 계약 유지');
    assert.equal(sel.dropped_unverified, 1);
  });
});

test('stdout에는 훅 JSON 한 줄만 나온다 (본문 주입이 stdout을 오염시키지 않는다)', () => {
  withProject({
    cards: { 'card.md': card(VERIFIED_FM, '여러\n줄로\n\n이루어진 본문.') },
  }, ({ dir, fixture, write }) => {
    write([{ file: 'proj-wiki/decisions/card.md', title: 'Summary', score: 1 }]);
    const out = runRecall({ prompt: PROMPT, cwd: dir },
      { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: join(dir, 'recall.log') });
    assert.equal(out.trim().split('\n').length, 1, '훅 JSON 외 라인이 있으면 host가 파싱에 실패한다');
    const parsed = JSON.parse(out.trim());
    assert.deepEqual(Object.keys(parsed), ['hookSpecificOutput']);
    assert.equal(parsed.hookSpecificOutput.hookEventName, 'UserPromptSubmit');
    assert.match(parsed.hookSpecificOutput.additionalContext, /이루어진 본문\./);
  });
});
