import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { removeTemp } from './helpers/temp.mjs';

const CARD_REL = '.auto-context/wiki/concepts/test-card.md';
const HASH = 'abc123';

function cardText(status = 'generated', extraFm = '') {
  return `---
title: "Test Card"
status: ${status}
createdBy: qmd-auto-context
reviewed: false${extraFm}
---

> Auto-generated by qmd-auto-context from conversation/work context. Review, edit, or delete if wrong.

<!-- qmd:auto:start id="main" sourceHash="${HASH}" -->
## Summary
Durable claim: the source documents cite markdown.
<!-- qmd:auto:end -->
`;
}

function setupProject({ verify = {}, extractorArgv = null, extractor = null, cardStatus = 'generated', jobOverrides = {}, withSource = true } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'qwiki-verify-'));
  mkdirSync(join(dir, '.auto-context', 'compile'), { recursive: true });
  mkdirSync(join(dir, '.auto-context', 'wiki', 'concepts'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  if (withSource) {
    writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable claim: the source documents cite markdown.\n');
  }
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-docs', 'proj-wiki'],
    collectionPaths: { 'proj-docs': 'docs', 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-docs': 'raw', 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      mode: 'auto-wiki',
      defaultStatus: 'generated',
      triggers: ['post_tool_source', 'manual'],
      maxSourceChars: 12000,
      // 단일 argv(`extractor.argv`)는 스키마에서 사라졌다 — 모든 argv는 엔진 라벨을
      // 통해서만 온다. 잡의 생성 엔진이 'claude'이므로 그 라벨 아래에 둔다.
      extractor: extractor || { backends: extractorArgv ? { claude: extractorArgv } : {}, timeout: 30 },
      verify: { enabled: true, timeout: 30, ...verify },
    },
  }));
  writeFileSync(join(dir, CARD_REL), cardText(cardStatus));
  writeFileSync(join(dir, '.auto-context', 'compile', 'verify-queue.jsonl'), JSON.stringify({
    ts: '2026-07-04T00:00:00Z',
    targetPath: CARD_REL,
    sources: [{ kind: 'file', path: 'docs/source.md', collection: 'proj-docs' }],
    sourceHash: HASH,
    engine: 'claude',
    trigger: 'post_tool_source',
    ...jobOverrides,
  }) + '\n');
  return dir;
}

function mockVerifier(verdictJson) {
  const script = join(mkdtempSync(join(tmpdir(), 'verifier-')), 'verify.py');
  writeFileSync(script, `#!/usr/bin/env python3
import json, sys
payload = json.loads(sys.stdin.read())
assert payload.get('task') == 'verify', 'verify payload expected'
assert 'content' in payload['card']
assert payload['sources'], 'sources must be loaded'
print(json.dumps(json.loads(${JSON.stringify(JSON.stringify(verdictJson))})))
`);
  return script;
}

function runVerifyWorker(project, env = {}) {
  return execFileSync('python3', ['core/wiki_verify_worker.py', '--cwd', project, '--json'], {
    cwd: process.cwd(),
    encoding: 'utf8',
    // QMD_DIRTY_QUEUE를 임시 경로로 격리하지 않으면 dirty queue 유출 시 사용자 실제 qmd 인덱스에 고아 컬렉션이 등록되며(복구 불가 고아 등록), 자동으로 정리할 수 있는 경로가 없다.
    env: { ...process.env, QMD_DIRTY_QUEUE: join(project, 'dirty-queue'), ...env },
  });
}

function engineCooldown(project) {
  const path = join(project, '.auto-context', 'compile', 'verify-engine-cooldown.json');
  return existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : {};
}

function jsonl(path) {
  if (!existsSync(path)) return [];
  return readFileSync(path, 'utf8').trim().split('\n').filter(Boolean).map((line) => JSON.parse(line));
}

test('verify pass → status verified + verifiedBy/verifiedAt 패치 + 재인덱싱 enqueue', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [{ claim: 'c', supported: true, quote: 'q', sourcePath: 'docs/source.md' }], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vp-')), 'queue');
  try {
    const out = JSON.parse(runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue }));
    assert.equal(out.processed, 1);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: verified$/m);
    assert.match(text, /^verifiedBy: "?claude"?$/m);
    assert.match(text, /^verifiedAt: /m);
    assert.match(text, /Durable claim/, '관리 블록 본문은 보존');
    assert.match(readFileSync(dirtyQueue, 'utf8'), /^proj-wiki\t/);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'verified');
    assert.equal(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), '');
  } finally { removeTemp(project); }
});

test('verify fail + onFail 기본(delete) → 카드 삭제, tombstone 없음, 재인덱싱 enqueue', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [{ claim: 'c', supported: false, quote: '', sourcePath: 'docs/source.md' }], reasons: ['source contradicts claim'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vf-')), 'queue');
  try {
    runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue });
    assert.equal(existsSync(join(project, CARD_REL)), false, '반증된 카드는 즉시 삭제');
    const tombstones = join(project, '.auto-context', 'compile', 'tombstones.jsonl');
    assert.equal(jsonl(tombstones).length, 0, 'tombstone을 세우지 않아 소스 수정 후 재생성 가능');
    assert.match(readFileSync(dirtyQueue, 'utf8'), /^proj-wiki\t/);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'deleted');
    assert.equal(log[0].reasons[0], 'source contradicts claim');
  } finally { removeTemp(project); }
});

// 기계 판정이 카드를 지우는 유일한 게이트이므로 삭제 사유는 pass 트래픽과 분리된
// 파일에 남아야 한다 — fail은 억제 마커(verify-skipped)를 남기지 않으므로 이 원장이
// 유일한 지속 기록이다.
test('verify fail delete → verify-deleted.jsonl 감사 레코드 (fail은 억제 마커 없음)', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [{ claim: 'c', supported: false, quote: '', sourcePath: 'docs/source.md' }], reasons: ['source contradicts claim'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  try {
    runVerifyWorker(project);
    const deleted = jsonl(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl'));
    assert.equal(deleted.length, 1);
    assert.equal(deleted[0].targetPath, CARD_REL);
    assert.equal(deleted[0].verdict, 'fail');
    assert.equal(deleted[0].engine, 'claude');
    assert.equal(deleted[0].reasons[0], 'source contradicts claim');
    assert.deepEqual(deleted[0].sourcePaths, ['docs/source.md']);
    assert.equal(deleted[0].claims, 1);
    assert.ok(deleted[0].deletedAt);
    assert.equal(JSON.stringify(deleted[0]).includes('Durable claim'), false, '원문 본문은 담지 않는다');
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0,
      'fail은 재컴파일을 막지 않으므로 억제 마커 없음 — 감사 추적은 verify-deleted가 책임');
  } finally { removeTemp(project); }
});

test('verify-deleted.jsonl은 상한을 넘어도 트림되지 않는다 (verify-log와 대비)', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [], reasons: ['contradiction'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const deletedPath = join(project, '.auto-context', 'compile', 'verify-deleted.jsonl');
  const logPath = join(project, '.auto-context', 'compile', 'verify-log.jsonl');
  // 둘 다 LOG_MAX_BYTES(256KB) 초과 상태로 시작 — 트림 대상이면 절반이 날아간다.
  const bulk = (tag) => Array.from({ length: 400 }, (_, i) => JSON.stringify({ i, tag, pad: 'x'.repeat(700) })).join('\n') + '\n';
  writeFileSync(deletedPath, bulk('old-deletion'));
  writeFileSync(logPath, bulk('old-verdict'));
  try {
    runVerifyWorker(project);
    const deleted = jsonl(deletedPath);
    assert.equal(deleted.length, 401, '기존 400줄 보존 + 새 삭제 1줄');
    assert.equal(deleted[0].i, 0, '가장 오래된 삭제 이력이 남아 있다');
    assert.equal(deleted[400].verdict, 'fail');
    const log = jsonl(logPath);
    assert.equal(log.length, 201, 'verify-log는 상한 초과 시 최근 절반만 유지');
    assert.equal(log[0].i, 200);
  } finally { removeTemp(project); }
});

test('verify fail + onFail=contested → status contested 패치(파일 보존)', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [], reasons: ['contradiction'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], verify: { onFail: 'contested' } });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vc-')), 'queue');
  try {
    runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue });
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: contested$/m);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl')), false,
      '삭제하지 않았으면 삭제 원장에 쓰지 않는다');
  } finally { removeTemp(project); }
});

test('inconclusive + onInconclusive=none → generated 유지 + log 기록 (하위호환)', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['source truncated'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], verify: { onInconclusive: 'none' } });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'inconclusive');
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0,
      '삭제하지 않았으면 억제 마커도 남기지 않는다');
  } finally { removeTemp(project); }
});

test('inconclusive + onInconclusive 기본(delete) → 카드 삭제 + 억제 마커 + 삭제 사유 로그', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['verifier could not adjudicate'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vi-')), 'queue');
  try {
    runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue });
    assert.equal(existsSync(join(project, CARD_REL)), false, '판정 불가 카드도 삭제');
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'tombstones.jsonl')).length, 0,
      'tombstone 없음 — 소스 변경 시 재생성 가능');
    assert.match(readFileSync(dirtyQueue, 'utf8'), /^proj-wiki\t/, '삭제 후 wiki 재인덱싱');

    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'deleted');
    assert.equal(log[0].verdict, 'inconclusive', '삭제 사유(verdict) 추적 가능');
    assert.equal(log[0].reasons[0], 'verifier could not adjudicate');
    assert.equal(log[0].suppressedSources, 1);

    const skipped = jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl'));
    assert.equal(skipped.length, 1);
    assert.equal(skipped[0].sourcePath, 'docs/source.md');
    assert.equal(skipped[0].verdict, 'inconclusive');
    assert.equal(skipped[0].targetPath, CARD_REL);
    assert.match(skipped[0].sourceBodyHash, /^[a-f0-9]{32}$/);
    assert.ok(skipped[0].deletedAt, '삭제 시각 기록 — verify-log 트림 후에도 남는 감사 추적');

    const deleted = jsonl(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl'));
    assert.equal(deleted.length, 1, 'inconclusive 삭제도 삭제 원장에 기록');
    assert.equal(deleted[0].verdict, 'inconclusive');
    assert.equal(deleted[0].reasons[0], 'verifier could not adjudicate');
  } finally { removeTemp(project); }
});

test('inconclusive delete: reviewed 카드는 삭제되지 않는다 (사람 판단 보호)', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['unclear'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], cardStatus: 'reviewed' });
  try {
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, CARD_REL)), true, 'reviewed 카드는 기계 삭제 대상 아님');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: reviewed$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'not_generated');
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0);
  } finally { removeTemp(project); }
});

test('inconclusive + onInconclusive=contested → 파일 보존 + status contested', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['unclear'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], verify: { onInconclusive: 'contested' } });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: contested$/m);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0);
  } finally { removeTemp(project); }
});

test('transient(CLI 부재 127)는 inconclusive로 오분류되지 않는다 — 카드 보존 + 큐 보존', () => {
  const project = setupProject({ extractorArgv: ['/nonexistent/verify-cli-xyz'] });
  try {
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, CARD_REL)), true, 'CLI 없는 머신에서 카드가 전멸해선 안 됨');
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), /test-card\.md/);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0,
      'transient은 억제 마커를 남기지 않는다 — CLI 설치 후 재시도되어야 함');
  } finally { removeTemp(project); }
});

test('transient(timeout)는 inconclusive로 오분류되지 않는다 — 카드 보존 + cooldown', () => {
  const slow = join(mkdtempSync(join(tmpdir(), 'verifier-slow-i-')), 'verify.py');
  writeFileSync(slow, '#!/usr/bin/env python3\nimport time\ntime.sleep(5)\n');
  const project = setupProject({ extractorArgv: ['python3', slow], verify: { timeout: 1 } });
  try {
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, CARD_REL)), true);
    // 실패한 후보만 식힌다(0.x의 전역 verify-cooldown 대체) — 전역이면 한 엔진 실패가
    // 프로젝트 전체 검수를 막고 다음 후보로 degrade하지 못했다.
    assert.deepEqual(Object.keys(engineCooldown(project)), ['claude']);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0);
  } finally { removeTemp(project); }
});

test('verifier CLI 부재(127) → 큐 보존(설치 대기)', () => {
  const project = setupProject({ extractorArgv: ['/nonexistent/verify-cli-xyz'] });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    const queue = readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8');
    assert.match(queue, /test-card\.md/, '127이면 잡 보존');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
  } finally { removeTemp(project); }
});

test('verifier timeout → 후보 단위 cooldown 생성 + 큐 보존 (compile cooldown과 분리)', () => {
  const slow = join(mkdtempSync(join(tmpdir(), 'verifier-slow-')), 'verify.py');
  writeFileSync(slow, '#!/usr/bin/env python3\nimport time\ntime.sleep(5)\n');
  const project = setupProject({ extractorArgv: ['python3', slow], verify: { timeout: 1 } });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    assert.ok(Object.keys(engineCooldown(project)).length > 0);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'cooldown')), false, 'compile cooldown은 건드리지 않음');
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), /test-card\.md/);
  } finally { removeTemp(project); }
});

test('verify.enabled=false → 큐 미소비(무동작)', () => {
  const project = setupProject({ verify: { enabled: false } });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), /test-card\.md/);
  } finally { removeTemp(project); }
});

test('처리 전 카드가 reviewed 상태로 바뀐 경우 skip (사람 검수 존중)', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], cardStatus: 'reviewed' });
  try {
    runVerifyWorker(project);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: reviewed$/m, '사람 검수 status는 기계가 건드리지 않음');
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'skipped');
    assert.equal(log[0].reason, 'not_generated');
  } finally { removeTemp(project); }
});

test('job sourceHash와 카드 블록 hash 불일치 → stale_job skip', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], jobOverrides: { sourceHash: 'deadbeef' } });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'stale_job');
  } finally { removeTemp(project); }
});

test('소스 전부 소실 → source_missing skip, generated 유지(미검수 배지 유지)', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], withSource: false });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'source_missing');
  } finally { removeTemp(project); }
});

test('source_missing은 트림되지 않는 원장(source-missing.jsonl)에도 남는다', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], withSource: false });
  try {
    runVerifyWorker(project);
    const rows = jsonl(join(project, '.auto-context', 'compile', 'source-missing.jsonl'));
    assert.equal(rows.length, 1, 'verify-log.jsonl은 트림 대상이라 이 신호가 유실됐다 — 원장에 별도 보존');
    assert.equal(rows[0].targetPath, CARD_REL);
    assert.equal(rows[0].action, 'detected');
    assert.equal(rows[0].origin, 'verify');
    assert.equal(rows[0].status, 'generated');
    assert.deepEqual(rows[0].missingSources, ['docs/source.md']);
    // 카드는 그대로 남는다(삭제·downgrade 없음).
    assert.equal(existsSync(join(project, CARD_REL)), true);
  } finally { removeTemp(project); }
});

test('소스가 살아 있으면(읽기 실패 등) 원장에 소실로 기록하지 않는다', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  try {
    // 소스가 존재하지만 job이 kind를 file이 아닌 것으로 들고 있는 경우: load_sources는
    // 0건이지만 "원문 소실"은 아니다.
    writeFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), JSON.stringify({
      ts: '2026-07-04T00:00:00Z',
      targetPath: CARD_REL,
      sources: [{ kind: 'url', path: 'https://example.com/x' }],
      sourceHash: HASH,
      engine: 'claude',
      trigger: 'post_tool_source',
    }) + '\n');
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'source-missing.jsonl')), false);
  } finally { removeTemp(project); }
});

test('trim_jsonl: 상한 초과 시 최근 절반만 유지', () => {
  const dir = mkdtempSync(join(tmpdir(), 'trim-'));
  const log = join(dir, 'verify-log.jsonl');
  const lines = Array.from({ length: 100 }, (_, i) => JSON.stringify({ i, pad: 'x'.repeat(50) })).join('\n') + '\n';
  writeFileSync(log, lines);
  try {
    execFileSync('python3', ['-c', `
import sys
sys.path.insert(0, 'core')
from pathlib import Path
import wiki_compile as w
w.trim_jsonl(Path(${JSON.stringify(log)}), max_bytes=1024)
`], { cwd: process.cwd(), encoding: 'utf8' });
    const rows = jsonl(log);
    assert.equal(rows.length, 50, '절반 유지');
    assert.equal(rows[0].i, 50, '최근 절반(뒤쪽)이 남음');
  } finally { removeTemp(dir); }
});

// 루프 방지: inconclusive 삭제는 매번 host CLI 호출(=사용자 과금)을 유발하므로,
// 같은 소스 내용이 재후보가 되면 extractor를 띄우기 전에 skip해야 한다.
function setupLoopProject(dual) {
  const dir = mkdtempSync(join(tmpdir(), 'qwiki-loop-'));
  mkdirSync(join(dir, '.auto-context', 'compile'), { recursive: true });
  mkdirSync(join(dir, '.auto-context', 'wiki'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-docs', 'proj-wiki'],
    collectionPaths: { 'proj-docs': 'docs', 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-docs': 'raw', 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      mode: 'auto-wiki',
      defaultStatus: 'generated',
      triggers: ['post_tool_source', 'manual'],
      semanticDedup: { enabled: false },
      extractor: { backends: { claude: ['python3', dual] }, timeout: 30 },
      verify: { enabled: true, timeout: 30 },
    },
  }));
  return dir;
}

function inconclusiveDualMock(counter) {
  const dual = join(mkdtempSync(join(tmpdir(), 'dual-inc-')), 'dual.py');
  writeFileSync(dual, `#!/usr/bin/env python3
import json, sys
payload = json.loads(sys.stdin.read())
with open(${JSON.stringify(counter)}, 'a') as fh:
    fh.write((payload.get('task') or 'extract') + '\\n')
if payload.get('task') == 'verify':
    print(json.dumps({'verdict': 'inconclusive', 'claims': [], 'reasons': ['verifier could not adjudicate']}))
else:
    print(json.dumps({'candidates': [{
      'title': 'Loop Decision',
      'summary': 'Durable decision: loop guard suppresses unchanged sources.',
      'suggestedType': 'decision',
      'confidence': 'high',
      'targetPath': '.auto-context/wiki/decisions/loop-decision.md'
    }]}))
`);
  return dual;
}

test('루프 방지: 같은 소스·같은 body-hash 재후보는 extractor 호출 없이 skip, 소스 변경 시 재시도', () => {
  const counterDir = mkdtempSync(join(tmpdir(), 'counter-'));
  const counter = join(counterDir, 'calls.log');
  const dual = inconclusiveDualMock(counter);
  const dir = setupLoopProject(dual);
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-loop-')), 'queue');
  const page = join(dir, '.auto-context', 'wiki', 'decisions', 'loop-decision.md');
  const skippedPath = join(dir, '.auto-context', 'compile', 'verify-skipped.jsonl');
  const candidates = join(dir, '.auto-context', 'compile', 'candidates.jsonl');
  const enqueueSource = () => writeFileSync(
    join(dir, '.auto-context', 'compile', 'source-queue.jsonl'),
    JSON.stringify({
      ts: '2026-07-04T00:00:00Z',
      trigger: 'post_tool_source',
      engine: 'claude',
      cwd: dir,
      source: { kind: 'file', path: 'docs/source.md', collection: 'proj-docs' },
    }) + '\n',
  );
  const runWorker = () => execFileSync('python3', ['core/wiki_compile_worker.py', '--cwd', dir, '--flush-all'], {
    cwd: process.cwd(), encoding: 'utf8',
    env: { ...process.env, QMD_DIRTY_QUEUE: dirtyQueue },
  });
  const calls = () => readFileSync(counter, 'utf8').trim().split('\n').filter(Boolean);

  try {
    writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable decision: loop guard suppresses unchanged sources.\n');
    enqueueSource();
    runWorker();
    assert.equal(existsSync(page), false, '1회차: inconclusive → 카드 삭제');
    assert.equal(jsonl(skippedPath).length, 1, '1회차: 억제 마커 기록');
    assert.deepEqual(calls(), ['extract', 'verify'], '1회차는 extract + verify 각 1회');

    // 2회차: 소스 내용 동일 — sync/mtime 변화로 재enqueue될 수 있는 현실 경로.
    enqueueSource();
    runWorker();
    assert.deepEqual(calls(), ['extract', 'verify'], '2회차는 host CLI를 아예 호출하지 않는다');
    assert.equal(existsSync(page), false);
    const skipRow = jsonl(candidates).filter((r) => r.reason === 'verify_inconclusive_suppressed');
    assert.equal(skipRow.length, 1, 'skip 사유가 candidates 로그에 남는다');
    assert.equal(skipRow[0].action, 'skipped');

    // 3회차: 소스 본문이 실제로 바뀌면 억제가 풀리고 다시 시도된다.
    writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable decision: loop guard retries when the source body changes.\n');
    enqueueSource();
    runWorker();
    assert.deepEqual(calls(), ['extract', 'verify', 'extract', 'verify'], '소스 변경 후 재시도');
    assert.equal(jsonl(skippedPath).length, 2, '새 body-hash로 마커 갱신');
    const hashes = jsonl(skippedPath).map((r) => r.sourceBodyHash);
    assert.notEqual(hashes[0], hashes[1], '기록된 hash가 소스 내용에 따라 달라진다');

    // 기계 삭제는 사용자 삭제로 오독되면 안 된다: manifest의 verify-deleted 마커가
    // 없으면 3회차가 tombstoned로 영구 억제돼 "소스 고치면 재생성"이 성립하지 않는다.
    assert.equal(jsonl(join(dir, '.auto-context', 'compile', 'tombstones.jsonl')).length, 0);
    const actions = jsonl(candidates).map((r) => r.action);
    assert.deepEqual(actions, ['created', 'skipped', 'created'], 'tombstoned 없이 재생성');
  } finally {
    removeTemp(dir);
    removeTemp(counterDir);
  }
});

test('end-to-end 피기백: compile worker 1회 실행으로 생성→검증→verified 승격까지', () => {
  // task 분기 mock: extraction 요청엔 candidates, verify 요청엔 pass verdict.
  const dual = join(mkdtempSync(join(tmpdir(), 'dual-')), 'dual.py');
  writeFileSync(dual, `#!/usr/bin/env python3
import json, sys
payload = json.loads(sys.stdin.read())
if payload.get('task') == 'verify':
    print(json.dumps({'verdict': 'pass', 'claims': [], 'reasons': []}))
else:
    print(json.dumps({'candidates': [{
      'title': 'E2E Decision',
      'summary': 'Durable decision: generated wiki pages cite source markdown.',
      'suggestedType': 'decision',
      'confidence': 'high',
      'targetPath': '.auto-context/wiki/decisions/e2e-decision.md'
    }]}))
`);
  const dir = mkdtempSync(join(tmpdir(), 'qwiki-e2e-'));
  mkdirSync(join(dir, '.auto-context', 'compile'), { recursive: true });
  mkdirSync(join(dir, '.auto-context', 'wiki'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable decision: generated wiki pages cite source markdown.\n');
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-docs', 'proj-wiki'],
    collectionPaths: { 'proj-docs': 'docs', 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-docs': 'raw', 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      mode: 'auto-wiki',
      defaultStatus: 'generated',
      triggers: ['post_tool_source', 'manual'],
      semanticDedup: { enabled: false },
      extractor: { backends: { claude: ['python3', dual] }, timeout: 30 },
      verify: { enabled: true, timeout: 30 },
    },
  }));
  writeFileSync(join(dir, '.auto-context', 'compile', 'source-queue.jsonl'), JSON.stringify({
    ts: '2026-07-04T00:00:00Z',
    trigger: 'post_tool_source',
    engine: 'claude',
    cwd: dir,
    source: { kind: 'file', path: 'docs/source.md', collection: 'proj-docs' },
  }) + '\n');
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-e2e-')), 'queue');
  try {
    execFileSync('python3', ['core/wiki_compile_worker.py', '--cwd', dir, '--flush-all'], {
      cwd: process.cwd(), encoding: 'utf8',
      env: { ...process.env, QMD_DIRTY_QUEUE: dirtyQueue },
    });
    const page = join(dir, '.auto-context', 'wiki', 'decisions', 'e2e-decision.md');
    assert.equal(existsSync(page), true);
    const text = readFileSync(page, 'utf8');
    assert.match(text, /^status: verified$/m, '한 번의 worker 실행에서 생성 직후 검증·승격');
    assert.match(text, /^verifiedBy: "?claude"?$/m);
    assert.equal(readFileSync(join(dir, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), '');
  } finally { removeTemp(dir); }
});

// ---------------------------------------------------------------------------
// 4단계: verifier engine을 extractor와 분리 (cross-engine 우선 + degrade 기록)
// ---------------------------------------------------------------------------

// 엔진별 mock adapter. 호출 사실을 tracker 파일에 append하므로 "어느 엔진이 실제로
// 실행됐는지"와 "실행되지 **않았는지**"(과금 방지)를 둘 다 단정할 수 있다.
function mockEngine(name, tracker, behavior) {
  const script = join(mkdtempSync(join(tmpdir(), `verifier-${name}-`)), `${name}.py`);
  const body = {
    absent: 'sys.exit(127)',
    // 인증 안 된 host CLI: lib.py가 CLI의 비0 종료코드를 그대로 전파한다(비127).
    exit1: 'sys.exit(1)',
    slow: 'import time\ntime.sleep(5)',
  }[behavior] || `print(json.dumps({"verdict": ${JSON.stringify(behavior)}, "claims": [{"claim": "c", "supported": ${behavior === 'pass' ? 'True' : 'False'}, "quote": "q", "sourcePath": "docs/source.md"}], "reasons": ["by ${name}"]}))`;
  writeFileSync(script, `#!/usr/bin/env python3
import json, sys
sys.stdin.read()
with open(${JSON.stringify(tracker)}, "a") as fh:
    fh.write("${name}\\n")
${body}
`);
  return ['python3', script];
}

function trackerFile(label) {
  return join(mkdtempSync(join(tmpdir(), `tracker-${label}-`)), 'calls');
}

function calls(tracker) {
  return existsSync(tracker) ? readFileSync(tracker, 'utf8').trim().split('\n').filter(Boolean) : [];
}

test('cross-engine: 카드를 만든 엔진(claude)이 아닌 codex가 검수하고 verifiedMode를 기록한다', () => {
  const tracker = trackerFile('cross');
  const project = setupProject({
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'pass') },
    },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: verified$/m);
    assert.match(text, /^verifiedBy: "?codex"?$/m, '카드를 만든 claude가 아니라 codex가 검수');
    assert.match(text, /^verifiedMode: "?cross-engine"?$/m);
    assert.match(text, /^verifiedAt: /m);
    assert.deepEqual(calls(tracker), ['codex'], 'claude는 아예 호출되지 않는다(중복 과금 없음)');
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'verified');
    assert.equal(log[0].verifiedMode, 'cross-engine');
    assert.equal(log[0].producedBy, 'claude');
    assert.deepEqual(log[0].enginesAttempted, ['codex']);
  } finally { removeTemp(project); }
});

test('degrade: 다른 엔진 CLI가 없으면(127) 같은 엔진으로 검수하되 self로 기록한다', () => {
  const tracker = trackerFile('degrade');
  const project = setupProject({
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'absent') },
    },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    // 강제하지 않는 이유: 검수를 못 하면 카드는 generated로 남고 recallVerifiedOnly
    // 기본값 아래에서 wiki 전체가 recall에서 사라진다(사람 검수 복구 경로 없음).
    assert.match(text, /^status: verified$/m, '다른 엔진이 없어도 검수는 계속된다');
    assert.match(text, /^verifiedBy: "?claude"?$/m);
    assert.match(text, /^verifiedMode: "?self"?$/m, '자기검증 사실이 카드에 남는다');
    assert.deepEqual(calls(tracker), ['codex', 'claude'], '다른 엔진 먼저 시도 후 폴백');
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].verifiedMode, 'self');
    assert.deepEqual(log[0].enginesAttempted, ['codex', 'claude']);
  } finally { removeTemp(project); }
});

test('crossEngine:require + 다른 엔진 없음 → 검수 안 함, 카드 보존 + 큐 보존', () => {
  const tracker = trackerFile('require');
  const project = setupProject({
    verify: { crossEngine: 'require' },
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass') },
    },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 0);
    assert.deepEqual(calls(tracker), [], '자기검증을 금지했으므로 아무 CLI도 호출하지 않는다');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m, '카드는 삭제되지 않는다');
    assert.match(
      readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'),
      /test-card\.md/, '두 번째 CLI가 설정되면 검증되도록 잡 보존');
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'cross_engine_unavailable');
    assert.equal(log[0].crossEngine, 'require');
  } finally { removeTemp(project); }
});

test('crossEngine:off → 0.x 동작(카드를 만든 엔진이 검수, mode self)', () => {
  const tracker = trackerFile('off');
  const project = setupProject({
    verify: { crossEngine: 'off' },
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'pass') },
    },
  });
  try {
    runVerifyWorker(project);
    assert.deepEqual(calls(tracker), ['claude']);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^verifiedMode: "?self"?$/m);
  } finally { removeTemp(project); }
});

test('실패 분류 경계: 다른 엔진 timeout은 다음 엔진으로 넘기지 않는다(cooldown + 큐 보존)', () => {
  const tracker = trackerFile('timeout-boundary');
  const project = setupProject({
    verify: { timeout: 1 },
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'slow') },
    },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 0);
    // timeout은 이미 host CLI를 호출한 것이다 — 다음 엔진으로 넘기면 같은 카드에 대해
    // 사용자 계정이 두 번 청구된다. 127(실행 자체 실패, 과금 0)만 다음 후보로 넘어간다.
    assert.deepEqual(calls(tracker), ['codex'], 'timeout 후 claude로 재시도하지 않는다');
    assert.deepEqual(Object.keys(engineCooldown(project)), ['codex'], '실패한 후보만 식힌다');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    // transient가 inconclusive(=삭제)로 흐르지 않았음을 확인
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl')).length, 0);
  } finally { removeTemp(project); }
});

test('전 후보 CLI 부재(127) → 카드·큐 보존, transient로 처리(삭제 없음)', () => {
  const tracker = trackerFile('all-absent');
  const project = setupProject({
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'absent'), codex: mockEngine('codex', tracker, 'absent') },
    },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 0);
    assert.deepEqual(calls(tracker), ['codex', 'claude'], '후보 전원 시도');
    assert.equal(existsSync(join(project, CARD_REL)), true);
    assert.match(
      readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'),
      /test-card\.md/);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl')).length, 0);
  } finally { removeTemp(project); }
});

test('cross-engine fail 삭제 → 원장에 verifiedMode/producedBy가 함께 남는다', () => {
  const tracker = trackerFile('cross-fail');
  const project = setupProject({
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'fail') },
    },
  });
  try {
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, CARD_REL)), false);
    const deleted = jsonl(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl'));
    assert.equal(deleted[0].engine, 'codex');
    assert.equal(deleted[0].verifiedMode, 'cross-engine');
    assert.equal(deleted[0].producedBy, 'claude');
  } finally { removeTemp(project); }
});

// 귀속 불가의 두 형태 중 "풀 밖 라벨". sentinel `unknown`은 아래 별도 테스트가 덮는다.
// (0.x의 `extractor.argv`/`extractor.default`도 귀속 불가였지만 스키마에서 사라졌다 —
// 이제 모든 argv가 엔진 라벨을 통해 오므로 남은 귀속 불가는 이 두 가지뿐이다.)
test('풀 밖 라벨이 만든 카드는 엔진 귀속이 불가하므로 mode unknown (교차 주장 금지)', () => {
  const tracker = trackerFile('outside-pool-prefer');
  const project = setupProject({
    jobOverrides: { engine: 'hermes' },   // 풀에 없는 라벨 → argv가 해석되지 않는다
    extractor: { timeout: 30, backends: { codex: mockEngine('codex', tracker, 'pass') } },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    assert.deepEqual(calls(tracker), ['codex'], '검수는 계속된다(폐기하면 영원히 미검수)');
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: verified$/m);
    assert.match(text, /^verifiedMode: "?unknown"?$/m, '생성 엔진과 다름을 증명할 수 없다');
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].verifiedMode, 'unknown');
    assert.equal(log[0].producedBy, 'hermes');
  } finally { removeTemp(project); }
});

test('증명 필드 위생: pass 스탬프는 verifiedBy/verifiedAt/verifiedMode를 항상 함께 쓴다', () => {
  const tracker = trackerFile('proof');
  const project = setupProject({
    extractor: { timeout: 30, backends: { codex: mockEngine('codex', tracker, 'pass') } },
  });
  try {
    runVerifyWorker(project);
    const fm = readFileSync(join(project, CARD_REL), 'utf8').split('---')[1];
    for (const key of ['verifiedBy', 'verifiedAt', 'verifiedMode']) {
      assert.match(fm, new RegExp(`^${key}: .+$`, 'm'), `${key} 결측 금지`);
    }
  } finally { removeTemp(project); }
});

test('기존 verified 카드는 자동 재검증되지 않는다 (655장 재검증 = 사용자 계정 청구)', () => {
  const tracker = trackerFile('no-reverify');
  const project = setupProject({
    cardStatus: 'verified',
    extractor: { timeout: 30, backends: { codex: mockEngine('codex', tracker, 'fail') } },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    assert.deepEqual(calls(tracker), [], '검수된 카드에는 host CLI를 호출하지 않는다');
    assert.equal(existsSync(join(project, CARD_REL)), true);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'))[0].reason, 'not_generated');
  } finally { removeTemp(project); }
});

test('crossEngine:require는 풀 밖 라벨(귀속 불가)로 만족되지 않는다', () => {
  const tracker = trackerFile('outside-pool-require');
  const project = setupProject({
    jobOverrides: { engine: 'hermes' },
    verify: { crossEngine: 'require' },
    extractor: { timeout: 30, backends: { codex: mockEngine('codex', tracker, 'pass') } },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 0);
    // "never self-verify" 약속은 생성 엔진을 특정할 수 없으면 지킬 수 없다 → fail-closed.
    assert.deepEqual(calls(tracker), [], '증명할 수 없으면 유료 호출도 하지 않는다');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'))[0].reason,
      'cross_engine_unavailable');
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'),
      /test-card\.md/, '거부는 폐기가 아니다 — 잡 보존');
  } finally { removeTemp(project); }
});

// verify.builtins가 생성 엔진을 제외해도 self 폴백은 사라지면 안 된다. plan 단위 단정은
// 아래 'verify.builtins를 좁혀도…' 테스트가 하고, 여기서는 worker 실행 전체를 본다:
// 선호 후보(codex)가 127로 빠지면 풀 밖인 생성 엔진(claude)이 실제로 검수를 끝낸다.
test('verify.builtins가 생성 엔진을 제외해도 최후 후보로 남아 검수가 완료된다(prefer)', () => {
  const tracker = trackerFile('builtins-exclude-producer');
  const project = setupProject({
    verify: { builtins: ['codex'] },
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'absent') },
    },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    assert.deepEqual(calls(tracker), ['codex', 'claude'], '풀 밖이어도 생성 엔진이 최후 후보');
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: verified$/m, 'missing_extractor로 영구 drop되지 않는다');
    assert.match(text, /^verifiedMode: "?self"?$/m);
    assert.equal(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), '');
  } finally { removeTemp(project); }
});

// ---------------------------------------------------------------------------
// 리뷰 반영: non-127 실패의 run 간 degrade (전역 cooldown → 후보 단위)
// ---------------------------------------------------------------------------

test('선호 엔진 non-127 실패 → 다음 run이 다음 후보로 degrade, run당 유료 호출 1회', () => {
  const tracker = trackerFile('degrade-runs');
  const project = setupProject({
    extractor: {
      timeout: 30,
      // codex는 인증 안 된 CLI처럼 exit 1(비127)로 죽는다 — lib.py가 CLI 비0을 그대로
      // 전파하는 경로이므로 실제로 흔한 상태다.
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'exit1') },
    },
  });
  try {
    // run1: 선호 후보 codex가 유료 호출 1회를 소진하고 실패 → 카드·큐 보존, codex 식힘
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 0);
    assert.deepEqual(calls(tracker), ['codex']);
    assert.deepEqual(Object.keys(engineCooldown(project)), ['codex']);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl')).length, 1,
      'transient도 로그 1줄 — 0.x는 0줄이라 영구 정지를 진단할 수 없었다');

    // run2: codex는 식힘 중이므로 건너뛰고 생성 엔진으로 degrade. 이 run의 유료 호출도 1회.
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    assert.deepEqual(calls(tracker), ['codex', 'claude'], 'run당 유료 호출 1회 유지');
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: verified$/m, '영구 정지하지 않는다');
    assert.match(text, /^verifiedMode: "?self"?$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'deferred');
    assert.equal(log[0].cooledKey, 'codex');
    assert.deepEqual(log[1].enginesCooling, ['codex']);
    assert.equal(log[1].result, 'verified');
  } finally { removeTemp(project); }
});

test('후보 전원 식힘 중 → 잡 보존 + engines_cooling 로그 (드롭 아님)', () => {
  const tracker = trackerFile('all-cooling');
  const project = setupProject({
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'exit1'), codex: mockEngine('codex', tracker, 'exit1') },
    },
  });
  try {
    runVerifyWorker(project);  // codex 실패 → 식힘
    runVerifyWorker(project);  // claude 실패 → 식힘
    const out = JSON.parse(runVerifyWorker(project));  // 전원 식힘
    assert.equal(out.processed, 0);
    assert.deepEqual(calls(tracker), ['codex', 'claude'], '식힘 중에는 유료 호출 0');
    assert.match(
      readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'),
      /test-card\.md/, '잡 보존 — 식힘이 풀리면 재시도');
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[log.length - 1].reason, 'engines_cooling');
    assert.deepEqual(log[log.length - 1].enginesCooling, ['claude', 'codex']);
    assert.equal(existsSync(join(project, CARD_REL)), true, '삭제되지 않는다');
  } finally { removeTemp(project); }
});

test('CLI 부재(127)는 로그 1줄을 남기고 후보를 식히지 않는다(과금 0, 설치 즉시 재시도)', () => {
  const tracker = trackerFile('absent-log');
  const project = setupProject({
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'absent'), codex: mockEngine('codex', tracker, 'absent') },
    },
  });
  try {
    runVerifyWorker(project);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'deferred');
    assert.equal(log[0].reason, 'extractor_unavailable');
    assert.deepEqual(log[0].enginesAttempted, ['codex', 'claude']);
    assert.deepEqual(engineCooldown(project), {}, '127은 식히지 않는다');
  } finally { removeTemp(project); }
});

test('귀속 불가 라벨(sentinel "unknown"): prefer는 cross-engine을 주장하지 않고 require는 fail-closed', () => {
  for (const [mode, expect] of [['prefer', 'unknown'], ['require', null]]) {
    const tracker = trackerFile(`unattributed-${mode}`);
    const project = setupProject({
      jobOverrides: { engine: 'unknown' },
      verify: { crossEngine: mode },
      extractor: {
        timeout: 30,
        backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'pass') },
      },
    });
    try {
      runVerifyWorker(project);
      if (expect === null) {
        assert.deepEqual(calls(tracker), [], 'require는 생성 엔진을 특정할 수 없으면 검수하지 않는다');
        assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
        assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'))[0].reason,
          'cross_engine_unavailable');
        assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'),
          /test-card\.md/, '잡 보존');
      } else {
        assert.match(readFileSync(join(project, CARD_REL), 'utf8'),
          new RegExp(`^verifiedMode: "?${expect}"?$`, 'm'));
      }
    } finally { removeTemp(project); }
  }
});

test('verify.builtins를 좁혀도 prefer에서 생성 엔진은 최후 후보로 남는다', () => {
  const tracker = trackerFile('builtins-narrow');
  const project = setupProject({
    // builtins-only(--enable-compile 기본형) + verify.builtins가 codex만 지정.
    verify: { builtins: ['codex'] },
    extractor: { timeout: 30, builtins: ['claude', 'codex'], backends: {} },
  });
  try {
    const plan = execFileSync('python3', ['-c', `
import json, sys; sys.path.insert(0, 'core')
import wiki_verify_worker as w
cfg = {"extractor": {"builtins": ["claude", "codex"], "backends": {}}}
attempts, mode, reason = w.plan_verify_attempts(cfg, {"builtins": ["codex"]}, "claude")
print(json.dumps([[a["engine"], a["mode"]] for a in attempts]))
`], { cwd: process.cwd(), encoding: 'utf8' });
    assert.deepEqual(JSON.parse(plan), [['codex', 'cross-engine'], ['claude', 'self']]);
  } finally { removeTemp(project); }
});

test('verify.builtins 오타는 영구 drop이 아니라 self 폴백으로 degrade한다', () => {
  const tracker = trackerFile('builtins-typo');
  const adapter = mockEngine('claude', tracker, 'pass');
  const project = setupProject({
    verify: { builtins: ['codexx'] },   // 오타 — 해석되는 argv가 없다
    extractor: { timeout: 30, backends: { claude: adapter } },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    assert.deepEqual(calls(tracker), ['claude']);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: verified$/m);
    assert.equal(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), '',
      'missing_extractor 영구 drop이 아니다');
  } finally { removeTemp(project); }
});

test('로그 키 의미 고정: attempt 이전 줄은 producedBy만, 이후 줄은 engine=검수 엔진', () => {
  const tracker = trackerFile('log-keys');
  const project = setupProject({
    cardStatus: 'verified',   // attempt 이전 skip(not_generated)
    extractor: { timeout: 30, backends: { codex: mockEngine('codex', tracker, 'pass') } },
  });
  try {
    runVerifyWorker(project);
    const row = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'))[0];
    assert.equal(row.reason, 'not_generated');
    assert.equal(row.producedBy, 'claude');
    assert.equal('engine' in row, false, '검수 엔진이 없는 줄에 engine 키를 쓰지 않는다');
  } finally { removeTemp(project); }
});

// ---------------------------------------------------------------------------
// 확인 라운드 마무리: cooldown 쓰기 실패 표면화 / invalid_* degrade / off 폴백 / mode 표기
// ---------------------------------------------------------------------------

test('cooldown 쓰기 실패는 로그에 표면화된다 (MAJOR 1 복구 메커니즘의 조용한 실패 금지)', () => {
  const tracker = trackerFile('cooldown-fail');
  const project = setupProject({
    verify: { timeout: 1 },
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'slow') },
    },
  });
  const compileDir = join(project, '.auto-context', 'compile');
  try {
    // cooldown 파일 위치를 디렉터리로 점거 → write_text_atomic이 False를 반환한다.
    mkdirSync(join(compileDir, 'verify-engine-cooldown.json'), { recursive: true });
    runVerifyWorker(project);
    const row = jsonl(join(compileDir, 'verify-log.jsonl'))[0];
    assert.equal(row.result, 'deferred');
    assert.equal(row.cooldownWriteFailed, true, '식힘 기록 실패 = 다음 run이 같은 후보 재호출');
    assert.equal(existsSync(join(project, CARD_REL)), true);
  } finally { removeTemp(project); }
});

test('invalid_verdict: 남은 후보가 있으면 degrade, 후보가 다 떨어지면 폐기(과금 루프 방지)', () => {
  const tracker = trackerFile('invalid-degrade');
  // exit 0 + 쓰레기 stdout — builtin adapter로는 불가능한, 커스텀 argv 설정 오류.
  const garbage = join(mkdtempSync(join(tmpdir(), 'garbage-')), 'g.py');
  writeFileSync(garbage, `#!/usr/bin/env python3
import sys
sys.stdin.read()
with open(${JSON.stringify(tracker)}, "a") as fh:
    fh.write("garbage\\n")
print("{}")
`);
  const project = setupProject({
    extractor: {
      timeout: 30,
      backends: { claude: ['python3', garbage], codex: ['python3', garbage].concat(['--codex']) },
    },
  });
  const queuePath = join(project, '.auto-context', 'compile', 'verify-queue.jsonl');
  try {
    // run1: codex(선호)가 쓰레기 출력 → 남은 후보(claude)가 있으므로 degrade + 잡 보존
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 0);
    let log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'invalid_verdict');
    assert.equal(log[0].result, 'deferred');
    assert.match(readFileSync(queuePath, 'utf8'), /test-card\.md/);
    // run2: 마지막 후보도 실패 → 종점(폐기). 보존하면 cooldown 만료마다 전 후보 재호출.
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[1].result, 'skipped');
    assert.equal(readFileSync(queuePath, 'utf8'), '');
    assert.equal(existsSync(join(project, CARD_REL)), true, '폐기해도 카드는 삭제되지 않는다');
    assert.equal(calls(tracker).length, 2, 'run당 유료 호출 1회');
  } finally { removeTemp(project); }
});

test('crossEngine:off + 귀속 불가 라벨 → 폐기 대신 풀 첫 후보로 폴백(mode unknown)', () => {
  const tracker = trackerFile('off-unattributed');
  const project = setupProject({
    jobOverrides: { engine: 'unknown' },
    verify: { crossEngine: 'off' },
    extractor: { timeout: 30, backends: { codex: mockEngine('codex', tracker, 'pass') } },
  });
  try {
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    assert.deepEqual(calls(tracker), ['codex']);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: verified$/m, '폐기하면 그 카드는 영원히 검수되지 않는다');
    assert.match(text, /^verifiedMode: "?unknown"?$/m, '거짓 교차검증 주장 금지');
  } finally { removeTemp(project); }
});

test('실패 행은 verifiedMode를 쓰지 않는다 (attemptedMode로 분리 — 노출 집계 오독 방지)', () => {
  const tracker = trackerFile('mode-keys');
  const project = setupProject({
    verify: { timeout: 1 },
    extractor: {
      timeout: 30,
      backends: { claude: mockEngine('claude', tracker, 'pass'), codex: mockEngine('codex', tracker, 'slow') },
    },
  });
  try {
    runVerifyWorker(project);            // run1: codex timeout → deferred 행
    runVerifyWorker(project);            // run2: claude로 degrade → verified 행
    const [failed, passed] = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(failed.result, 'deferred');
    assert.equal(failed.attemptedMode, 'cross-engine');
    assert.equal('verifiedMode' in failed, false, '달성하지 않은 mode를 verifiedMode로 쓰지 않는다');
    assert.equal(passed.verifiedMode, 'self');
    assert.equal(passed.attemptedMode, 'self');
  } finally { removeTemp(project); }
});

test('0.x 전역 verify-cooldown 파일은 고아로 남지 않고 정리된다', () => {
  const project = setupProject({ extractorArgv: ['/nonexistent/verify-cli-xyz'] });
  const stale = join(project, '.auto-context', 'compile', 'verify-cooldown');
  try {
    writeFileSync(stale, '99999999999\n');
    runVerifyWorker(project);
    assert.equal(existsSync(stale), false);
  } finally { removeTemp(project); }
});

test('만료값 상한 클램프: 오염된 만료값은 후보를 영구 배제하지 못한다', () => {
  const tracker = trackerFile('clamp');
  const project = setupProject({
    extractor: { timeout: 30, backends: { codex: mockEngine('codex', tracker, 'pass') } },
  });
  const cooldown = join(project, '.auto-context', 'compile', 'verify-engine-cooldown.json');
  try {
    writeFileSync(cooldown, JSON.stringify({ codex: 9e18 }));
    assert.equal(JSON.parse(runVerifyWorker(project)).processed, 1);
    assert.deepEqual(calls(tracker), ['codex'], '상한 초과 만료값은 식힘으로 보지 않는다');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: verified$/m);
  } finally { removeTemp(project); }
});
