import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync, spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

function repoTemp(prefix) {
  const base = join(homedir(), '.cache');
  mkdirSync(base, { recursive: true });
  return mkdtempSync(join(base, `qmd-test-${prefix}-`));
}

function writeSettings(work, compile = {}) {
  mkdirSync(join(work, '.auto-context'), { recursive: true });
  writeFileSync(join(work, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-wiki'],
    collectionPaths: { 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      enabled: true,
      mode: 'auto-wiki',
      autoWrite: true,
      defaultStatus: 'generated',
      candidatePath: '.auto-context/compile/candidates.jsonl',
      tombstonePath: '.auto-context/compile/tombstones.jsonl',
      manifestPath: '.auto-context/compile/generated-manifest.jsonl',
      ...compile,
    },
  }));
}

function runCompile(work, payload, env = {}) {
  return execFileSync('python3', ['core/wiki_compile.py', '--cwd', work], {
    encoding: 'utf8',
    input: JSON.stringify(payload),
    env: { ...process.env, ...env },
  });
}

function runCompileAsync(work, payload, env = {}) {
  // execFileSync would block this process's event loop, starving the in-process
  // mock HTTP server used by tests that need to observe the outgoing /query
  // payload -- use async spawn instead so the server can actually respond.
  return new Promise((resolve, reject) => {
    const child = spawn('python3', ['core/wiki_compile.py', '--cwd', work], {
      env: { ...process.env, ...env },
    });
    let stdout = '';
    let stderr = '';
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk) => { stdout += chunk; });
    child.stderr.on('data', (chunk) => { stderr += chunk; });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve(stdout);
      else reject(new Error(`wiki_compile.py exited ${code}: ${stderr}`));
    });
    child.stdin.end(JSON.stringify(payload));
  });
}

function readJsonl(path) {
  return readFileSync(path, 'utf8').trim().split('\n').filter(Boolean).map((line) => JSON.parse(line));
}

test('wiki_compile: lint-clean candidate writes generated markdown, audit files, and dirty queue', () => {
  const work = repoTemp('wiki-compile-write');
  const dirtyQueue = join(work, 'dirty-queue');
  try {
    writeSettings(work);
    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Config Layout Decision',
      summary: 'Canonical config lives in .auto-context/settings.json; legacy root config is migration-only.',
      suggestedType: 'decision',
      confidence: 'high',
      sources: [{ kind: 'file', path: 'docs/spec.md' }],
      targetPath: '.auto-context/wiki/decisions/config-layout.md',
    }, { QMD_DIRTY_QUEUE: dirtyQueue });

    assert.match(out, /created/);
    const page = readFileSync(join(work, '.auto-context', 'wiki', 'decisions', 'config-layout.md'), 'utf8');
    assert.match(page, /status: generated/);
    assert.match(page, /reviewed: false/);
    assert.match(page, /Auto-generated by qmd-auto-context/);
    assert.match(page, /Canonical config lives/);
    assert.match(readFileSync(join(work, '.auto-context', 'compile', 'candidates.jsonl'), 'utf8'), /Config Layout Decision/);
    assert.match(readFileSync(join(work, '.auto-context', 'compile', 'generated-manifest.jsonl'), 'utf8'), /config-layout/);
    assert.match(readFileSync(join(work, '.auto-context', 'wiki', 'index.md'), 'utf8'), /decisions\/config-layout.md/);
    assert.match(readFileSync(join(work, '.auto-context', 'wiki', 'log.md'), 'utf8'), /created/);
    assert.match(readFileSync(dirtyQueue, 'utf8'), /proj-wiki\t.*\.auto-context\/wiki/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: writes canonical identity metadata into generated frontmatter', () => {
  const work = repoTemp('wiki-compile-identity-frontmatter');
  try {
    writeSettings(work);
    runCompile(work, {
      trigger: 'manual',
      title: 'Signal Perception Rule',
      canonicalKey: 'signal-perception-rule',
      aliases: ['Signal rule', 'Perception rule'],
      summary: 'Signal perception should be stored as one durable concept, not split by display title changes.',
      suggestedType: 'concept',
      confidence: 'high',
    });

    const page = readFileSync(join(work, '.auto-context', 'wiki', 'concepts', 'signal-perception-rule.md'), 'utf8');
    assert.match(page, /canonicalKey: "signal-perception-rule"/);
    assert.match(page, /aliases:\n  - "Signal rule"\n  - "Perception rule"/);
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows[0].canonicalKey, 'signal-perception-rule');
    assert.deepEqual(rows[0].aliases, ['Signal rule', 'Perception rule']);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: reuses existing page by canonicalKey when title changes and targetPath is omitted', () => {
  const work = repoTemp('wiki-compile-reuse-canonical');
  try {
    writeSettings(work);
    runCompile(work, {
      trigger: 'manual',
      title: 'Signal Perception Rule',
      canonicalKey: 'signal-perception-rule',
      aliases: ['Signal perception'],
      summary: 'Initial durable rule.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/signal-rules.md',
    });
    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Medicine Signal Detection',
      canonicalKey: 'signal-perception-rule',
      aliases: ['Medicine signal detection'],
      summary: 'Updated durable rule should land in the existing page.',
      suggestedType: 'concept',
      confidence: 'high',
    });

    assert.match(out, /updated/);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'medicine-signal-detection.md')), false);
    const page = readFileSync(join(work, '.auto-context', 'wiki', 'concepts', 'signal-rules.md'), 'utf8');
    assert.match(page, /Updated durable rule should land in the existing page/);
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows.at(-1).targetPath, '.auto-context/wiki/concepts/signal-rules.md');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: reuses existing page by alias or title before creating a title slug', () => {
  const work = repoTemp('wiki-compile-reuse-alias-title');
  try {
    writeSettings(work);
    runCompile(work, {
      trigger: 'manual',
      title: 'Canonical Signal Concept',
      canonicalKey: 'canonical-signal-concept',
      aliases: ['Signal Detection'],
      summary: 'Initial durable concept.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/canonical-signal.md',
    });
    runCompile(work, {
      trigger: 'manual',
      title: 'Signal Detection',
      summary: 'Alias-matched update should reuse canonical-signal.md.',
      suggestedType: 'concept',
      confidence: 'high',
    });

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'signal-detection.md')), false);
    const page = readFileSync(join(work, '.auto-context', 'wiki', 'concepts', 'canonical-signal.md'), 'utf8');
    assert.match(page, /Alias-matched update should reuse canonical-signal\.md/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: explicit targetPath wins over identity lookup', () => {
  const work = repoTemp('wiki-compile-explicit-target-wins');
  try {
    writeSettings(work);
    runCompile(work, {
      trigger: 'manual',
      title: 'Signal Perception Rule',
      canonicalKey: 'signal-perception-rule',
      summary: 'Existing canonical page.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/existing-signal.md',
    });
    runCompile(work, {
      trigger: 'manual',
      title: 'Signal Perception Rule',
      canonicalKey: 'signal-perception-rule',
      summary: 'Explicit target should create a separate page for this requested location.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/explicit-signal.md',
    });

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'explicit-signal.md')), true);
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows.at(-1).targetPath, '.auto-context/wiki/concepts/explicit-signal.md');
    assert.equal(rows.at(-1).targetResolution, 'explicit');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: ambiguous identity matches record merge-needed without creating slug fallback', () => {
  const work = repoTemp('wiki-compile-ambiguous-identity');
  try {
    writeSettings(work);
    const targetDir = join(work, '.auto-context', 'wiki', 'concepts');
    mkdirSync(targetDir, { recursive: true });
    for (const name of ['signal-a.md', 'signal-b.md']) {
      writeFileSync(join(targetDir, name), [
        '---',
        'title: "Signal Detection"',
        'canonicalKey: "signal-perception-rule"',
        'type: concept',
        'status: generated',
        'createdBy: qmd-auto-context',
        'reviewed: false',
        '---',
        '',
        '<!-- qmd:auto:start id="main" sourceHash="aaaaaaaaaaaaaaaa" -->',
        '## Summary',
        'Existing generated summary.',
        '<!-- qmd:auto:end -->',
        '',
      ].join('\n'));
    }

    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Different Signal Title',
      canonicalKey: 'signal-perception-rule',
      summary: 'Ambiguous update should wait for manual selection.',
      suggestedType: 'concept',
      confidence: 'high',
    });

    assert.match(out, /merge-needed/);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'different-signal-title.md')), false);
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows.at(-1).action, 'merge-needed');
    assert.equal(rows.at(-1).lint.findings[0], 'ambiguous_canonicalKey');
    assert.equal(rows.at(-1).targetMatches.length, 2);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: protected existing identity match records merge-needed without overwriting', () => {
  const work = repoTemp('wiki-compile-merge-needed');
  try {
    writeSettings(work);
    const targetDir = join(work, '.auto-context', 'wiki', 'concepts');
    mkdirSync(targetDir, { recursive: true });
    const target = join(targetDir, 'reviewed-signal.md');
    writeFileSync(target, [
      '---',
      'title: "Reviewed Signal Rule"',
      'canonicalKey: "signal-perception-rule"',
      'aliases:',
      '  - "Signal Detection"',
      'type: concept',
      'status: reviewed',
      'createdBy: qmd-auto-context',
      'reviewed: true',
      '---',
      '',
      'Human reviewed text must stay untouched.',
      '',
      '<!-- qmd:auto:start id="main" sourceHash="aaaaaaaaaaaaaaaa" -->',
      '## Summary',
      'Old generated block must not be replaced.',
      '<!-- qmd:auto:end -->',
      '',
    ].join('\n'));

    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Signal Detection',
      canonicalKey: 'signal-perception-rule',
      summary: 'New summary should be held for manual merge.',
      suggestedType: 'concept',
      confidence: 'high',
    });

    assert.match(out, /merge-needed/);
    const page = readFileSync(target, 'utf8');
    assert.match(page, /Old generated block must not be replaced/);
    assert.doesNotMatch(page, /New summary should be held/);
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows.at(-1).action, 'merge-needed');
    assert.equal(rows.at(-1).targetPath, '.auto-context/wiki/concepts/reviewed-signal.md');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: superseded existing page is protected — records merge-needed instead of rewriting', () => {
  const work = repoTemp('wiki-compile-superseded-protected');
  try {
    writeSettings(work);
    mkdirSync(join(work, '.auto-context', 'wiki', 'decisions'), { recursive: true });
    writeFileSync(
      join(work, '.auto-context', 'wiki', 'decisions', 'old-principle.md'),
      [
        '---',
        'title: "Old principle"',
        'canonicalKey: "old-principle-rule"',
        'type: decision',
        'status: superseded',
        'createdBy: qmd-auto-context',
        '---',
        '',
        '<!-- qmd:auto:start id="main" sourceHash="abc123" -->',
        '## Summary',
        'Old text.',
        '<!-- qmd:auto:end -->',
        '',
      ].join('\n'),
    );

    const out = JSON.parse(runCompile(work, {
      title: 'Old principle, reworded',
      summary: 'A later candidate that matches the same canonicalKey.',
      suggestedType: 'decision',
      confidence: 'high',
      canonicalKey: 'old-principle-rule',
    }));

    assert.equal(out.action, 'merge-needed');
    assert.deepEqual(out.findings, ['protected_status']);

    const stillOld = readFileSync(join(work, '.auto-context', 'wiki', 'decisions', 'old-principle.md'), 'utf8');
    assert.match(stillOld, /Old text\./);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: manual status page records merge-needed without overwriting auto block', () => {
  const work = repoTemp('wiki-compile-manual-status');
  try {
    writeSettings(work);
    const targetDir = join(work, '.auto-context', 'wiki', 'concepts');
    mkdirSync(targetDir, { recursive: true });
    const target = join(targetDir, 'manual-signal.md');
    writeFileSync(target, [
      '---',
      'title: "Manual Signal Rule"',
      'canonicalKey: "signal-perception-rule"',
      'type: concept',
      'status: manual',
      'createdBy: qmd-auto-context',
      'reviewed: false',
      '---',
      '',
      '<!-- qmd:auto:start id="main" sourceHash="aaaaaaaaaaaaaaaa" -->',
      '## Summary',
      'Manual-status generated block must not be replaced.',
      '<!-- qmd:auto:end -->',
      '',
    ].join('\n'));

    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Manual Signal Rule',
      canonicalKey: 'signal-perception-rule',
      summary: 'New summary should not overwrite manual status.',
      suggestedType: 'concept',
      confidence: 'high',
    });

    assert.match(out, /merge-needed/);
    const page = readFileSync(target, 'utf8');
    assert.match(page, /Manual-status generated block must not be replaced/);
    assert.doesNotMatch(page, /New summary should not overwrite/);
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows.at(-1).lint.findings.includes('protected_status'), true);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: malformed existing frontmatter is fail-safe merge-needed', () => {
  const work = repoTemp('wiki-compile-malformed-frontmatter');
  try {
    writeSettings(work);
    const targetDir = join(work, '.auto-context', 'wiki', 'concepts');
    mkdirSync(targetDir, { recursive: true });
    const target = join(targetDir, 'malformed.md');
    writeFileSync(target, [
      '---',
      'title: "Malformed Page"',
      'canonicalKey: "signal-perception-rule"',
      '  bad-indent',
      '---',
      '',
      '<!-- qmd:auto:start id="main" sourceHash="aaaaaaaaaaaaaaaa" -->',
      '## Summary',
      'Original text must remain.',
      '<!-- qmd:auto:end -->',
      '',
    ].join('\n'));

    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Malformed Page',
      summary: 'Explicit target must not overwrite malformed frontmatter.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/malformed.md',
    });

    assert.match(out, /merge-needed/);
    assert.match(readFileSync(target, 'utf8'), /Original text must remain/);
    assert.doesNotMatch(readFileSync(target, 'utf8'), /Explicit target must not overwrite/);
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows.at(-1).lint.findings[0], 'frontmatter_unparseable');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: tombstone suppresses deleted generated page by canonicalKey', () => {
  const work = repoTemp('wiki-compile-tombstone-canonical');
  try {
    writeSettings(work);
    runCompile(work, {
      trigger: 'manual',
      title: 'Signal Rule',
      canonicalKey: 'signal-perception-rule',
      summary: 'Initial summary that creates the generated page.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/signal-rule.md',
    });
    rmSync(join(work, '.auto-context', 'wiki', 'concepts', 'signal-rule.md'));
    const tombstoned = runCompile(work, {
      trigger: 'manual',
      title: 'Renamed Signal Rule',
      canonicalKey: 'signal-perception-rule',
      summary: 'Different summary must not recreate a deleted generated identity.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/signal-rule.md',
    });
    const suppressed = runCompile(work, {
      trigger: 'manual',
      title: 'Another Signal Rule',
      canonicalKey: 'signal-perception-rule',
      summary: 'Another summary must still respect the deleted generated identity.',
      suggestedType: 'concept',
      confidence: 'high',
    });

    assert.match(tombstoned, /tombstoned/);
    assert.match(suppressed, /suppressed/);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'renamed-signal-rule.md')), false);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'another-signal-rule.md')), false);
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows.at(-1).action, 'suppressed');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: rejects transcript-like and secret-like candidates without writing wiki page', () => {
  const work = repoTemp('wiki-compile-lint');
  try {
    writeSettings(work);
    runCompile(work, {
      trigger: 'manual',
      title: 'Bad Transcript',
      summary: 'User: please save this\nAssistant: ok\nsk-1234567890abcdef1234567890abcdef',
      suggestedType: 'decision',
      confidence: 'high',
      targetPath: '.auto-context/wiki/decisions/bad.md',
    });

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'decisions', 'bad.md')), false);
    const candidate = readFileSync(join(work, '.auto-context', 'compile', 'candidates.jsonl'), 'utf8');
    assert.match(candidate, /rejected/);
    assert.doesNotMatch(candidate, /sk-1234567890abcdef1234567890abcdef/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: disabled or candidates mode records candidate only', () => {
  const work = repoTemp('wiki-compile-candidates');
  try {
    writeSettings(work, { mode: 'candidates' });
    runCompile(work, {
      trigger: 'manual',
      title: 'Candidate Only',
      summary: 'This should stay in the queue only.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/candidate-only.md',
    });

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'candidate-only.md')), false);
    assert.match(readFileSync(join(work, '.auto-context', 'compile', 'candidates.jsonl'), 'utf8'), /candidate-only/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});


test('wiki_compile: mode off is a no-op and writes no candidate audit', () => {
  const work = repoTemp('wiki-compile-mode-off');
  try {
    writeSettings(work, { mode: 'off' });
    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Mode Off Candidate',
      summary: 'Mode off should not write candidate audit records.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/mode-off.md',
    });

    assert.equal(out, '');
    assert.equal(existsSync(join(work, '.auto-context', 'compile', 'candidates.jsonl')), false);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'mode-off.md')), false);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: missing generated page creates tombstone and suppresses automatic recreation', () => {
  const work = repoTemp('wiki-compile-tombstone');
  try {
    writeSettings(work);
    const payload = {
      trigger: 'manual',
      title: 'Deleted Page',
      summary: 'A generated page that the user deletes should not be recreated automatically.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/deleted-page.md',
    };
    runCompile(work, payload);
    rmSync(join(work, '.auto-context', 'wiki', 'concepts', 'deleted-page.md'));
    runCompile(work, payload);

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'deleted-page.md')), false);
    assert.match(readFileSync(join(work, '.auto-context', 'compile', 'tombstones.jsonl'), 'utf8'), /deleted-page/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});


test('wiki_compile: compile audit paths are confined to project .auto-context/compile', () => {
  const work = repoTemp('wiki-compile-safe-audit');
  try {
    const outsideName = `../outside-candidates-${work.split('/').pop()}.jsonl`;
    writeSettings(work, { candidatePath: outsideName });
    const result = spawnSync('python3', ['core/wiki_compile.py', '--cwd', work], {
      encoding: 'utf8',
      input: JSON.stringify({
      trigger: 'manual',
      title: 'Unsafe Audit Path',
      summary: 'Unsafe audit path must be rejected before any outside write.',
      suggestedType: 'decision',
      confidence: 'high',
      targetPath: '.auto-context/wiki/decisions/unsafe-audit.md',
      }),
    });
    assert.equal(result.status, 1);
    assert.match(result.stdout, /unsafe_managed_path|unsafe_compile_path/);
    assert.equal(existsSync(join(work, '..', outsideName.slice(3))), false);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'decisions', 'unsafe-audit.md')), false);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('patch_frontmatter_fields: rewrites only named scalar keys, leaves body and other fields untouched', () => {
  const work = repoTemp('wiki-compile-patch-frontmatter');
  try {
    const page = join(work, 'page.md');
    const originalFixture = [
      '---',
      'title: "Some Decision"',
      'canonicalKey: "some-decision"',
      'aliases:',
      '  - "Alt Name"',
      'status: generated',
      'createdBy: qmd-auto-context',
      '---',
      '',
      '<!-- qmd:auto:start id="main" sourceHash="deadbeef" -->',
      '## Summary',
      'Body text that must survive untouched.',
      '<!-- qmd:auto:end -->',
      '',
    ].join('\n');
    writeFileSync(page, originalFixture);

    const script = `
import sys
sys.path.insert(0, 'core')
from pathlib import Path
import wiki_compile as w
ok = w.patch_frontmatter_fields(Path(${JSON.stringify(page)}), {"status": "superseded", "supersededBy": ".auto-context/wiki/decisions/new.md"})
print(ok)
`;
    const result = execFileSync('python3', ['-c', script], { encoding: 'utf8' }).trim();
    assert.equal(result, 'True');

    const text = readFileSync(page, 'utf8');

    // Full-content equality: construct the expected file with only status and supersededBy changed/added
    const expectedFullText = [
      '---',
      'title: "Some Decision"',
      'canonicalKey: "some-decision"',
      'aliases:',
      '  - "Alt Name"',
      'status: superseded',
      'createdBy: qmd-auto-context',
      'supersededBy: ".auto-context/wiki/decisions/new.md"',
      '---',
      '',
      '<!-- qmd:auto:start id="main" sourceHash="deadbeef" -->',
      '## Summary',
      'Body text that must survive untouched.',
      '<!-- qmd:auto:end -->',
      '',
    ].join('\n');
    assert.equal(text, expectedFullText);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('patch_frontmatter_fields: quotes unknown status values', () => {
  const work = repoTemp('wiki-compile-patch-frontmatter-unknown-status');
  try {
    const page = join(work, 'page.md');
    writeFileSync(page, [
      '---',
      'title: "Some Decision"',
      'status: generated',
      '---',
      '',
      'Body text.',
      '',
    ].join('\n'));
    const script = `
import sys
sys.path.insert(0, 'core')
from pathlib import Path
import wiki_compile as w
print(w.patch_frontmatter_fields(Path(${JSON.stringify(page)}), {"status": "needs review"}))
`;
    const result = execFileSync('python3', ['-c', script], { encoding: 'utf8' }).trim();
    assert.equal(result, 'True');
    assert.match(readFileSync(page, 'utf8'), /^status: "needs review"$/m);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('patch_frontmatter_fields: returns False for a page with no parseable frontmatter', () => {
  const work = repoTemp('wiki-compile-patch-frontmatter-noop');
  try {
    const page = join(work, 'page.md');
    writeFileSync(page, 'no frontmatter here\n');
    const script = `
import sys
sys.path.insert(0, 'core')
from pathlib import Path
import wiki_compile as w
print(w.patch_frontmatter_fields(Path(${JSON.stringify(page)}), {"status": "superseded"}))
`;
    const result = execFileSync('python3', ['-c', script], { encoding: 'utf8' }).trim();
    assert.equal(result, 'False');
    assert.equal(readFileSync(page, 'utf8'), 'no frontmatter here\n');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate queues merge-needed when no identity match but daemon reports a high-similarity hit', () => {
  const work = repoTemp('wiki-compile-semantic-hit');
  try {
    writeSettings(work);
    mkdirSync(join(work, '.auto-context', 'wiki', 'entities'), { recursive: true });
    writeFileSync(
      join(work, '.auto-context', 'wiki', 'entities', 'cctv-request.md'),
      [
        '---',
        'title: "CCTV request"',
        'canonicalKey: "cctv-request"',
        'type: entity',
        'status: generated',
        'createdBy: qmd-auto-context',
        '---',
        '',
        '<!-- qmd:auto:start id="main" sourceHash="abc" -->',
        '## Summary',
        'Someone requested CCTV footage from the building office.',
        '<!-- qmd:auto:end -->',
        '',
      ].join('\n'),
    );

    const fixture = join(work, 'daemon-fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [
        { file: 'proj-wiki/entities/cctv-request.md', score: 0.9, title: 'CCTV request' },
      ],
    }));

    const out = JSON.parse(runCompile(work, {
      title: 'Second unknown call about luggage',
      summary: 'An unrelated-looking phone call about luggage — possibly the same actor as the CCTV request.',
      suggestedType: 'entity',
      confidence: 'medium',
    }, { QMD_QUERY_FIXTURE: fixture }));

    assert.equal(out.action, 'queued_for_review');
    assert.equal(out.matchedPath, '.auto-context/wiki/entities/cctv-request.md');
    assert.equal(out.score, 0.9);

    const mergeNeeded = readJsonl(join(work, '.auto-context', 'compile', 'merge-needed.jsonl'));
    assert.equal(mergeNeeded.length, 1);
    assert.equal(mergeNeeded[0].matchedPath, '.auto-context/wiki/entities/cctv-request.md');
    assert.equal(mergeNeeded[0].suggestedAction, 'merge');
    assert.equal(mergeNeeded[0].candidate.title, 'Second unknown call about luggage');

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'entities', 'second-unknown-call-about-luggage.md')), false);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate is skipped when identity already matched (no daemon call needed)', () => {
  const work = repoTemp('wiki-compile-semantic-identity-bypass');
  try {
    writeSettings(work);
    mkdirSync(join(work, '.auto-context', 'wiki', 'entities'), { recursive: true });
    writeFileSync(
      join(work, '.auto-context', 'wiki', 'entities', 'known.md'),
      [
        '---',
        'title: "Known entity"',
        'canonicalKey: "known-entity"',
        'type: entity',
        'status: generated',
        'createdBy: qmd-auto-context',
        '---',
        '',
        '<!-- qmd:auto:start id="main" sourceHash="abc" -->',
        '## Summary',
        'Old summary.',
        '<!-- qmd:auto:end -->',
        '',
      ].join('\n'),
    );

    // No fixture set: if the gate were reached it would try (and fail) to reach a real
    // daemon at localhost:8483 and fail-open. Identity match must short-circuit before that.
    const out = JSON.parse(runCompile(work, {
      title: 'Known entity',
      summary: 'Updated summary via identity match.',
      suggestedType: 'entity',
      confidence: 'high',
      canonicalKey: 'known-entity',
    }));

    assert.equal(out.action, 'updated');
    assert.equal(existsSync(join(work, '.auto-context', 'compile', 'merge-needed.jsonl')), false);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate below threshold writes a new page as before', () => {
  const work = repoTemp('wiki-compile-semantic-below-threshold');
  try {
    writeSettings(work);
    mkdirSync(join(work, '.auto-context', 'wiki', 'entities'), { recursive: true });
    writeFileSync(
      join(work, '.auto-context', 'wiki', 'entities', 'unrelated.md'),
      [
        '---',
        'title: "Unrelated entity"',
        'canonicalKey: "unrelated-entity"',
        'type: entity',
        'status: generated',
        'createdBy: qmd-auto-context',
        '---',
        '',
        '<!-- qmd:auto:start id="main" sourceHash="abc" -->',
        '## Summary',
        'Something else entirely.',
        '<!-- qmd:auto:end -->',
        '',
      ].join('\n'),
    );

    const fixture = join(work, 'daemon-fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [
        { file: 'proj-wiki/entities/unrelated.md', score: 0.2, title: 'Unrelated entity' },
      ],
    }));

    const out = JSON.parse(runCompile(work, {
      title: 'Brand new entity',
      summary: 'A genuinely new fact.',
      suggestedType: 'entity',
      confidence: 'high',
    }, { QMD_QUERY_FIXTURE: fixture }));

    assert.equal(out.action, 'created');
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'entities', 'brand-new-entity.md')), true);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate fails open when QMD_QUERY_FIXTURE is malformed', () => {
  const work = repoTemp('wiki-compile-semantic-fixture-error');
  try {
    writeSettings(work);
    const fixture = join(work, 'bad-fixture.json');
    writeFileSync(fixture, 'not json');

    const out = JSON.parse(runCompile(work, {
      title: 'New entity while fixture is broken',
      summary: 'Should still be created — fail-open on any daemon/fixture problem.',
      suggestedType: 'entity',
      confidence: 'high',
    }, { QMD_QUERY_FIXTURE: fixture }));

    assert.equal(out.action, 'created');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate fails open when QMD_QUERY_FIXTURE returns valid JSON that is not a dict', () => {
  const work = repoTemp('wiki-compile-semantic-fixture-wrong-shape');
  try {
    writeSettings(work);
    const fixture = join(work, 'array-fixture.json');
    writeFileSync(fixture, JSON.stringify([1, 2, 3]));

    const out = JSON.parse(runCompile(work, {
      title: 'New entity with array-shaped fixture',
      summary: 'Should still be created — fail-open when JSON is valid but wrong shape.',
      suggestedType: 'entity',
      confidence: 'high',
    }, { QMD_QUERY_FIXTURE: fixture }));

    assert.equal(out.action, 'created');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate queries with rerank=true (find_wiki_semantic_match only ever runs off the async compile worker or the manual wiki-compile skill, never a synchronous per-edit path)', async () => {
  const work = repoTemp('wiki-compile-semantic-rerank-true');
  const requests = [];
  const server = createServer((req, res) => {
    if (req.method === 'POST' && req.url === '/query') {
      let body = '';
      req.setEncoding('utf8');
      req.on('data', (chunk) => { body += chunk; });
      req.on('end', () => {
        requests.push(JSON.parse(body));
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ results: [] }));
      });
      return;
    }
    res.writeHead(404);
    res.end();
  });
  try {
    writeSettings(work);
    await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
    const { port } = server.address();

    await runCompileAsync(work, {
      title: 'Brand new entity with no identity match',
      summary: 'Should trigger the semantic gate to query the live daemon.',
      suggestedType: 'entity',
      confidence: 'high',
    }, { QMD_DAEMON_URL: `http://127.0.0.1:${port}` });

    assert.equal(requests.length, 1, 'expected exactly one /query call from the semantic gate');
    assert.equal(requests[0].rerank, true, 'semantic gate must use rerank=true for a real, threshold-comparable score');
  } finally {
    await new Promise((resolve) => server.close(resolve));
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate fails open when the daemon result score is non-numeric (string)', () => {
  const work = repoTemp('wiki-compile-semantic-score-string');
  try {
    writeSettings(work);
    const fixture = join(work, 'string-score-fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [
        { file: 'proj-wiki/entities/whatever.md', score: 'bad', title: 'Whatever' },
      ],
    }));

    const out = JSON.parse(runCompile(work, {
      title: 'New entity with a string score result',
      summary: 'Should still be created — a non-numeric score must not crash the gate.',
      suggestedType: 'entity',
      confidence: 'high',
    }, { QMD_QUERY_FIXTURE: fixture }));

    assert.equal(out.action, 'created');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate fails open when the daemon result score is null', () => {
  const work = repoTemp('wiki-compile-semantic-score-null');
  try {
    writeSettings(work);
    const fixture = join(work, 'null-score-fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [
        { file: 'proj-wiki/entities/whatever.md', score: null, title: 'Whatever' },
      ],
    }));

    const out = JSON.parse(runCompile(work, {
      title: 'New entity with a null score result',
      summary: 'Should still be created — a null score must not crash the gate.',
      suggestedType: 'entity',
      confidence: 'high',
    }, { QMD_QUERY_FIXTURE: fixture }));

    assert.equal(out.action, 'created');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: semantic gate resolves a daemon result path via the project-root-relative fallback when the primary (wiki-root-relative) interpretation misses (Finding 1 hardening)', () => {
  const work = repoTemp('wiki-compile-semantic-fallback-path');
  try {
    writeSettings(work);
    mkdirSync(join(work, '.auto-context', 'wiki', 'entities'), { recursive: true });
    writeFileSync(
      join(work, '.auto-context', 'wiki', 'entities', 'cctv-request.md'),
      [
        '---',
        'title: "CCTV request"',
        'canonicalKey: "cctv-request"',
        'type: entity',
        'status: generated',
        'createdBy: qmd-auto-context',
        '---',
        '',
        '<!-- qmd:auto:start id="main" sourceHash="abc" -->',
        '## Summary',
        'Someone requested CCTV footage from the building office.',
        '<!-- qmd:auto:end -->',
        '',
      ].join('\n'),
    );

    const fixture = join(work, 'daemon-fixture.json');
    // "rel" here (the part after qmd://proj-wiki/) is the project-root-relative
    // path, INCLUDING the .auto-context/wiki/ prefix, not the wiki-root-relative
    // path. wiki_root/rel would be wiki/.auto-context/wiki/entities/... (misses).
    // root/rel is wiki/entities/... nested under wiki_root again by coincidence
    // of this fixture shape and lands inside wiki_root, so the fallback catches it.
    writeFileSync(fixture, JSON.stringify({
      results: [
        { file: 'qmd://proj-wiki/.auto-context/wiki/entities/cctv-request.md', score: 0.9, title: 'CCTV request' },
      ],
    }));

    const out = JSON.parse(runCompile(work, {
      title: 'Second unknown call about luggage',
      summary: 'An unrelated-looking phone call about luggage — possibly the same actor as the CCTV request.',
      suggestedType: 'entity',
      confidence: 'medium',
    }, { QMD_QUERY_FIXTURE: fixture }));

    assert.equal(out.action, 'queued_for_review');
    assert.equal(out.matchedPath, '.auto-context/wiki/entities/cctv-request.md');
    assert.equal(out.score, 0.9);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

// --- auto-verify enqueue (wiki_compile write 성공 → verify-queue) ---

test('wiki_compile: generated 카드 write 성공 시 verify-queue에 잡 enqueue (engine/sourceHash 포함)', () => {
  const work = repoTemp('verify-enq');
  writeSettings(work, { semanticDedup: { enabled: false } });
  try {
    const out = JSON.parse(runCompile(work, {
      title: 'Verify Enqueue Decision',
      summary: 'Durable decision: verify queue records freshly written generated cards.',
      suggestedType: 'decision',
      confidence: 'high',
      trigger: 'manual',
      engine: 'claude',
      sources: [{ kind: 'file', path: 'docs/source.md', collection: 'proj-docs' }],
      targetPath: '.auto-context/wiki/decisions/verify-enqueue-decision.md',
    }));
    assert.equal(out.action, 'created');
    const queue = readFileSync(join(work, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8')
      .trim().split('\n').map((l) => JSON.parse(l));
    assert.equal(queue.length, 1);
    assert.equal(queue[0].targetPath, '.auto-context/wiki/decisions/verify-enqueue-decision.md');
    assert.equal(queue[0].engine, 'claude');
    assert.ok(queue[0].sourceHash, 'sourceHash 포함');
    assert.equal(queue[0].sources[0].path, 'docs/source.md');
  } finally { rmSync(work, { recursive: true, force: true }); }
});

test('wiki_compile: verify.enabled=false면 enqueue 안 함', () => {
  const work = repoTemp('verify-off');
  writeSettings(work, { semanticDedup: { enabled: false }, verify: { enabled: false } });
  try {
    const out = JSON.parse(runCompile(work, {
      title: 'No Verify Decision',
      summary: 'Durable decision: verify disabled projects skip the verify queue.',
      suggestedType: 'decision',
      confidence: 'high',
      trigger: 'manual',
      targetPath: '.auto-context/wiki/decisions/no-verify-decision.md',
    }));
    assert.equal(out.action, 'created');
    assert.equal(existsSync(join(work, '.auto-context', 'compile', 'verify-queue.jsonl')), false);
  } finally { rmSync(work, { recursive: true, force: true }); }
});

test('wiki_compile: verified 카드가 auto-update되면 status가 generated로 리셋 + verify 필드 제거 + 재enqueue', () => {
  const work = repoTemp('verify-reset');
  writeSettings(work, { semanticDedup: { enabled: false } });
  const payload = {
    title: 'Reset Decision',
    summary: 'Durable decision: updated cards drop stale verification.',
    suggestedType: 'decision',
    confidence: 'high',
    trigger: 'manual',
    engine: 'claude',
    targetPath: '.auto-context/wiki/decisions/reset-decision.md',
  };
  try {
    assert.equal(JSON.parse(runCompile(work, payload)).action, 'created');
    const page = join(work, '.auto-context', 'wiki', 'decisions', 'reset-decision.md');
    // verify 승격 시뮬레이션
    execFileSync('python3', ['-c', `
import sys; sys.path.insert(0, 'core')
from pathlib import Path
import wiki_compile as wc
wc.patch_frontmatter_fields(Path(${JSON.stringify(page)}), {"status": "verified", "verifiedBy": "claude", "verifiedAt": "2026-07-04T00:00:00Z"})
`], { encoding: 'utf8' });
    assert.match(readFileSync(page, 'utf8'), /^status: verified$/m);
    // 같은 identity로 재컴파일(내용 갱신) → updated 경로
    const updated = JSON.parse(runCompile(work, {
      ...payload,
      summary: 'Durable decision: updated cards drop stale verification. Now with new wording.',
    }));
    assert.equal(updated.action, 'updated');
    const text = readFileSync(page, 'utf8');
    assert.match(text, /^status: generated$/m, '갱신된 카드는 재검증 대상으로 리셋');
    assert.match(text, /^verifiedBy: ""?$/m, 'stale verifiedBy 제거');
    const queue = readFileSync(join(work, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8')
      .trim().split('\n').map((l) => JSON.parse(l));
    assert.equal(queue.length, 2, 'created + updated 각각 enqueue');
  } finally { rmSync(work, { recursive: true, force: true }); }
});

test('wiki_compile: normalizes wiki-root-relative targetPath under .auto-context/wiki', () => {
  const work = repoTemp('wiki-compile-wikirel-target');
  try {
    writeSettings(work);
    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Relative Target Rule',
      summary: 'Extractor emitted a wiki-root-relative targetPath; compile should normalize it under the wiki root.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: 'concepts/relative-target-rule.md',
    });

    assert.match(out, /created/);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'relative-target-rule.md')), true);
    assert.equal(existsSync(join(work, 'concepts')), false, 'must not write outside the wiki root');
    const rows = readJsonl(join(work, '.auto-context', 'compile', 'candidates.jsonl'));
    assert.equal(rows.at(-1).targetPath, '.auto-context/wiki/concepts/relative-target-rule.md');
    assert.equal(rows.at(-1).targetResolution, 'explicit');
    assert.deepEqual(rows.at(-1).lint.findings, []);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: wiki-relative targetPath with type mismatch falls back to identity resolution', () => {
  const work = repoTemp('wiki-compile-wikirel-mismatch');
  try {
    writeSettings(work);
    runCompile(work, {
      trigger: 'manual',
      title: 'Mismatch Signal Rule',
      canonicalKey: 'mismatch-signal-rule',
      summary: 'Existing canonical page for the mismatch fallback test.',
      suggestedType: 'concept',
      confidence: 'high',
    });
    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Mismatch Signal Rule',
      canonicalKey: 'mismatch-signal-rule',
      summary: 'Updated summary arriving with a decisions/ targetPath despite concept type.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: 'decisions/wrong-place.md',
    });

    assert.match(out, /updated/);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'decisions', 'wrong-place.md')), false);
    const page = readFileSync(join(work, '.auto-context', 'wiki', 'concepts', 'mismatch-signal-rule.md'), 'utf8');
    assert.match(page, /Updated summary arriving/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: wiki-relative targetPath without .md extension is ignored in favor of slug', () => {
  const work = repoTemp('wiki-compile-wikirel-badext');
  try {
    writeSettings(work);
    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Bad Extension Rule',
      summary: 'A wiki-relative targetPath without the md extension must not be trusted.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: 'concepts/bad-extension.txt',
    });

    assert.match(out, /created/);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'bad-extension.txt')), false);
    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'bad-extension-rule.md')), true);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: traversal, absolute, and hidden-segment targetPath are still rejected', () => {
  const work = repoTemp('wiki-compile-unsafe-target');
  try {
    writeSettings(work);
    const cases = [
      '../outside.md',
      'concepts/../../../escape.md',
      '/tmp/evil-absolute.md',
      'concepts/.hidden/foo.md',
    ];
    for (const targetPath of cases) {
      const out = runCompile(work, {
        trigger: 'manual',
        title: 'Unsafe Target Attempt',
        summary: 'Unsafe targetPath variants must keep rejecting.',
        suggestedType: 'concept',
        confidence: 'high',
        targetPath,
      });
      assert.match(out, /rejected/, `expected reject for ${targetPath}`);
      assert.match(out, /unsafe_target_path/, `expected unsafe_target_path for ${targetPath}`);
    }
    assert.equal(existsSync(join(work, 'concepts')), false);
    assert.equal(existsSync(join(work, 'outside.md')), false);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('query_wiki_similar collapses a multi-line query into a single line (qmd vec search rejects newlines with a 500)', () => {
  // Regression: card bodies are multi-line; qmd's structuredSearch throws
  // "queries must be single-line" -> HTTP 500 -> fail-open, silently disabling
  // the semantic gate/scan for every multi-line card. The query text sent to
  // the daemon must have all whitespace (incl. newlines) collapsed to spaces.
  const script = `
import sys, json
sys.path.insert(0, 'core')
import urllib.request
import wiki_compile as w
cap = {}
class R:
    def __enter__(self): return self
    def __exit__(self, *a): pass
    def read(self): return json.dumps({"results": []}).encode()
def fake(req, timeout=None):
    cap['q'] = json.loads(req.data.decode())['searches'][0]['query']
    return R()
urllib.request.urlopen = fake
w.query_wiki_similar('http://x', 'col', 'line1\\nline2\\n\\n  line3\\t tail ', 3, 5.0)
print(cap['q'])
`;
  const out = execFileSync('python3', ['-c', script], { encoding: 'utf8' }).trim();
  assert.equal(out, 'line1 line2 line3 tail');
  assert.doesNotMatch(out, /\n/);
});

test('compact_manifest: same-identity 중복은 접되 최신 엔트리를 보존해 삭제감지(previous 조회)를 유지', () => {
  // manifest는 삭제감지용으로 read되므로 size trim(카드 엔트리 통째 유실) 대신
  // same_generated_identity로 중복만 접어야 한다. 핵심 불변식: compaction 후에도
  // previous 조회가 살아있고 previous[-1] status(최신)가 유지되어야 한다.
  const work = repoTemp('wiki-compile-compact-manifest');
  const manifest = join(work, 'manifest.jsonl');
  const rows = [
    { targetPath: 'concepts/a.md', canonicalKey: 'ka', status: 'generated' },
    { targetPath: 'concepts/b.md', canonicalKey: 'kb', status: 'generated' },
    { targetPath: 'concepts/a.md', canonicalKey: 'ka', status: 'verified' }, // A 재생성(최신)
  ].map((r) => JSON.stringify(r)).join('\n') + '\n';
  writeFileSync(manifest, rows);
  const script = `
import sys
sys.path.insert(0, 'core')
from pathlib import Path
import wiki_compile as w
p = Path(${JSON.stringify(manifest)})
w.compact_manifest(p, max_bytes=1)  # 임계 강제 트리거
out = w.read_jsonl(p)
assert len(out) == 2, out                     # A 중복 접힘 + B 유지 = 2
prev = [r for r in out if w.same_generated_identity(r, {"targetPath": "concepts/a.md"})]
assert len(prev) == 1 and prev[-1]["status"] == "verified", prev  # 삭제감지 생존 + 최신 status
print("OK")
`;
  try {
    const out = execFileSync('python3', ['-c', script], { encoding: 'utf8' }).trim();
    assert.equal(out, 'OK');
  } finally { rmSync(work, { recursive: true, force: true }); }
});
