import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const CARD_REL = '.auto-context/wiki/concepts/test-card.md';
const HASH = 'abc123';

function cardText(status = 'generated', extraFm = '') {
  return `---
title: "Test Card"
status: ${status}
createdBy: qmd-auto-context
reviewed: false${extraFm}
---

> Auto-generated by qmd-auto-context from conversation/work context. Review, edit, or delete if wrong.

<!-- qmd:auto:start id="main" sourceHash="${HASH}" -->
## Summary
Durable claim: the source documents cite markdown.
<!-- qmd:auto:end -->
`;
}

function setupProject({ verify = {}, extractorArgv = [], cardStatus = 'generated', jobOverrides = {}, withSource = true } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'qwiki-verify-'));
  mkdirSync(join(dir, '.auto-context', 'compile'), { recursive: true });
  mkdirSync(join(dir, '.auto-context', 'wiki', 'concepts'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  if (withSource) {
    writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable claim: the source documents cite markdown.\n');
  }
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-docs', 'proj-wiki'],
    collectionPaths: { 'proj-docs': 'docs', 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-docs': 'raw', 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      enabled: true,
      mode: 'auto-wiki',
      autoWrite: true,
      defaultStatus: 'generated',
      triggers: ['post_tool_source', 'manual'],
      maxSourceChars: 12000,
      extractor: { argv: extractorArgv, timeout: 30 },
      verify: { enabled: true, timeout: 30, ...verify },
    },
  }));
  writeFileSync(join(dir, CARD_REL), cardText(cardStatus));
  writeFileSync(join(dir, '.auto-context', 'compile', 'verify-queue.jsonl'), JSON.stringify({
    ts: '2026-07-04T00:00:00Z',
    targetPath: CARD_REL,
    sources: [{ kind: 'file', path: 'docs/source.md', collection: 'proj-docs' }],
    sourceHash: HASH,
    engine: 'claude',
    trigger: 'post_tool_source',
    ...jobOverrides,
  }) + '\n');
  return dir;
}

function mockVerifier(verdictJson) {
  const script = join(mkdtempSync(join(tmpdir(), 'verifier-')), 'verify.py');
  writeFileSync(script, `#!/usr/bin/env python3
import json, sys
payload = json.loads(sys.stdin.read())
assert payload.get('task') == 'verify', 'verify payload expected'
assert 'content' in payload['card']
assert payload['sources'], 'sources must be loaded'
print(json.dumps(json.loads(${JSON.stringify(JSON.stringify(verdictJson))})))
`);
  return script;
}

function runVerifyWorker(project, env = {}) {
  return execFileSync('python3', ['core/wiki_verify_worker.py', '--cwd', project, '--json'], {
    cwd: process.cwd(),
    encoding: 'utf8',
    env: { ...process.env, ...env },
  });
}

function jsonl(path) {
  if (!existsSync(path)) return [];
  return readFileSync(path, 'utf8').trim().split('\n').filter(Boolean).map((line) => JSON.parse(line));
}

test('verify pass → status verified + verifiedBy/verifiedAt 패치 + 재인덱싱 enqueue', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [{ claim: 'c', supported: true, quote: 'q', sourcePath: 'docs/source.md' }], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vp-')), 'queue');
  try {
    const out = JSON.parse(runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue }));
    assert.equal(out.processed, 1);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: verified$/m);
    assert.match(text, /^verifiedBy: "?claude"?$/m);
    assert.match(text, /^verifiedAt: /m);
    assert.match(text, /Durable claim/, '관리 블록 본문은 보존');
    assert.match(readFileSync(dirtyQueue, 'utf8'), /^proj-wiki\t/);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'verified');
    assert.equal(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), '');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verify fail + onFail 기본(delete) → 카드 삭제, tombstone 없음, 재인덱싱 enqueue', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [{ claim: 'c', supported: false, quote: '', sourcePath: 'docs/source.md' }], reasons: ['source contradicts claim'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vf-')), 'queue');
  try {
    runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue });
    assert.equal(existsSync(join(project, CARD_REL)), false, '반증된 카드는 즉시 삭제');
    const tombstones = join(project, '.auto-context', 'compile', 'tombstones.jsonl');
    assert.equal(jsonl(tombstones).length, 0, 'tombstone을 세우지 않아 소스 수정 후 재생성 가능');
    assert.match(readFileSync(dirtyQueue, 'utf8'), /^proj-wiki\t/);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'deleted');
    assert.equal(log[0].reasons[0], 'source contradicts claim');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

// 기계 판정이 카드를 지우는 유일한 게이트이므로 삭제 사유는 pass 트래픽과 분리된
// 파일에 남아야 한다 — fail은 억제 마커(verify-skipped)를 남기지 않으므로 이 원장이
// 유일한 지속 기록이다.
test('verify fail delete → verify-deleted.jsonl 감사 레코드 (fail은 억제 마커 없음)', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [{ claim: 'c', supported: false, quote: '', sourcePath: 'docs/source.md' }], reasons: ['source contradicts claim'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  try {
    runVerifyWorker(project);
    const deleted = jsonl(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl'));
    assert.equal(deleted.length, 1);
    assert.equal(deleted[0].targetPath, CARD_REL);
    assert.equal(deleted[0].verdict, 'fail');
    assert.equal(deleted[0].engine, 'claude');
    assert.equal(deleted[0].reasons[0], 'source contradicts claim');
    assert.deepEqual(deleted[0].sourcePaths, ['docs/source.md']);
    assert.equal(deleted[0].claims, 1);
    assert.ok(deleted[0].deletedAt);
    assert.equal(JSON.stringify(deleted[0]).includes('Durable claim'), false, '원문 본문은 담지 않는다');
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0,
      'fail은 재컴파일을 막지 않으므로 억제 마커 없음 — 감사 추적은 verify-deleted가 책임');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verify-deleted.jsonl은 상한을 넘어도 트림되지 않는다 (verify-log와 대비)', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [], reasons: ['contradiction'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const deletedPath = join(project, '.auto-context', 'compile', 'verify-deleted.jsonl');
  const logPath = join(project, '.auto-context', 'compile', 'verify-log.jsonl');
  // 둘 다 LOG_MAX_BYTES(256KB) 초과 상태로 시작 — 트림 대상이면 절반이 날아간다.
  const bulk = (tag) => Array.from({ length: 400 }, (_, i) => JSON.stringify({ i, tag, pad: 'x'.repeat(700) })).join('\n') + '\n';
  writeFileSync(deletedPath, bulk('old-deletion'));
  writeFileSync(logPath, bulk('old-verdict'));
  try {
    runVerifyWorker(project);
    const deleted = jsonl(deletedPath);
    assert.equal(deleted.length, 401, '기존 400줄 보존 + 새 삭제 1줄');
    assert.equal(deleted[0].i, 0, '가장 오래된 삭제 이력이 남아 있다');
    assert.equal(deleted[400].verdict, 'fail');
    const log = jsonl(logPath);
    assert.equal(log.length, 201, 'verify-log는 상한 초과 시 최근 절반만 유지');
    assert.equal(log[0].i, 200);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verify fail + onFail=contested → status contested 패치(파일 보존)', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [], reasons: ['contradiction'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], verify: { onFail: 'contested' } });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vc-')), 'queue');
  try {
    runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue });
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: contested$/m);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl')), false,
      '삭제하지 않았으면 삭제 원장에 쓰지 않는다');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('inconclusive + onInconclusive=none → generated 유지 + log 기록 (하위호환)', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['source truncated'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], verify: { onInconclusive: 'none' } });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'inconclusive');
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0,
      '삭제하지 않았으면 억제 마커도 남기지 않는다');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('inconclusive + onInconclusive 기본(delete) → 카드 삭제 + 억제 마커 + 삭제 사유 로그', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['verifier could not adjudicate'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vi-')), 'queue');
  try {
    runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue });
    assert.equal(existsSync(join(project, CARD_REL)), false, '판정 불가 카드도 삭제');
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'tombstones.jsonl')).length, 0,
      'tombstone 없음 — 소스 변경 시 재생성 가능');
    assert.match(readFileSync(dirtyQueue, 'utf8'), /^proj-wiki\t/, '삭제 후 wiki 재인덱싱');

    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'deleted');
    assert.equal(log[0].verdict, 'inconclusive', '삭제 사유(verdict) 추적 가능');
    assert.equal(log[0].reasons[0], 'verifier could not adjudicate');
    assert.equal(log[0].suppressedSources, 1);

    const skipped = jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl'));
    assert.equal(skipped.length, 1);
    assert.equal(skipped[0].sourcePath, 'docs/source.md');
    assert.equal(skipped[0].verdict, 'inconclusive');
    assert.equal(skipped[0].targetPath, CARD_REL);
    assert.match(skipped[0].sourceBodyHash, /^[a-f0-9]{32}$/);
    assert.ok(skipped[0].deletedAt, '삭제 시각 기록 — verify-log 트림 후에도 남는 감사 추적');

    const deleted = jsonl(join(project, '.auto-context', 'compile', 'verify-deleted.jsonl'));
    assert.equal(deleted.length, 1, 'inconclusive 삭제도 삭제 원장에 기록');
    assert.equal(deleted[0].verdict, 'inconclusive');
    assert.equal(deleted[0].reasons[0], 'verifier could not adjudicate');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('inconclusive delete: reviewed 카드는 삭제되지 않는다 (사람 판단 보호)', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['unclear'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], cardStatus: 'reviewed' });
  try {
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, CARD_REL)), true, 'reviewed 카드는 기계 삭제 대상 아님');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: reviewed$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'not_generated');
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('inconclusive + onInconclusive=contested → 파일 보존 + status contested', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['unclear'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], verify: { onInconclusive: 'contested' } });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: contested$/m);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('transient(CLI 부재 127)는 inconclusive로 오분류되지 않는다 — 카드 보존 + 큐 보존', () => {
  const project = setupProject({ extractorArgv: ['/nonexistent/verify-cli-xyz'] });
  try {
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, CARD_REL)), true, 'CLI 없는 머신에서 카드가 전멸해선 안 됨');
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), /test-card\.md/);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0,
      'transient은 억제 마커를 남기지 않는다 — CLI 설치 후 재시도되어야 함');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('transient(timeout)는 inconclusive로 오분류되지 않는다 — 카드 보존 + cooldown', () => {
  const slow = join(mkdtempSync(join(tmpdir(), 'verifier-slow-i-')), 'verify.py');
  writeFileSync(slow, '#!/usr/bin/env python3\nimport time\ntime.sleep(5)\n');
  const project = setupProject({ extractorArgv: ['python3', slow], verify: { timeout: 1 } });
  try {
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, CARD_REL)), true);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'verify-cooldown')), true);
    assert.equal(jsonl(join(project, '.auto-context', 'compile', 'verify-skipped.jsonl')).length, 0);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verifier CLI 부재(127) → 큐 보존(설치 대기)', () => {
  const project = setupProject({ extractorArgv: ['/nonexistent/verify-cli-xyz'] });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    const queue = readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8');
    assert.match(queue, /test-card\.md/, '127이면 잡 보존');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verifier timeout → verify-cooldown 생성 + 큐 보존 (compile cooldown과 분리)', () => {
  const slow = join(mkdtempSync(join(tmpdir(), 'verifier-slow-')), 'verify.py');
  writeFileSync(slow, '#!/usr/bin/env python3\nimport time\ntime.sleep(5)\n');
  const project = setupProject({ extractorArgv: ['python3', slow], verify: { timeout: 1 } });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'verify-cooldown')), true);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'cooldown')), false, 'compile cooldown은 건드리지 않음');
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), /test-card\.md/);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verify.enabled=false → 큐 미소비(무동작)', () => {
  const project = setupProject({ verify: { enabled: false } });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), /test-card\.md/);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('처리 전 카드가 reviewed 상태로 바뀐 경우 skip (사람 검수 존중)', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], cardStatus: 'reviewed' });
  try {
    runVerifyWorker(project);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: reviewed$/m, '사람 검수 status는 기계가 건드리지 않음');
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'skipped');
    assert.equal(log[0].reason, 'not_generated');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('job sourceHash와 카드 블록 hash 불일치 → stale_job skip', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], jobOverrides: { sourceHash: 'deadbeef' } });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'stale_job');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('소스 전부 소실 → source_missing skip, generated 유지(미검수 배지 유지)', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], withSource: false });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'source_missing');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('source_missing은 트림되지 않는 원장(source-missing.jsonl)에도 남는다', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], withSource: false });
  try {
    runVerifyWorker(project);
    const rows = jsonl(join(project, '.auto-context', 'compile', 'source-missing.jsonl'));
    assert.equal(rows.length, 1, 'verify-log.jsonl은 트림 대상이라 이 신호가 유실됐다 — 원장에 별도 보존');
    assert.equal(rows[0].targetPath, CARD_REL);
    assert.equal(rows[0].action, 'detected');
    assert.equal(rows[0].origin, 'verify');
    assert.equal(rows[0].status, 'generated');
    assert.deepEqual(rows[0].missingSources, ['docs/source.md']);
    // 카드는 그대로 남는다(삭제·downgrade 없음).
    assert.equal(existsSync(join(project, CARD_REL)), true);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('소스가 살아 있으면(읽기 실패 등) 원장에 소실로 기록하지 않는다', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  try {
    // 소스가 존재하지만 job이 kind를 file이 아닌 것으로 들고 있는 경우: load_sources는
    // 0건이지만 "원문 소실"은 아니다.
    writeFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), JSON.stringify({
      ts: '2026-07-04T00:00:00Z',
      targetPath: CARD_REL,
      sources: [{ kind: 'url', path: 'https://example.com/x' }],
      sourceHash: HASH,
      engine: 'claude',
      trigger: 'post_tool_source',
    }) + '\n');
    runVerifyWorker(project);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'source-missing.jsonl')), false);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('trim_jsonl: 상한 초과 시 최근 절반만 유지', () => {
  const dir = mkdtempSync(join(tmpdir(), 'trim-'));
  const log = join(dir, 'verify-log.jsonl');
  const lines = Array.from({ length: 100 }, (_, i) => JSON.stringify({ i, pad: 'x'.repeat(50) })).join('\n') + '\n';
  writeFileSync(log, lines);
  try {
    execFileSync('python3', ['-c', `
import sys
sys.path.insert(0, 'core')
from pathlib import Path
import wiki_compile as w
w.trim_jsonl(Path(${JSON.stringify(log)}), max_bytes=1024)
`], { cwd: process.cwd(), encoding: 'utf8' });
    const rows = jsonl(log);
    assert.equal(rows.length, 50, '절반 유지');
    assert.equal(rows[0].i, 50, '최근 절반(뒤쪽)이 남음');
  } finally { rmSync(dir, { recursive: true, force: true }); }
});

// 루프 방지: inconclusive 삭제는 매번 host CLI 호출(=사용자 과금)을 유발하므로,
// 같은 소스 내용이 재후보가 되면 extractor를 띄우기 전에 skip해야 한다.
function setupLoopProject(dual) {
  const dir = mkdtempSync(join(tmpdir(), 'qwiki-loop-'));
  mkdirSync(join(dir, '.auto-context', 'compile'), { recursive: true });
  mkdirSync(join(dir, '.auto-context', 'wiki'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-docs', 'proj-wiki'],
    collectionPaths: { 'proj-docs': 'docs', 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-docs': 'raw', 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      enabled: true,
      mode: 'auto-wiki',
      autoWrite: true,
      defaultStatus: 'generated',
      triggers: ['post_tool_source', 'manual'],
      semanticDedup: { enabled: false },
      extractor: { argv: ['python3', dual], timeout: 30 },
      verify: { enabled: true, timeout: 30 },
    },
  }));
  return dir;
}

function inconclusiveDualMock(counter) {
  const dual = join(mkdtempSync(join(tmpdir(), 'dual-inc-')), 'dual.py');
  writeFileSync(dual, `#!/usr/bin/env python3
import json, sys
payload = json.loads(sys.stdin.read())
with open(${JSON.stringify(counter)}, 'a') as fh:
    fh.write((payload.get('task') or 'extract') + '\\n')
if payload.get('task') == 'verify':
    print(json.dumps({'verdict': 'inconclusive', 'claims': [], 'reasons': ['verifier could not adjudicate']}))
else:
    print(json.dumps({'candidates': [{
      'title': 'Loop Decision',
      'summary': 'Durable decision: loop guard suppresses unchanged sources.',
      'suggestedType': 'decision',
      'confidence': 'high',
      'targetPath': '.auto-context/wiki/decisions/loop-decision.md'
    }]}))
`);
  return dual;
}

test('루프 방지: 같은 소스·같은 body-hash 재후보는 extractor 호출 없이 skip, 소스 변경 시 재시도', () => {
  const counterDir = mkdtempSync(join(tmpdir(), 'counter-'));
  const counter = join(counterDir, 'calls.log');
  const dual = inconclusiveDualMock(counter);
  const dir = setupLoopProject(dual);
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-loop-')), 'queue');
  const page = join(dir, '.auto-context', 'wiki', 'decisions', 'loop-decision.md');
  const skippedPath = join(dir, '.auto-context', 'compile', 'verify-skipped.jsonl');
  const candidates = join(dir, '.auto-context', 'compile', 'candidates.jsonl');
  const enqueueSource = () => writeFileSync(
    join(dir, '.auto-context', 'compile', 'source-queue.jsonl'),
    JSON.stringify({
      ts: '2026-07-04T00:00:00Z',
      trigger: 'post_tool_source',
      engine: 'claude',
      cwd: dir,
      source: { kind: 'file', path: 'docs/source.md', collection: 'proj-docs' },
    }) + '\n',
  );
  const runWorker = () => execFileSync('python3', ['core/wiki_compile_worker.py', '--cwd', dir, '--flush-all'], {
    cwd: process.cwd(), encoding: 'utf8',
    env: { ...process.env, QMD_DIRTY_QUEUE: dirtyQueue },
  });
  const calls = () => readFileSync(counter, 'utf8').trim().split('\n').filter(Boolean);

  try {
    writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable decision: loop guard suppresses unchanged sources.\n');
    enqueueSource();
    runWorker();
    assert.equal(existsSync(page), false, '1회차: inconclusive → 카드 삭제');
    assert.equal(jsonl(skippedPath).length, 1, '1회차: 억제 마커 기록');
    assert.deepEqual(calls(), ['extract', 'verify'], '1회차는 extract + verify 각 1회');

    // 2회차: 소스 내용 동일 — sync/mtime 변화로 재enqueue될 수 있는 현실 경로.
    enqueueSource();
    runWorker();
    assert.deepEqual(calls(), ['extract', 'verify'], '2회차는 host CLI를 아예 호출하지 않는다');
    assert.equal(existsSync(page), false);
    const skipRow = jsonl(candidates).filter((r) => r.reason === 'verify_inconclusive_suppressed');
    assert.equal(skipRow.length, 1, 'skip 사유가 candidates 로그에 남는다');
    assert.equal(skipRow[0].action, 'skipped');

    // 3회차: 소스 본문이 실제로 바뀌면 억제가 풀리고 다시 시도된다.
    writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable decision: loop guard retries when the source body changes.\n');
    enqueueSource();
    runWorker();
    assert.deepEqual(calls(), ['extract', 'verify', 'extract', 'verify'], '소스 변경 후 재시도');
    assert.equal(jsonl(skippedPath).length, 2, '새 body-hash로 마커 갱신');
    const hashes = jsonl(skippedPath).map((r) => r.sourceBodyHash);
    assert.notEqual(hashes[0], hashes[1], '기록된 hash가 소스 내용에 따라 달라진다');

    // 기계 삭제는 사용자 삭제로 오독되면 안 된다: manifest의 verify-deleted 마커가
    // 없으면 3회차가 tombstoned로 영구 억제돼 "소스 고치면 재생성"이 성립하지 않는다.
    assert.equal(jsonl(join(dir, '.auto-context', 'compile', 'tombstones.jsonl')).length, 0);
    const actions = jsonl(candidates).map((r) => r.action);
    assert.deepEqual(actions, ['created', 'skipped', 'created'], 'tombstoned 없이 재생성');
  } finally {
    rmSync(dir, { recursive: true, force: true });
    rmSync(counterDir, { recursive: true, force: true });
  }
});

test('end-to-end 피기백: compile worker 1회 실행으로 생성→검증→verified 승격까지', () => {
  // task 분기 mock: extraction 요청엔 candidates, verify 요청엔 pass verdict.
  const dual = join(mkdtempSync(join(tmpdir(), 'dual-')), 'dual.py');
  writeFileSync(dual, `#!/usr/bin/env python3
import json, sys
payload = json.loads(sys.stdin.read())
if payload.get('task') == 'verify':
    print(json.dumps({'verdict': 'pass', 'claims': [], 'reasons': []}))
else:
    print(json.dumps({'candidates': [{
      'title': 'E2E Decision',
      'summary': 'Durable decision: generated wiki pages cite source markdown.',
      'suggestedType': 'decision',
      'confidence': 'high',
      'targetPath': '.auto-context/wiki/decisions/e2e-decision.md'
    }]}))
`);
  const dir = mkdtempSync(join(tmpdir(), 'qwiki-e2e-'));
  mkdirSync(join(dir, '.auto-context', 'compile'), { recursive: true });
  mkdirSync(join(dir, '.auto-context', 'wiki'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable decision: generated wiki pages cite source markdown.\n');
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-docs', 'proj-wiki'],
    collectionPaths: { 'proj-docs': 'docs', 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-docs': 'raw', 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      enabled: true,
      mode: 'auto-wiki',
      autoWrite: true,
      defaultStatus: 'generated',
      triggers: ['post_tool_source', 'manual'],
      semanticDedup: { enabled: false },
      extractor: { argv: ['python3', dual], timeout: 30 },
      verify: { enabled: true, timeout: 30 },
    },
  }));
  writeFileSync(join(dir, '.auto-context', 'compile', 'source-queue.jsonl'), JSON.stringify({
    ts: '2026-07-04T00:00:00Z',
    trigger: 'post_tool_source',
    engine: 'claude',
    cwd: dir,
    source: { kind: 'file', path: 'docs/source.md', collection: 'proj-docs' },
  }) + '\n');
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-e2e-')), 'queue');
  try {
    execFileSync('python3', ['core/wiki_compile_worker.py', '--cwd', dir, '--flush-all'], {
      cwd: process.cwd(), encoding: 'utf8',
      env: { ...process.env, QMD_DIRTY_QUEUE: dirtyQueue },
    });
    const page = join(dir, '.auto-context', 'wiki', 'decisions', 'e2e-decision.md');
    assert.equal(existsSync(page), true);
    const text = readFileSync(page, 'utf8');
    assert.match(text, /^status: verified$/m, '한 번의 worker 실행에서 생성 직후 검증·승격');
    assert.match(text, /^verifiedBy: "?claude"?$/m);
    assert.equal(readFileSync(join(dir, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), '');
  } finally { rmSync(dir, { recursive: true, force: true }); }
});
