import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

function repoTemp(prefix) {
  const base = join(homedir(), '.cache');
  mkdirSync(base, { recursive: true });
  return mkdtempSync(join(base, `qmd-test-${prefix}-`));
}

function writeSettings(work, compile = {}) {
  mkdirSync(join(work, '.auto-context'), { recursive: true });
  writeFileSync(join(work, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-wiki'],
    collectionPaths: { 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      enabled: true,
      mode: 'auto-wiki',
      autoWrite: true,
      defaultStatus: 'generated',
      candidatePath: '.auto-context/compile/candidates.jsonl',
      tombstonePath: '.auto-context/compile/tombstones.jsonl',
      manifestPath: '.auto-context/compile/generated-manifest.jsonl',
      ...compile,
    },
  }));
}

function runCompile(work, payload, env = {}) {
  return execFileSync('python3', ['core/wiki_compile.py', '--cwd', work], {
    encoding: 'utf8',
    input: JSON.stringify(payload),
    env: { ...process.env, ...env },
  });
}

test('wiki_compile: lint-clean candidate writes generated markdown, audit files, and dirty queue', () => {
  const work = repoTemp('wiki-compile-write');
  const dirtyQueue = join(work, 'dirty-queue');
  try {
    writeSettings(work);
    const out = runCompile(work, {
      trigger: 'manual',
      title: 'Config Layout Decision',
      summary: 'Canonical config lives in .auto-context/settings.json; legacy root config is migration-only.',
      suggestedType: 'decision',
      confidence: 'high',
      sources: [{ kind: 'file', path: 'docs/spec.md' }],
      targetPath: '.auto-context/wiki/decisions/config-layout.md',
    }, { QMD_DIRTY_QUEUE: dirtyQueue });

    assert.match(out, /created/);
    const page = readFileSync(join(work, '.auto-context', 'wiki', 'decisions', 'config-layout.md'), 'utf8');
    assert.match(page, /status: generated/);
    assert.match(page, /reviewed: false/);
    assert.match(page, /Auto-generated by qmd-auto-context/);
    assert.match(page, /Canonical config lives/);
    assert.match(readFileSync(join(work, '.auto-context', 'compile', 'candidates.jsonl'), 'utf8'), /Config Layout Decision/);
    assert.match(readFileSync(join(work, '.auto-context', 'compile', 'generated-manifest.jsonl'), 'utf8'), /config-layout/);
    assert.match(readFileSync(join(work, '.auto-context', 'wiki', 'index.md'), 'utf8'), /decisions\/config-layout.md/);
    assert.match(readFileSync(join(work, '.auto-context', 'wiki', 'log.md'), 'utf8'), /created/);
    assert.match(readFileSync(dirtyQueue, 'utf8'), /proj-wiki\t.*\.auto-context\/wiki/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: rejects transcript-like and secret-like candidates without writing wiki page', () => {
  const work = repoTemp('wiki-compile-lint');
  try {
    writeSettings(work);
    runCompile(work, {
      trigger: 'manual',
      title: 'Bad Transcript',
      summary: 'User: please save this\nAssistant: ok\nsk-1234567890abcdef1234567890abcdef',
      suggestedType: 'decision',
      confidence: 'high',
      targetPath: '.auto-context/wiki/decisions/bad.md',
    });

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'decisions', 'bad.md')), false);
    const candidate = readFileSync(join(work, '.auto-context', 'compile', 'candidates.jsonl'), 'utf8');
    assert.match(candidate, /rejected/);
    assert.doesNotMatch(candidate, /sk-1234567890abcdef1234567890abcdef/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: disabled or candidates mode records candidate only', () => {
  const work = repoTemp('wiki-compile-candidates');
  try {
    writeSettings(work, { mode: 'candidates' });
    runCompile(work, {
      trigger: 'manual',
      title: 'Candidate Only',
      summary: 'This should stay in the queue only.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/candidate-only.md',
    });

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'candidate-only.md')), false);
    assert.match(readFileSync(join(work, '.auto-context', 'compile', 'candidates.jsonl'), 'utf8'), /candidate-only/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_compile: missing generated page creates tombstone and suppresses automatic recreation', () => {
  const work = repoTemp('wiki-compile-tombstone');
  try {
    writeSettings(work);
    const payload = {
      trigger: 'manual',
      title: 'Deleted Page',
      summary: 'A generated page that the user deletes should not be recreated automatically.',
      suggestedType: 'concept',
      confidence: 'high',
      targetPath: '.auto-context/wiki/concepts/deleted-page.md',
    };
    runCompile(work, payload);
    rmSync(join(work, '.auto-context', 'wiki', 'concepts', 'deleted-page.md'));
    runCompile(work, payload);

    assert.equal(existsSync(join(work, '.auto-context', 'wiki', 'concepts', 'deleted-page.md')), false);
    assert.match(readFileSync(join(work, '.auto-context', 'compile', 'tombstones.jsonl'), 'utf8'), /deleted-page/);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});
