import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

function repoTemp(prefix) {
  const base = join(homedir(), '.cache');
  mkdirSync(base, { recursive: true });
  return mkdtempSync(join(base, `qmd-test-${prefix}-`));
}

function writeSettings(work, overrides = {}) {
  mkdirSync(join(work, '.auto-context'), { recursive: true });
  writeFileSync(join(work, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-wiki'],
    collectionPaths: { 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: { enabled: true, mode: 'auto-wiki', autoWrite: true, ...overrides },
  }));
}

function writePage(work, relPath, { status, body } = {}) {
  const full = join(work, '.auto-context', 'wiki', relPath);
  mkdirSync(join(full, '..'), { recursive: true });
  const frontmatter = [
    '---',
    'title: "Test Page"',
    'type: entity',
    `status: ${status || 'generated'}`,
    'createdBy: qmd-auto-context',
    '---',
    '',
    '> Auto-generated by qmd-auto-context from conversation/work context. Review, edit, or delete if wrong.',
    '',
    '<!-- qmd:auto:start id="main" sourceHash="abc123" -->',
    '## Summary',
    body || 'Some duplicate-ish content about an event.',
    '<!-- qmd:auto:end -->',
    '',
  ].join('\n');
  writeFileSync(full, frontmatter);
}

function readDedupNeeded(work) {
  const path = join(work, '.auto-context', 'compile', 'dedup-needed.jsonl');
  if (!existsSync(path)) return [];
  return readFileSync(path, 'utf8').trim().split('\n').filter(Boolean).map((l) => JSON.parse(l));
}

function readDedupSnapshot(stateDir) {
  if (!existsSync(stateDir)) return null;
  const file = readdirSync(stateDir).find((f) => f.endsWith('-wiki-dedup.json'));
  if (!file) return null;
  return JSON.parse(readFileSync(join(stateDir, file), 'utf8'));
}

function lastLogLine(logFile) {
  const lines = readFileSync(logFile, 'utf8').trim().split('\n').filter(Boolean);
  return lines[lines.length - 1];
}

function runScanAsync(work, env = {}) {
  // execFileSync would block this process's event loop, starving the in-process
  // mock HTTP server used by tests that need to observe the outgoing /query
  // payload -- use async spawn instead so the server can actually respond.
  return new Promise((resolve, reject) => {
    const child = spawn('python3', ['core/wiki_dedup_scan.py', '--cwd', work], {
      env: { ...process.env, ...env },
    });
    let stderr = '';
    child.stderr.setEncoding('utf8');
    child.stderr.on('data', (chunk) => { stderr += chunk; });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`wiki_dedup_scan.py exited ${code}: ${stderr}`));
    });
  });
}

function runScan(work, env = {}) {
  const cooldownDir = join(work, 'dedup-cooldown');
  const stateDir = join(work, 'sync-state');
  const logFile = join(work, 'dedup.log');
  execFileSync('python3', ['core/wiki_dedup_scan.py', '--cwd', work], {
    encoding: 'utf8',
    env: {
      ...process.env,
      QMD_DEDUP_COOLDOWN_DIR: cooldownDir,
      QMD_SYNC_STATE_DIR: stateDir,
      QMD_DEDUP_LOG: logFile,
      ...env,
    },
  });
  return { cooldownDir, stateDir, logFile };
}

test('wiki_dedup_scan: first run backfills every existing page (no snapshot yet)', () => {
  const work = repoTemp('dedup-scan-backfill');
  try {
    writeSettings(work);
    writePage(work, 'entities/page-a.md', { body: 'The stalker asked for CCTV footage at the front desk.' });
    writePage(work, 'entities/page-b.md', { body: 'A follow-up call came in about the same package delivery.' });
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [{ file: 'proj-wiki/entities/page-b.md', score: 0.95 }],
    }));
    runScan(work, { QMD_QUERY_FIXTURE: fixture });
    const entries = readDedupNeeded(work);
    assert.equal(entries.length >= 1, true, 'expected at least one queued pair on first-run backfill');
    assert.ok(
      entries.some((e) => [e.pageA, e.pageB].includes('entities/page-a.md') && [e.pageA, e.pageB].includes('entities/page-b.md')),
      `expected page-a/page-b pair, got: ${JSON.stringify(entries)}`,
    );
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: self-match is filtered (queried page never matches itself)', () => {
  const work = repoTemp('dedup-scan-self-match');
  try {
    writeSettings(work);
    writePage(work, 'entities/only-page.md', { body: 'The only page in this wiki.' });
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [{ file: 'proj-wiki/entities/only-page.md', score: 0.99 }],
    }));
    runScan(work, { QMD_QUERY_FIXTURE: fixture });
    assert.deepEqual(readDedupNeeded(work), []);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: below autoMergeThreshold (0.9 default) is not queued', () => {
  const work = repoTemp('dedup-scan-below-threshold');
  try {
    writeSettings(work);
    writePage(work, 'entities/page-a.md', { body: 'Some content.' });
    writePage(work, 'entities/page-b.md', { body: 'Loosely related content.' });
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [{ file: 'proj-wiki/entities/page-b.md', score: 0.85 }],
    }));
    runScan(work, { QMD_QUERY_FIXTURE: fixture });
    assert.deepEqual(readDedupNeeded(work), []);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: superseded and discarded pages are excluded from the scan set and as match targets', () => {
  const work = repoTemp('dedup-scan-excluded-status');
  try {
    writeSettings(work);
    writePage(work, 'entities/current.md', { body: 'Current version of the fact.' });
    writePage(work, 'entities/old.md', { status: 'superseded', body: 'Old superseded version of the fact.' });
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [{ file: 'proj-wiki/entities/old.md', score: 0.99 }],
    }));
    runScan(work, { QMD_QUERY_FIXTURE: fixture });
    assert.deepEqual(readDedupNeeded(work), []);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: index.md is never scanned nor matched', () => {
  const work = repoTemp('dedup-scan-index-md');
  try {
    writeSettings(work);
    mkdirSync(join(work, '.auto-context', 'wiki'), { recursive: true });
    writeFileSync(join(work, '.auto-context', 'wiki', 'index.md'), '# Auto-context Wiki Index\n\n- entities/page-a.md\n');
    writePage(work, 'entities/page-a.md', { body: 'Some content.' });
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/index.md', score: 0.99 }] }));
    runScan(work, { QMD_QUERY_FIXTURE: fixture });
    assert.deepEqual(readDedupNeeded(work), []);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: already-queued pair (either field order) is not re-queued', () => {
  const work = repoTemp('dedup-scan-already-queued');
  try {
    writeSettings(work);
    writePage(work, 'entities/page-a.md', { body: 'Content A.' });
    writePage(work, 'entities/page-b.md', { body: 'Content B.' });
    mkdirSync(join(work, '.auto-context', 'compile'), { recursive: true });
    writeFileSync(
      join(work, '.auto-context', 'compile', 'dedup-needed.jsonl'),
      JSON.stringify({ pageA: 'entities/page-b.md', pageB: 'entities/page-a.md', score: 0.95 }) + '\n',
    );
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/entities/page-b.md', score: 0.95 }] }));
    runScan(work, { QMD_QUERY_FIXTURE: fixture });
    assert.equal(readDedupNeeded(work).length, 1, 'must not add a second entry for the same pair');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: cooldown skip when lock is younger than 24h; runs when lock absent', () => {
  const work = repoTemp('dedup-scan-cooldown');
  try {
    writeSettings(work);
    writePage(work, 'entities/page-a.md', { body: 'Content A.' });
    writePage(work, 'entities/page-b.md', { body: 'Content B.' });
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/entities/page-b.md', score: 0.95 }] }));

    // First run: no lock yet -> must run.
    const { cooldownDir } = runScan(work, { QMD_QUERY_FIXTURE: fixture });
    assert.equal(readDedupNeeded(work).length, 1, 'first run (no lock) must scan');

    // Second run immediately after: lock is fresh (<24h) -> must NOT scan again even with a new page.
    writePage(work, 'entities/page-c.md', { body: 'Content C, also matches.' });
    const fixture2 = join(work, 'fixture.json');
    writeFileSync(fixture2, JSON.stringify({ results: [{ file: 'proj-wiki/entities/page-a.md', score: 0.95 }] }));
    runScan(work, { QMD_QUERY_FIXTURE: fixture2 });
    assert.equal(readDedupNeeded(work).length, 1, 'second run within cooldown must not scan again');
    assert.equal(existsSync(cooldownDir), true);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: incremental run only re-examines changed/new pages', () => {
  const work = repoTemp('dedup-scan-incremental');
  try {
    writeSettings(work);
    writePage(work, 'entities/page-a.md', { body: 'Content A.' });
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({ results: [] }));
    const env = runScan(work, { QMD_QUERY_FIXTURE: fixture, QMD_DEDUP_COOLDOWN_SECONDS: '0' });

    writePage(work, 'entities/page-b.md', { body: 'Content B, brand new.' });
    const fixture2 = join(work, 'fixture.json');
    writeFileSync(fixture2, JSON.stringify({ results: [{ file: 'proj-wiki/entities/page-a.md', score: 0.95 }] }));
    runScan(work, {
      QMD_QUERY_FIXTURE: fixture2,
      QMD_DEDUP_COOLDOWN_SECONDS: '0',
      QMD_DEDUP_COOLDOWN_DIR: env.cooldownDir,
      QMD_SYNC_STATE_DIR: env.stateDir,
      QMD_DEDUP_LOG: env.logFile,
    });
    const entries = readDedupNeeded(work);
    assert.equal(entries.length, 1);
    assert.ok([entries[0].pageA, entries[0].pageB].includes('entities/page-b.md'));

    // Prove page-a (unchanged since scan 1) was actually skipped this scan, not just
    // "happened not to produce a pair": the second scan's log line must show only
    // page-b was scanned (scanned_ok=1 out of pages=2).
    const secondScanLog = lastLogLine(env.logFile);
    assert.match(
      secondScanLog,
      /\bscanned_ok=1\b/,
      `expected only the changed/new page (page-b) to be re-scanned on scan 2, got log line: ${secondScanLog}`,
    );
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: maxPairsPerScan caps queuing per scan; overflow retried next scan', () => {
  const work = repoTemp('dedup-scan-max-pairs');
  try {
    writeSettings(work, { semanticDedup: { maxPairsPerScan: 1 } });
    writePage(work, 'entities/page-a.md', { body: 'Content A.' });
    writePage(work, 'entities/page-b.md', { body: 'Content B.' });
    writePage(work, 'entities/page-c.md', { body: 'Content C.' });
    const fixture = join(work, 'fixture.json');
    // Every query returns a high-scoring match against a different partner so each of the 3
    // "new" pages would independently queue a pair if not capped.
    writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/entities/page-a.md', score: 0.95 }] }));
    const env = runScan(work, { QMD_QUERY_FIXTURE: fixture });
    const afterScan1 = readDedupNeeded(work);
    assert.equal(afterScan1.length, 1, 'must stop at maxPairsPerScan=1 for this scan');

    // The page(s) skipped this scan purely due to the cap must NOT have had their snapshot
    // entry advanced -- otherwise they'd never be retried. Prove it by re-running the scan
    // (cooldown forced open) and checking that more pairs get queued, i.e. the overflow
    // page(s) from scan 1 were re-examined and got their own chance to queue a pair.
    runScan(work, {
      QMD_QUERY_FIXTURE: fixture,
      QMD_DEDUP_COOLDOWN_SECONDS: '0',
      QMD_DEDUP_COOLDOWN_DIR: env.cooldownDir,
      QMD_SYNC_STATE_DIR: env.stateDir,
      QMD_DEDUP_LOG: env.logFile,
    });
    const afterScan2 = readDedupNeeded(work);
    assert.ok(
      afterScan2.length > afterScan1.length,
      `expected the overflow page from scan 1 to queue a new pair on scan 2, got ${afterScan1.length} -> ${afterScan2.length} entries`,
    );
    assert.ok(
      afterScan2.some((e) => [e.pageA, e.pageB].includes('entities/page-c.md')),
      `expected page-c (never examined in scan 1 due to the cap) to be re-examined and queued on scan 2, got: ${JSON.stringify(afterScan2)}`,
    );
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: daemon query failure leaves that page unadvanced for retry, never crashes', () => {
  const work = repoTemp('dedup-scan-query-failure');
  try {
    writeSettings(work);
    writePage(work, 'entities/page-a.md', { body: 'Content A.' });
    // No QMD_QUERY_FIXTURE and no real daemon reachable at QMD_DAEMON_URL -> query_wiki_similar
    // returns None (network failure). Must not raise, must still exit 0, must log the failure.
    const { logFile, stateDir, cooldownDir } = runScan(work, { QMD_DAEMON_URL: 'http://127.0.0.1:1' });
    assert.deepEqual(readDedupNeeded(work), []);
    assert.equal(existsSync(logFile), true);

    // Prove the failed page's snapshot entry was never advanced -- read the snapshot
    // directly instead of just inferring it from "nothing got queued".
    const snapshotAfterFailure = readDedupSnapshot(stateDir);
    const filesAfterFailure = (snapshotAfterFailure && snapshotAfterFailure.files) || {};
    assert.ok(
      !('entities/page-a.md' in filesAfterFailure),
      `failed page must not have its snapshot entry advanced, got: ${JSON.stringify(snapshotAfterFailure)}`,
    );

    // Retry with a reachable daemon (fixture): the page should now be examined and
    // get a snapshot entry, proving it was correctly retried rather than stuck forever.
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({ results: [] }));
    runScan(work, {
      QMD_QUERY_FIXTURE: fixture,
      QMD_DEDUP_COOLDOWN_SECONDS: '0',
      QMD_DEDUP_COOLDOWN_DIR: cooldownDir,
      QMD_SYNC_STATE_DIR: stateDir,
      QMD_DEDUP_LOG: logFile,
    });
    const snapshotAfterRetry = readDedupSnapshot(stateDir);
    const filesAfterRetry = (snapshotAfterRetry && snapshotAfterRetry.files) || {};
    assert.ok(
      'entities/page-a.md' in filesAfterRetry,
      `expected page-a to be retried and advanced after a successful scan, got: ${JSON.stringify(snapshotAfterRetry)}`,
    );
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: compile.enabled=false or semanticDedup.enabled=false is a no-op', () => {
  const work = repoTemp('dedup-scan-disabled');
  try {
    writeSettings(work, { enabled: false });
    writePage(work, 'entities/page-a.md', { body: 'Content A.' });
    writePage(work, 'entities/page-b.md', { body: 'Content B.' });
    const fixture = join(work, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({ results: [{ file: 'proj-wiki/entities/page-b.md', score: 0.99 }] }));
    runScan(work, { QMD_QUERY_FIXTURE: fixture });
    assert.deepEqual(readDedupNeeded(work), []);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
});

test('wiki_dedup_scan: queries the daemon with rerank=true (query_wiki_similar defaults to false; the scanner must opt in explicitly)', async () => {
  const work = repoTemp('dedup-scan-rerank-flag');
  const requests = [];
  const server = createServer((req, res) => {
    if (req.method === 'POST' && req.url === '/query') {
      let body = '';
      req.setEncoding('utf8');
      req.on('data', (chunk) => { body += chunk; });
      req.on('end', () => {
        requests.push(JSON.parse(body));
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ results: [] }));
      });
      return;
    }
    res.writeHead(404);
    res.end();
  });
  try {
    writeSettings(work);
    writePage(work, 'entities/page-a.md', { body: 'Some content that needs a real similarity score.' });

    await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
    const { port } = server.address();
    await runScanAsync(work, {
      QMD_DAEMON_URL: `http://127.0.0.1:${port}`,
      QMD_DEDUP_COOLDOWN_DIR: join(work, 'dedup-cooldown'),
      QMD_SYNC_STATE_DIR: join(work, 'sync-state'),
      QMD_DEDUP_LOG: join(work, 'dedup.log'),
    });

    assert.equal(requests.length, 1, 'expected exactly one /query call for the one page');
    assert.equal(requests[0].rerank, true, 'scanner must request rerank=true, not the query_wiki_similar default of false');
  } finally {
    await new Promise((resolve) => server.close(resolve));
    rmSync(work, { recursive: true, force: true });
  }
});
