import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const CARD_REL = '.auto-context/wiki/concepts/test-card.md';
const HASH = 'abc123';

function cardText(status = 'generated', extraFm = '') {
  return `---
title: "Test Card"
status: ${status}
createdBy: qmd-auto-context
reviewed: false${extraFm}
---

> Auto-generated by qmd-auto-context from conversation/work context. Review, edit, or delete if wrong.

<!-- qmd:auto:start id="main" sourceHash="${HASH}" -->
## Summary
Durable claim: the source documents cite markdown.
<!-- qmd:auto:end -->
`;
}

function setupProject({ verify = {}, extractorArgv = [], cardStatus = 'generated', jobOverrides = {}, withSource = true } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'qwiki-verify-'));
  mkdirSync(join(dir, '.auto-context', 'compile'), { recursive: true });
  mkdirSync(join(dir, '.auto-context', 'wiki', 'concepts'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  if (withSource) {
    writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable claim: the source documents cite markdown.\n');
  }
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-docs', 'proj-wiki'],
    collectionPaths: { 'proj-docs': 'docs', 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-docs': 'raw', 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      enabled: true,
      mode: 'auto-wiki',
      autoWrite: true,
      defaultStatus: 'generated',
      triggers: ['post_tool_source', 'manual'],
      maxSourceChars: 12000,
      extractor: { argv: extractorArgv, timeout: 30 },
      verify: { enabled: true, timeout: 30, ...verify },
    },
  }));
  writeFileSync(join(dir, CARD_REL), cardText(cardStatus));
  writeFileSync(join(dir, '.auto-context', 'compile', 'verify-queue.jsonl'), JSON.stringify({
    ts: '2026-07-04T00:00:00Z',
    targetPath: CARD_REL,
    sources: [{ kind: 'file', path: 'docs/source.md', collection: 'proj-docs' }],
    sourceHash: HASH,
    engine: 'claude',
    trigger: 'post_tool_source',
    ...jobOverrides,
  }) + '\n');
  return dir;
}

function mockVerifier(verdictJson) {
  const script = join(mkdtempSync(join(tmpdir(), 'verifier-')), 'verify.py');
  writeFileSync(script, `#!/usr/bin/env python3
import json, sys
payload = json.loads(sys.stdin.read())
assert payload.get('task') == 'verify', 'verify payload expected'
assert 'content' in payload['card']
assert payload['sources'], 'sources must be loaded'
print(json.dumps(json.loads(${JSON.stringify(JSON.stringify(verdictJson))})))
`);
  return script;
}

function runVerifyWorker(project, env = {}) {
  return execFileSync('python3', ['core/wiki_verify_worker.py', '--cwd', project, '--json'], {
    cwd: process.cwd(),
    encoding: 'utf8',
    env: { ...process.env, ...env },
  });
}

function jsonl(path) {
  if (!existsSync(path)) return [];
  return readFileSync(path, 'utf8').trim().split('\n').filter(Boolean).map((line) => JSON.parse(line));
}

test('verify pass → status verified + verifiedBy/verifiedAt 패치 + 재인덱싱 enqueue', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [{ claim: 'c', supported: true, quote: 'q', sourcePath: 'docs/source.md' }], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vp-')), 'queue');
  try {
    const out = JSON.parse(runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue }));
    assert.equal(out.processed, 1);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: verified$/m);
    assert.match(text, /^verifiedBy: "?claude"?$/m);
    assert.match(text, /^verifiedAt: /m);
    assert.match(text, /Durable claim/, '관리 블록 본문은 보존');
    assert.match(readFileSync(dirtyQueue, 'utf8'), /^proj-wiki\t/);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'verified');
    assert.equal(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), '');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verify fail + onFail 기본(delete) → 카드 삭제, tombstone 없음, 재인덱싱 enqueue', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [{ claim: 'c', supported: false, quote: '', sourcePath: 'docs/source.md' }], reasons: ['source contradicts claim'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vf-')), 'queue');
  try {
    runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue });
    assert.equal(existsSync(join(project, CARD_REL)), false, '반증된 카드는 즉시 삭제');
    const tombstones = join(project, '.auto-context', 'compile', 'tombstones.jsonl');
    assert.equal(jsonl(tombstones).length, 0, 'tombstone을 세우지 않아 소스 수정 후 재생성 가능');
    assert.match(readFileSync(dirtyQueue, 'utf8'), /^proj-wiki\t/);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'deleted');
    assert.equal(log[0].reasons[0], 'source contradicts claim');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verify fail + onFail=contested → status contested 패치(파일 보존)', () => {
  const verifier = mockVerifier({ verdict: 'fail', claims: [], reasons: ['contradiction'] });
  const project = setupProject({ extractorArgv: ['python3', verifier], verify: { onFail: 'contested' } });
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-vc-')), 'queue');
  try {
    runVerifyWorker(project, { QMD_DIRTY_QUEUE: dirtyQueue });
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: contested$/m);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('inconclusive → generated 유지 + log 기록', () => {
  const verifier = mockVerifier({ verdict: 'inconclusive', claims: [], reasons: ['source truncated'] });
  const project = setupProject({ extractorArgv: ['python3', verifier] });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'inconclusive');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verifier CLI 부재(127) → 큐 보존(설치 대기)', () => {
  const project = setupProject({ extractorArgv: ['/nonexistent/verify-cli-xyz'] });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    const queue = readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8');
    assert.match(queue, /test-card\.md/, '127이면 잡 보존');
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verifier timeout → verify-cooldown 생성 + 큐 보존 (compile cooldown과 분리)', () => {
  const slow = join(mkdtempSync(join(tmpdir(), 'verifier-slow-')), 'verify.py');
  writeFileSync(slow, '#!/usr/bin/env python3\nimport time\ntime.sleep(5)\n');
  const project = setupProject({ extractorArgv: ['python3', slow], verify: { timeout: 1 } });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'verify-cooldown')), true);
    assert.equal(existsSync(join(project, '.auto-context', 'compile', 'cooldown')), false, 'compile cooldown은 건드리지 않음');
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), /test-card\.md/);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('verify.enabled=false → 큐 미소비(무동작)', () => {
  const project = setupProject({ verify: { enabled: false } });
  try {
    const out = JSON.parse(runVerifyWorker(project));
    assert.equal(out.processed, 0);
    assert.match(readFileSync(join(project, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), /test-card\.md/);
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('처리 전 카드가 reviewed 상태로 바뀐 경우 skip (사람 검수 존중)', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], cardStatus: 'reviewed' });
  try {
    runVerifyWorker(project);
    const text = readFileSync(join(project, CARD_REL), 'utf8');
    assert.match(text, /^status: reviewed$/m, '사람 검수 status는 기계가 건드리지 않음');
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].result, 'skipped');
    assert.equal(log[0].reason, 'not_generated');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('job sourceHash와 카드 블록 hash 불일치 → stale_job skip', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], jobOverrides: { sourceHash: 'deadbeef' } });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'stale_job');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('소스 전부 소실 → source_missing skip, generated 유지(미검수 배지 유지)', () => {
  const verifier = mockVerifier({ verdict: 'pass', claims: [], reasons: [] });
  const project = setupProject({ extractorArgv: ['python3', verifier], withSource: false });
  try {
    runVerifyWorker(project);
    assert.match(readFileSync(join(project, CARD_REL), 'utf8'), /^status: generated$/m);
    const log = jsonl(join(project, '.auto-context', 'compile', 'verify-log.jsonl'));
    assert.equal(log[0].reason, 'source_missing');
  } finally { rmSync(project, { recursive: true, force: true }); }
});

test('trim_jsonl: 상한 초과 시 최근 절반만 유지', () => {
  const dir = mkdtempSync(join(tmpdir(), 'trim-'));
  const log = join(dir, 'verify-log.jsonl');
  const lines = Array.from({ length: 100 }, (_, i) => JSON.stringify({ i, pad: 'x'.repeat(50) })).join('\n') + '\n';
  writeFileSync(log, lines);
  try {
    execFileSync('python3', ['-c', `
import sys
sys.path.insert(0, 'core')
from pathlib import Path
import wiki_compile as w
w.trim_jsonl(Path(${JSON.stringify(log)}), max_bytes=1024)
`], { cwd: process.cwd(), encoding: 'utf8' });
    const rows = jsonl(log);
    assert.equal(rows.length, 50, '절반 유지');
    assert.equal(rows[0].i, 50, '최근 절반(뒤쪽)이 남음');
  } finally { rmSync(dir, { recursive: true, force: true }); }
});

test('end-to-end 피기백: compile worker 1회 실행으로 생성→검증→verified 승격까지', () => {
  // task 분기 mock: extraction 요청엔 candidates, verify 요청엔 pass verdict.
  const dual = join(mkdtempSync(join(tmpdir(), 'dual-')), 'dual.py');
  writeFileSync(dual, `#!/usr/bin/env python3
import json, sys
payload = json.loads(sys.stdin.read())
if payload.get('task') == 'verify':
    print(json.dumps({'verdict': 'pass', 'claims': [], 'reasons': []}))
else:
    print(json.dumps({'candidates': [{
      'title': 'E2E Decision',
      'summary': 'Durable decision: generated wiki pages cite source markdown.',
      'suggestedType': 'decision',
      'confidence': 'high',
      'targetPath': '.auto-context/wiki/decisions/e2e-decision.md'
    }]}))
`);
  const dir = mkdtempSync(join(tmpdir(), 'qwiki-e2e-'));
  mkdirSync(join(dir, '.auto-context', 'compile'), { recursive: true });
  mkdirSync(join(dir, '.auto-context', 'wiki'), { recursive: true });
  mkdirSync(join(dir, 'docs'), { recursive: true });
  writeFileSync(join(dir, 'docs', 'source.md'), '# Source\n\nDurable decision: generated wiki pages cite source markdown.\n');
  writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
    indexing: true,
    collections: ['proj-docs', 'proj-wiki'],
    collectionPaths: { 'proj-docs': 'docs', 'proj-wiki': '.auto-context/wiki' },
    collectionRoles: { 'proj-docs': 'raw', 'proj-wiki': 'wiki' },
    wikiPath: '.auto-context/wiki',
    compile: {
      enabled: true,
      mode: 'auto-wiki',
      autoWrite: true,
      defaultStatus: 'generated',
      triggers: ['post_tool_source', 'manual'],
      semanticDedup: { enabled: false },
      extractor: { argv: ['python3', dual], timeout: 30 },
      verify: { enabled: true, timeout: 30 },
    },
  }));
  writeFileSync(join(dir, '.auto-context', 'compile', 'source-queue.jsonl'), JSON.stringify({
    ts: '2026-07-04T00:00:00Z',
    trigger: 'post_tool_source',
    engine: 'claude',
    cwd: dir,
    source: { kind: 'file', path: 'docs/source.md', collection: 'proj-docs' },
  }) + '\n');
  const dirtyQueue = join(mkdtempSync(join(tmpdir(), 'dirty-e2e-')), 'queue');
  try {
    execFileSync('python3', ['core/wiki_compile_worker.py', '--cwd', dir, '--flush-all'], {
      cwd: process.cwd(), encoding: 'utf8',
      env: { ...process.env, QMD_DIRTY_QUEUE: dirtyQueue },
    });
    const page = join(dir, '.auto-context', 'wiki', 'decisions', 'e2e-decision.md');
    assert.equal(existsSync(page), true);
    const text = readFileSync(page, 'utf8');
    assert.match(text, /^status: verified$/m, '한 번의 worker 실행에서 생성 직후 검증·승격');
    assert.match(text, /^verifiedBy: "?claude"?$/m);
    assert.equal(readFileSync(join(dir, '.auto-context', 'compile', 'verify-queue.jsonl'), 'utf8'), '');
  } finally { rmSync(dir, { recursive: true, force: true }); }
});
