// 카드 본문 지문 결속(`verifiedBodyHash`).
//
// 배경: wiki trust 는 `sourceRevisions`(원문 SHA-256)에만 결속돼 있어 "원문이 컴파일 이후
// 바뀌지 않았다"만 증명했다. 원문을 그대로 둔 채 **카드 본문만** 고치면 `verified` 배지를
// 단 채 그대로 주입됐다(실측 재현: `포트는 8080이다` → `포트는 9999이다`). 이 파일은 그
// 어긋남의 감지와, 감지하지 **않기로 한** 경계(frontmatter·결속 없는 legacy 카드)를 함께
// 고정한다.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { removeTemp } from './helpers/temp.mjs';

function py(code, args = []) {
  return execFileSync('python3', ['-c', code, ...args], {
    cwd: process.cwd(), encoding: 'utf8',
    env: { ...process.env, QMD_RECALL_LOG: '' },
  }).trim();
}

function contextOf(payload, env = {}) {
  const out = execFileSync('python3', ['core/recall.py'], {
    input: JSON.stringify(payload), encoding: 'utf8',
    env: { ...process.env, QMD_RECALL_LOG: '', ...env },
  }).trim();
  return out ? JSON.parse(out).hookSpecificOutput.additionalContext : null;
}

function selectionLine(logPath) {
  const lines = readFileSync(logPath, 'utf8').trim().split('\n')
    .filter((l) => l.startsWith('{')).map((l) => JSON.parse(l))
    .filter((e) => e.event === 'qmd_recall_selection');
  return lines[lines.length - 1];
}

// 카드는 실제 compile 산출물과 같은 구조를 쓴다(frontmatter + 상투구 + auto 블록 + 블록 밖).
function card({ summary, manual = '', title = '포트 결정', status = 'generated' }) {
  return [
    '---',
    `title: "${title}"`,
    `status: ${status}`,
    'createdBy: qmd-auto-context',
    '---',
    '',
    '> Auto-generated by qmd-auto-context from conversation/work context. Review, edit, or delete if wrong.',
    '',
    '<!-- qmd:auto:start id="main" sourceHash="deadbeef" -->',
    '## Summary',
    summary,
    '<!-- qmd:auto:end -->',
    manual,
    '',
  ].join('\n');
}

// 신뢰 3요소 중 sourceRevisions 를 실제 파일 스냅샷으로 채운다(freshness 까지 통과해야
// 주입되므로 리터럴 해시로는 이 파일의 단정이 성립하지 않는다).
function addRevision(dir, body) {
  const rel = 'docs/source.md';
  const abs = join(dir, rel);
  const bytes = readFileSync(abs);
  const st = statSync(abs, { bigint: true });
  const hash = createHash('sha256').update(bytes).digest('hex');
  const rev = `{kind: "file", path: "${rel}", collection: "p-docs", sha256: "${hash}", size: ${st.size}, mtimeNs: ${st.mtimeNs}}`;
  return body.replace(/createdBy: qmd-auto-context\n/,
    `createdBy: qmd-auto-context\nsourceRevisions:\n  - ${rev}\n`);
}

// 기계 검수 통과를 **실제 유일한 writer** 로 찍는다. 지문도 그 writer 가 넣는다.
function stamp(dir, cardRel) {
  const out = py([
    'import sys',
    'from pathlib import Path',
    'sys.path.insert(0, "core")',
    'import wiki_compile as wc, yaml_scalars as ys',
    'card = Path(sys.argv[1]) / sys.argv[2]',
    'h = ys.card_body_hash(card.read_text(encoding="utf-8"))',
    'print(wc.stamp_verification(card, "verified", "codex", "cross-engine", h))',
  ].join('\n'), [dir, cardRel]);
  assert.equal(out, 'True', 'stamp_verification 이 성공해야 함');
}

function withProject(cardBody, fn, settings = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'qmd-bodybind-'));
  try {
    mkdirSync(join(dir, '.auto-context', 'wiki', 'concepts'), { recursive: true });
    mkdirSync(join(dir, 'docs'), { recursive: true });
    writeFileSync(join(dir, 'docs', 'source.md'), '# 원문\n포트는 8080이다\n');
    writeFileSync(join(dir, '.auto-context', 'settings.json'), JSON.stringify({
      indexing: true,
      collections: ['p-wiki', 'p-docs'],
      collectionPaths: { 'p-wiki': '.auto-context/wiki', 'p-docs': 'docs' },
      collectionRoles: { 'p-wiki': 'wiki', 'p-docs': 'raw' },
      recallStrategy: 'wikiOnly', topN: 3, ...settings,
    }));
    const cardRel = '.auto-context/wiki/concepts/port.md';
    writeFileSync(join(dir, cardRel), addRevision(dir, cardBody));
    const fixture = join(dir, 'fixture.json');
    writeFileSync(fixture, JSON.stringify({
      results: [{ file: 'p-wiki/concepts/port.md', title: 'Summary', score: 1 }],
    }));
    return fn({ dir, cardRel, cardAbs: join(dir, cardRel), fixture, log: join(dir, 'r.log') });
  } finally { removeTemp(dir); }
}

const PROMPT = '포트 결정 내용을 알려줘';

// ── 불변식: 지문이 스탬프를 견딘다 ────────────────────────────────────────────
// 이것이 설계의 linchpin 이다. `stamp_verification` 은 frontmatter 를 다시 쓰므로, 지문이
// 스탬프에서 흔들리면 방금 검수한 카드가 그 즉시 자기 지문과 불일치해 전량 비가시가 된다.
test('본문 지문은 stamp_verification 을 견딘다 (CRLF·본문 내 --- ·본문 없음 포함)', () => {
  const out = py([
    'import sys, json, tempfile, shutil',
    'from pathlib import Path',
    'sys.path.insert(0, "core")',
    'import wiki_compile as wc, yaml_scalars as ys',
    'cases = {',
    '  "기본": "---\\nstatus: generated\\n---\\nbody\\n",',
    '  "CRLF": "---\\r\\nstatus: generated\\r\\n---\\r\\nbody\\r\\n",',
    '  "본문없음": "---\\nstatus: generated\\n---\\n",',
    '  "본문에 구분선": "---\\nstatus: generated\\n---\\nbody\\n---\\n표처럼 보이는 줄\\n",',
    '}',
    'd = Path(tempfile.mkdtemp()); res = {}',
    'for name, text in cases.items():',
    '    f = d / "c.md"',
    '    f.write_text(text, encoding="utf-8", newline="")',
    '    before = ys.card_body_hash(f.read_text(encoding="utf-8"))',
    '    ok = wc.stamp_verification(f, "verified", "codex", "cross-engine", before)',
    '    after = ys.card_body_hash(f.read_text(encoding="utf-8"))',
    '    res[name] = {"stamped": ok, "stable": before == after,',
    '                 "recorded": "verifiedBodyHash" in f.read_text(encoding="utf-8")}',
    'shutil.rmtree(d)',
    'print(json.dumps(res, ensure_ascii=False))',
  ].join('\n'));
  for (const [name, r] of Object.entries(JSON.parse(out))) {
    assert.equal(r.stamped, true, `${name}: 스탬프 성공`);
    assert.equal(r.stable, true, `${name}: 지문이 스탬프 전후 동일해야 한다`);
    assert.equal(r.recorded, true, `${name}: 지문이 frontmatter 에 기록돼야 한다`);
  }
});

// 경계 정규식이 두 벌이면 쓰는 쪽과 읽는 쪽이 다른 본문을 해시한다.
test('frontmatter 경계 정규식은 yaml_scalars 가 SSOT다 (wiki_compile 은 별칭)', () => {
  assert.equal(py([
    'import sys; sys.path.insert(0, "core")',
    'import wiki_compile as wc, yaml_scalars as ys',
    'print(wc.FRONTMATTER_RE is ys.FRONTMATTER_RE)',
  ].join('\n')), 'True');
});

// ── 감지 ──────────────────────────────────────────────────────────────────────
test('지문이 일치하는 카드는 그대로 주입된다', () => {
  withProject(card({ summary: '포트는 8080이다.' }), ({ dir, cardRel, fixture, log }) => {
    stamp(dir, cardRel);
    const ctx = contextOf({ prompt: PROMPT, cwd: dir },
      { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log });
    assert.ok(ctx, '주입이 있어야 함');
    assert.match(ctx, /포트는 8080이다\./);
    assert.equal(selectionLine(log).card_body_hash_states.match, undefined,
      '정상값(match)은 로그 줄을 키우지 않는다');
  });
});

test('검수 뒤 본문이 바뀐 카드는 주입되지 않는다 (문서화된 8080→9999 재현)', () => {
  withProject(card({ summary: '포트는 8080이다.' }), ({ dir, cardRel, cardAbs, fixture, log }) => {
    stamp(dir, cardRel);
    // 원문은 그대로 두고 카드 본문만 고친다 — sourceRevisions 기반 freshness 는 통과한다.
    writeFileSync(cardAbs, readFileSync(cardAbs, 'utf8').replace('8080', '9999'));
    const ctx = contextOf({ prompt: PROMPT, cwd: dir },
      { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log });
    assert.equal(ctx, null, '어긋난 카드는 주입되지 않아야 한다');
    const line = selectionLine(log);
    assert.equal(line.card_body_hash_states.mismatch, 1, '어긋남이 진단에 남아야 한다');
    assert.ok(line.dropped_unverified >= 1, '미검수로 떨어진다');
    assert.equal(line.reason, 'no_results_after_filter');
  });
});

test('블록 밖(qmd:auto:end 뒤) 수정도 잡는다', () => {
  // 고유 사실을 블록 밖에 두라는 규약 때문에 이 자리가 결속에서 빠지면 안 된다.
  withProject(card({ summary: '포트는 8080이다.', manual: '\n## 수동\n원래 문장\n' }),
    ({ dir, cardRel, cardAbs, fixture, log }) => {
      stamp(dir, cardRel);
      writeFileSync(cardAbs, readFileSync(cardAbs, 'utf8').replace('원래 문장', '바꾼 문장'));
      assert.equal(contextOf({ prompt: PROMPT, cwd: dir },
        { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log }), null);
      assert.equal(selectionLine(log).card_body_hash_states.mismatch, 1);
    });
});

// ── 감지하지 않기로 한 경계 ──────────────────────────────────────────────────
test('지문 필드가 없는 legacy 카드는 기존대로 주입된다', () => {
  // 결속 도입 전 검수된 카드가 전부 이 상태다(라이브 verified 1,177장 전원). 부재를
  // 불신으로 읽으면 그 전량이 사라지고, 되살리는 길은 카드당 유료 호출 1회다.
  withProject(card({ summary: '포트는 8080이다.', status: 'verified' }),
    ({ dir, cardAbs, fixture, log }) => {
      assert.doesNotMatch(readFileSync(cardAbs, 'utf8'), /verifiedBodyHash/);
      const ctx = contextOf({ prompt: PROMPT, cwd: dir },
        { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log });
      assert.ok(ctx, 'legacy 카드는 그대로 주입된다');
      assert.match(ctx, /포트는 8080이다\./);
      assert.equal(selectionLine(log).card_body_hash_states.absent, undefined,
        'absent 도 정상값이라 로그에 남기지 않는다');
    });
});

test('frontmatter 변경(title)은 결속 밖이라 주입을 막지 않는다', () => {
  // dedup 의 alias·canonicalKey 이식과 wiki-source-repair 의 sources repoint(사용자 확인
  // 경로)가 이 자리를 쓴다. 결속에 넣으면 그 워크플로가 카드를 비가시로 만든다.
  withProject(card({ summary: '포트는 8080이다.' }), ({ dir, cardRel, cardAbs, fixture, log }) => {
    stamp(dir, cardRel);
    writeFileSync(cardAbs, readFileSync(cardAbs, 'utf8')
      .replace('title: "포트 결정"', 'title: "포트 결정 — 보강"'));
    const ctx = contextOf({ prompt: PROMPT, cwd: dir },
      { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log });
    assert.ok(ctx, 'frontmatter 만 바뀐 카드는 그대로 주입된다');
    assert.match(ctx, /포트 결정 — 보강/);
    assert.equal(selectionLine(log).card_body_hash_states.mismatch, undefined);
  });
});

// ── 읽기 창을 넘는 카드 ──────────────────────────────────────────────────────
// 본문 읽기는 8,192자 창으로 유계다. 지문 대조는 전문이 필요하므로 창을 넘는 카드에서는
// 별도 전문 읽기로 내려간다 — 그 경로가 없으면 큰 카드가 전부 어긋남으로 오판된다.
test('읽기 창을 넘는 카드도 지문 대조가 옳다', () => {
  const filler = Array.from({ length: 400 }, (_, i) => `채움 줄 ${i} — 읽기 창을 넘기기 위한 본문.`).join('\n');
  withProject(card({ summary: `포트는 8080이다.\n${filler}` }), ({ dir, cardRel, cardAbs, fixture, log }) => {
    assert.ok(readFileSync(cardAbs, 'utf8').length > 8192, '카드가 읽기 창보다 커야 한다');
    stamp(dir, cardRel);
    assert.ok(contextOf({ prompt: PROMPT, cwd: dir },
      { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log }), '창을 넘어도 일치하면 주입된다');
    assert.equal(selectionLine(log).card_body_hash_states.mismatch, undefined);
    // 창 **밖**을 고쳐도 잡혀야 한다(창 안만 해시하면 이 수정이 무흔적이 된다).
    writeFileSync(cardAbs, readFileSync(cardAbs, 'utf8').replace('채움 줄 399', '변조된 줄'));
    const log2 = join(dir, 'r2.log');
    assert.equal(contextOf({ prompt: PROMPT, cwd: dir },
      { QMD_QUERY_FIXTURE: fixture, QMD_RECALL_LOG: log2 }), null,
      '창 밖 수정도 어긋남으로 잡아야 한다');
    assert.equal(selectionLine(log2).card_body_hash_states.mismatch, 1);
  });
});

// ── 리셋 ─────────────────────────────────────────────────────────────────────
test('verifiedBodyHash 는 검증 증명 필드라 리셋 경로가 키째 제거한다', () => {
  // 남으면 새 본문에 옛 지문이 붙어 영구 불일치가 된다.
  assert.equal(py([
    'import sys; sys.path.insert(0, "core")',
    'import config as qmd_config',
    'print("verifiedBodyHash" in qmd_config.VERIFY_PROOF_FIELDS)',
  ].join('\n')), 'True');
});

// ── 리셋 경로: 동작으로 확인한다 ──────────────────────────────────────────────
// `VERIFY_PROOF_FIELDS` 멤버십 단정만으로는 "그 튜플을 실제로 경유하는가"가 증명되지
// 않는다. 남으면 새 본문에 옛 지문이 붙어 그 카드가 **영구 불일치**로 비가시가 된다.
test('소스 변경으로 카드가 갱신되면 verifiedBodyHash 가 키째 사라진다 (compile merge)', () => {
  const out = py([
    'import sys, json, tempfile, shutil',
    'from pathlib import Path',
    'sys.path.insert(0, "core")',
    'import wiki_compile as wc, yaml_scalars as ys',
    'd = Path(tempfile.mkdtemp())',
    'card = d / "c.md"',
    'old = ("---\\ntitle: \\"t\\"\\nstatus: generated\\ncreatedBy: qmd-auto-context\\n"',
    '       "sources:\\n  - {kind: \\"file\\", path: \\"a.md\\"}\\n---\\n"',
    '       "<!-- qmd:auto:start id=\\"main\\" sourceHash=\\"aa\\" -->\\n옛 본문\\n"',
    '       "<!-- qmd:auto:end -->\\n\\n## 수동\\n보존 대상\\n")',
    'card.write_text(old, encoding="utf-8", newline="")',
    // 검수 통과 상태를 실제 writer 로 만든다(status: verified + 증명 4필드).
    'wc.stamp_verification(card, "verified", "codex", "cross-engine",',
    '                      ys.card_body_hash(card.read_text(encoding="utf-8")))',
    'stamped = card.read_text(encoding="utf-8")',
    'assert "verifiedBodyHash" in stamped',
    // 소스가 바뀐 뒤의 재생성 페이지(status 는 generated 로 돌아온다).
    'new = ("---\\ntitle: \\"t\\"\\nstatus: generated\\ncreatedBy: qmd-auto-context\\n"',
    '       "sources:\\n  - {kind: \\"file\\", path: \\"a.md\\"}\\n---\\n"',
    '       "<!-- qmd:auto:start id=\\"main\\" sourceHash=\\"bb\\" -->\\n새 본문\\n"',
    '       "<!-- qmd:auto:end -->\\n")',
    'ok = wc.rewrite_generated_card(card, stamped, new)',
    'after = card.read_text(encoding="utf-8")',
    'shutil.rmtree(d)',
    'print(json.dumps({"ok": ok, "hasHash": "verifiedBodyHash" in after,',
    '                  "hasProof": "verifiedBy" in after,',
    '                  "status": "status: generated" in after,',
    '                  "keptManual": "보존 대상" in after,',
    '                  "newBody": "새 본문" in after}, ensure_ascii=False))',
  ].join('\n'));
  const r = JSON.parse(out);
  assert.equal(r.ok, true, '갱신이 성공해야 함');
  assert.equal(r.hasHash, false, 'verifiedBodyHash 가 남으면 새 본문에 옛 지문이 붙는다');
  assert.equal(r.hasProof, false, '증명 필드 전체가 함께 제거된다');
  assert.equal(r.status, true, 'status 는 generated 로 리셋된다(재검증 대상)');
  assert.equal(r.keptManual, true, '블록 밖 수동 섹션은 보존된다');
  assert.equal(r.newBody, true, '새 본문이 반영된다');
});

test('legacy 정규화(wiki_reviewed_migrate)도 verifiedBodyHash 를 제거한다', () => {
  // `sourceRevisions` 가 없는 신뢰 status 는 정규화 대상이다 — `generated` 로 내려가면서
  // 증명 필드가 함께 사라져야 한다. 지문만 남으면 그 카드는 재검수 뒤에도 옛 지문과
  // 어긋난 채로 남는다.
  const out = py([
    'import sys, json, tempfile, shutil',
    'from pathlib import Path',
    'sys.path.insert(0, "core")',
    'import wiki_reviewed_migrate as m',
    'root = Path(tempfile.mkdtemp())',
    'wiki = root / ".auto-context" / "wiki" / "concepts"',
    'wiki.mkdir(parents=True)',
    '(root / ".auto-context" / "settings.json").write_text(json.dumps({',
    '    "indexing": True, "collections": ["w"],',
    '    "collectionPaths": {"w": ".auto-context/wiki"},',
    '    "collectionRoles": {"w": "wiki"}}), encoding="utf-8")',
    'card = wiki / "c.md"',
    'card.write_text("---\\ntitle: \\"t\\"\\nstatus: verified\\n"',
    '                "createdBy: qmd-auto-context\\nverifiedBy: \\"codex\\"\\n"',
    '                "verifiedAt: \\"2026-08-01T00:00:00Z\\"\\n"',
    '                "verifiedBodyHash: \\"deadbeef\\"\\n---\\nbody\\n",',
    '                encoding="utf-8", newline="")',
    'report = m.migrate_reviewed_state(root)',
    'after = card.read_text(encoding="utf-8")',
    'shutil.rmtree(root)',
    'print(json.dumps({"hasHash": "verifiedBodyHash" in after,',
    '                  "hasProof": "verifiedBy" in after,',
    '                  "generated": "status: generated" in after,',
    '                  "text": after}, ensure_ascii=False))',
  ].join('\n'));
  const r = JSON.parse(out);
  assert.equal(r.generated, true, `정규화 대상이어야 한다:\n${r.text}`);
  assert.equal(r.hasHash, false, `정규화 뒤에도 지문이 남았다:\n${r.text}`);
  assert.equal(r.hasProof, false, '증명 필드 전체가 함께 제거된다');
});
