#!/usr/bin/env python3
"""Retroactive wiki dedup scanner ("robot vacuum").

Runs from inside core/update.sh's nested `qmd embed` subshell, after embed
completes -- never from a user-facing entry point. Finds near-duplicate
pages already sitting in .auto-context/wiki/ (created before, or outside,
Phase 1's write-time semantic gate) via daemon vector search on
frontmatter-stripped body text, and queues surviving pairs to
.auto-context/compile/dedup-needed.jsonl for the wiki-dedup-resolver
subagent to judge and resolve.

Fail-open end to end: always exits 0, never writes to stdout, and any
exception is caught and logged rather than raised, so a scanner bug can
never break the embed subshell that calls it.
"""
import argparse
import hashlib
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.resolve()))
import config as qmd_config
import sync as qmd_sync
import wiki_compile as wc

BANNER_RE = re.compile(r"^> Auto-generated by qmd-auto-context.*\n+", re.M)
AUTO_MARKER_LINE_RE = re.compile(r"^<!-- qmd:auto:(start|end).*-->\n?", re.M)
SUMMARY_HEADING_RE = re.compile(r"^## Summary\n+", re.M)
EXCLUDED_STATUSES = {"superseded", "discarded"}
DEDUP_NEEDED_REL = ".auto-context/compile/dedup-needed.jsonl"


def log_path() -> Path:
    return Path(os.environ.get("QMD_DEDUP_LOG", str(Path.home() / ".cache" / "qmd" / "dedup.log")))


def log(message: str) -> None:
    try:
        path = log_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as handle:
            handle.write(f"[{datetime.now(timezone.utc).isoformat()}] {message}\n")
    except OSError:
        pass


def extract_body_text(text: str) -> str:
    """Strip frontmatter and the managed auto-block banner/markers/heading,
    leaving just the page's meaningful prose for semantic-similarity queries.
    Every auto-generated page shares the same ~20 lines of boilerplate; querying
    the full file would make similarity scores meaningless."""
    body = wc.FRONTMATTER_RE.sub("", text, count=1)
    body = BANNER_RE.sub("", body)
    body = AUTO_MARKER_LINE_RE.sub("", body)
    body = SUMMARY_HEADING_RE.sub("", body)
    return body.strip()


def body_hash(text: str) -> str:
    """Stable content hash of a page's normalized body text.

    Normalization is extract_body_text() plus a FIXED whitespace rule
    (CRLF -> LF, per-line trailing-whitespace strip, outer strip), sha256
    over UTF-8 bytes -- insensitive to line-ending/trailing-space churn.
    Shared by this scanner's skip-suppression check and by
    wiki_dedup_resolve.py's skip recording: the two sides MUST hash
    identically or suppression never matches. Never duplicate this.
    """
    body = extract_body_text(text.replace("\r\n", "\n"))
    normalized = "\n".join(line.rstrip() for line in body.split("\n")).strip()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def cooldown_dir(project_key: str) -> Path:
    base = Path(os.environ.get(
        "QMD_DEDUP_COOLDOWN_DIR",
        str(Path.home() / ".config" / "qmd" / "dedup-cooldown"),
    ))
    return base / project_key


def cooldown_seconds() -> int:
    try:
        return max(0, int(os.environ.get("QMD_DEDUP_COOLDOWN_SECONDS", "86400")))
    except ValueError:
        return 86400


def cooldown_ready(lock: Path) -> bool:
    """True if the scan should run now. Absence of the lock means "never
    scanned" and MUST mean run, not skip -- the opposite of
    backend_manager.sh's stale-lock convention, which assumes the lock
    already exists."""
    if not lock.is_dir():
        return True
    try:
        age = time.time() - lock.stat().st_mtime
    except OSError:
        return True
    return age >= cooldown_seconds()


def touch_cooldown(lock: Path) -> None:
    lock.mkdir(parents=True, exist_ok=True)
    os.utime(lock, None)


def snapshot_path(project_key: str) -> Path:
    return qmd_sync.state_dir() / f"{project_key}-wiki-dedup.json"


def scan_set(wiki_root: Path) -> list[Path]:
    pages = []
    for page in sorted(wiki_root.rglob("*.md")):
        if page.name == "index.md":
            continue
        try:
            text = page.read_text(encoding="utf-8")
        except OSError:
            continue
        meta, ok = wc.parse_frontmatter(text)
        status = str(meta.get("status") or "").strip().lower() if ok else ""
        if status in EXCLUDED_STATUSES:
            continue
        pages.append(page)
    return pages


def pair_key(a: str, b: str) -> tuple[str, str]:
    return tuple(sorted((a, b)))


def already_queued(queue_path: Path, key: tuple[str, str]) -> bool:
    for row in wc.read_jsonl(queue_path):
        if pair_key(str(row.get("pageA", "")), str(row.get("pageB", ""))) == key:
            return True
    return False


def run(cwd: str) -> None:
    found = qmd_config.find_project_config(cwd)
    root = Path(found["projectRoot"]).resolve()
    config = found["config"]
    compile_cfg = config.get("compile") if isinstance(config.get("compile"), dict) else {}
    if not compile_cfg.get("enabled"):
        log("SKIP: compile.enabled is false")
        return
    semantic_cfg = compile_cfg.get("semanticDedup") if isinstance(compile_cfg.get("semanticDedup"), dict) else {}
    if not semantic_cfg.get("enabled", True):
        log("SKIP: compile.semanticDedup.enabled is false")
        return

    wiki_rel = config.get("wikiPath", ".auto-context/wiki")
    wiki_root = wc.safe_managed_dir(root, wiki_rel)
    compile_dir = wc.safe_managed_dir(root, ".auto-context/compile")
    if wiki_root is None or compile_dir is None:
        log("ABORT: unsafe_managed_path")
        return
    collection, _ = wc.find_wiki_collection(config)
    if not collection:
        log("SKIP: no wiki collection configured")
        return

    project_key = qmd_sync.project_key(str(root), found.get("configPath"))
    lock = cooldown_dir(project_key)
    if not cooldown_ready(lock):
        return
    touch_cooldown(lock)

    snap_path = snapshot_path(project_key)
    previous = qmd_sync.read_state(snap_path)
    previous_files = previous.get("files", {}) if isinstance(previous.get("files"), dict) else {}

    pages = scan_set(wiki_root)
    scan_set_resolved = {page.resolve() for page in pages}
    current_rels = set()
    to_scan = []
    for page in pages:
        rel = page.relative_to(wiki_root).as_posix()
        current_rels.add(rel)
        try:
            stat = page.stat()
        except OSError:
            continue
        old = previous_files.get(rel)
        if old is None or old.get("mtimeNs") != stat.st_mtime_ns or old.get("size") != stat.st_size:
            to_scan.append((rel, page, stat))

    # Start from the previous snapshot restricted to pages that still exist and
    # are still in-scope; unchanged pages keep their (already-correct) entry.
    current_files = {rel: meta for rel, meta in previous_files.items() if rel in current_rels}

    queue_path = wc.safe_compile_file(root, compile_dir, DEDUP_NEEDED_REL)
    if queue_path is None:
        log("ABORT: unsafe_compile_path")
        return

    daemon_url = os.environ.get("QMD_DAEMON_URL", "http://localhost:8483")
    timeout = float(config.get("queryTimeout", 5.0) or 5.0)
    top_k = int(semantic_cfg.get("topK", 3) or 3)
    threshold = float(semantic_cfg.get("autoMergeThreshold", 0.9))
    max_pairs = int(semantic_cfg.get("maxPairsPerScan", 10) or 10)

    queued_this_scan = 0
    scanned_ok = 0
    scanned_failed = 0
    for rel, page, stat in to_scan:
        if queued_this_scan >= max_pairs:
            break  # overflow: leave unadvanced, retried next scan
        try:
            text = page.read_text(encoding="utf-8")
        except OSError:
            continue
        body = extract_body_text(text)
        if not body:
            continue  # nothing to compare; leave unadvanced (retry once it has content)
        results = wc.query_wiki_similar(daemon_url, collection, body, top_k, timeout)
        if results is None:
            scanned_failed += 1
            continue  # query failed: leave unadvanced, retried next scan
        scanned_ok += 1
        current_files[rel] = {"mtimeNs": stat.st_mtime_ns, "size": stat.st_size}
        for result in results:
            if not isinstance(result, dict):
                continue
            score = result.get("score", 0)
            if not isinstance(score, (int, float)) or score < threshold:
                continue
            matched = wc.resolve_daemon_result_path(root, wiki_root, result.get("file", ""), collection)
            if matched is None:
                continue
            matched_resolved = matched.resolve()
            if matched_resolved == page.resolve():
                continue  # self-match
            if matched_resolved not in scan_set_resolved:
                continue  # excluded status, index.md, or otherwise out of scope
            matched_rel = matched.relative_to(wiki_root).as_posix()
            key = pair_key(rel, matched_rel)
            if already_queued(queue_path, key):
                continue
            wc.append_jsonl(queue_path, {"pageA": rel, "pageB": matched_rel, "score": score})
            queued_this_scan += 1
            break  # one queued pair per scanned page is enough for this pass

    snapshot = {"version": 1, "projectRoot": str(root), "files": current_files}
    qmd_sync.write_state_atomic(snap_path, snapshot)
    log(f"pages={len(pages)} scanned_ok={scanned_ok} scanned_failed={scanned_failed} queued={queued_this_scan}")


def main() -> int:
    if os.environ.get("QMD_SANDBOX"):
        return 0
    parser = argparse.ArgumentParser()
    parser.add_argument("--cwd", default=os.getcwd())
    args = parser.parse_args()
    try:
        run(args.cwd)
    except Exception as exc:  # fail-open: never break the caller
        log(f"EXCEPTION: {exc!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
