#!/usr/bin/env python3
"""wiki 카드 auto 블록 마커의 SSOT.

wiki_compile은 이 마커를 **쓰고**, recall은 주입할 본문을 뽑기 위해 **읽는다**. 예전엔
양쪽이 각자 정규식을 들고 있어 엄격도가 달랐고, 마커 형식이 바뀌면 한쪽만 조용히
깨졌다(읽는 쪽이 깨지면 주입 본문이 빈다 — 이번에 고친 버그와 같은 클래스).

읽기·쓰기 엄격도가 의도적으로 다르다:
- 쓰기(wiki_compile)는 `AUTO_START_PATTERN`으로 sourceHash까지 정확히 매칭한다.
  블록 치환·stale 판정이 hash에 의존하므로 느슨하면 잘못된 블록을 덮어쓴다.
- 읽기(recall)는 `AUTO_START_OPEN` 접두만 보고 선형 스캔한다. 훅은 fail-open이어야
  하고, hash 형식이 미래에 바뀌어도 본문은 계속 읽혀야 한다.
"""

AUTO_START_OPEN = "<!-- qmd:auto:start"
AUTO_START_TEMPLATE = '<!-- qmd:auto:start id="main" sourceHash="{source_hash}" -->'
AUTO_START_PATTERN = r'<!-- qmd:auto:start id="main" sourceHash="([a-f0-9]+)" -->'
AUTO_END = "<!-- qmd:auto:end -->"
COMMENT_OPEN = "<!--"
COMMENT_CLOSE = "-->"

AUTO_DISCLAIMER = (
    "> Auto-generated by qmd-auto-context from conversation/work context. "
    "Review, edit, or delete if wrong."
)
# 상투구 판정용 접두(문구 뒷부분이 바뀌어도 계속 걸러진다).
AUTO_DISCLAIMER_PREFIX = "> Auto-generated by qmd-auto-context"
