#!/usr/bin/env python3
"""Retroactive wiki dedup scanner ("robot vacuum").

Runs from inside core/update.sh's nested `qmd embed` subshell, after embed
completes -- never from a user-facing entry point. Finds near-duplicate
pages already sitting in .auto-context/wiki/ (created before, or outside,
Phase 1's write-time semantic gate) via daemon vector search on
frontmatter-stripped body text, and queues surviving pairs to
.auto-context/compile/dedup-needed.jsonl for the wiki-dedup-resolver
subagent to judge and resolve.

Fail-open end to end: always exits 0, never writes to stdout, and any
exception is caught and logged rather than raised, so a scanner bug can
never break the embed subshell that calls it.
"""
from __future__ import annotations
import argparse
import hashlib
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.resolve()))
import config as qmd_config
import cooldown as qmd_cooldown
import sync as qmd_sync
import wiki_compile as wc
import wiki_dedup_judge as judge

BANNER_RE = re.compile(r"^> Auto-generated by qmd-auto-context.*\n+", re.M)
AUTO_MARKER_LINE_RE = re.compile(r"^<!-- qmd:auto:(start|end).*-->\n?", re.M)
SUMMARY_HEADING_RE = re.compile(r"^## Summary\n+", re.M)
EXCLUDED_STATUSES = {"superseded", "discarded"}
DEDUP_NEEDED_REL = ".auto-context/compile/dedup-needed.jsonl"
DEDUP_SKIPPED_REL = ".auto-context/compile/dedup-skipped.jsonl"


def log_path() -> Path:
    return Path(os.environ.get("QMD_DEDUP_LOG", str(Path.home() / ".cache" / "qmd" / "dedup.log")))


def log(message: str) -> None:
    try:
        path = log_path()
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as handle:
            handle.write(f"[{datetime.now(timezone.utc).isoformat()}] {message}\n")
    except OSError:
        pass


def extract_body_text(text: str) -> str:
    """Strip frontmatter and the managed auto-block banner/markers/heading,
    leaving just the page's meaningful prose for semantic-similarity queries.
    Every auto-generated page shares the same ~20 lines of boilerplate; querying
    the full file would make similarity scores meaningless."""
    body = wc.FRONTMATTER_RE.sub("", text, count=1)
    body = BANNER_RE.sub("", body)
    body = AUTO_MARKER_LINE_RE.sub("", body)
    body = SUMMARY_HEADING_RE.sub("", body)
    return body.strip()


def body_hash(text: str) -> str:
    """Stable content hash of a page's normalized body text.

    Normalization is extract_body_text() plus a FIXED whitespace rule
    (CRLF -> LF, per-line trailing-whitespace strip, outer strip), sha256
    over UTF-8 bytes -- insensitive to line-ending/trailing-space churn.
    Shared by this scanner's skip-suppression check and by
    wiki_dedup_resolve.py's skip recording: the two sides MUST hash
    identically or suppression never matches. Never duplicate this.
    """
    body = extract_body_text(text.replace("\r\n", "\n"))
    normalized = "\n".join(line.rstrip() for line in body.split("\n")).strip()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def cooldown_dir(project_key: str) -> Path:
    base = Path(os.environ.get(
        "QMD_DEDUP_COOLDOWN_DIR",
        str(Path.home() / ".config" / "qmd" / "dedup-cooldown"),
    ))
    return base / project_key


def cooldown_seconds() -> int:
    try:
        return max(0, int(os.environ.get("QMD_DEDUP_COOLDOWN_SECONDS", "86400")))
    except ValueError:
        return 86400


def cooldown_ready(lock: Path) -> bool:
    """True if the scan should run now. Absence of the lock means "never
    scanned" and MUST mean run, not skip -- the opposite of
    backend_manager.sh's stale-lock convention, which assumes the lock
    already exists.

    나이 판정은 `cooldown.window_elapsed`가 SSOT다 — `now - mtime`을 그대로 쓰면
    **미래 mtime**(시계 되돌림·백업 복원)에서 나이가 음수가 되어 이 함수가 영구 False를
    내고 **scan이 영구 skip**된다(dedup 큐가 다시는 채워지지 않는다).
    """
    if lock.exists() and not lock.is_dir():
        # 그 경로가 파일이면 `is_dir()`가 False라 "준비됨"을 내고, 직후 `touch_cooldown`의
        # `mkdir`이 FileExistsError로 죽어 `main`의 except가 그것을 삼킨다 = **scan 영구
        # 사망**(실측: 연속 3회 전부 errno 17, scan 0회). 그 파일을 만드는 코드는 없어
        # 우선순위는 낮지만, 가드가 없으면 복구 경로가 사람의 수동 삭제뿐이다.
        try:
            lock.unlink()
        except OSError:
            log("SKIP: cooldown path exists as a file and could not be removed")
            return False
        return True
    if not lock.is_dir():
        return True
    try:
        mtime = lock.stat().st_mtime
    except OSError:
        return True
    return qmd_cooldown.window_elapsed(mtime, time.time(), cooldown_seconds())


def touch_cooldown(lock: Path) -> None:
    lock.mkdir(parents=True, exist_ok=True)
    os.utime(lock, None)


def snapshot_path(project_key: str) -> Path:
    return qmd_sync.state_dir() / f"{project_key}-wiki-dedup.json"


def scan_set(wiki_root: Path) -> list[Path]:
    pages = []
    for page in sorted(wiki_root.rglob("*.md")):
        # index.md (목차) / log.md (생성 이력) are auto-generated wiki metadata,
        # not knowledge cards. They aggregate every card's name/title, so vec
        # search matches them against almost any query -- pure dedup noise.
        if page.name in ("index.md", "log.md"):
            continue
        try:
            text = page.read_text(encoding="utf-8")
        except OSError:
            continue
        meta, ok = wc.parse_frontmatter(text)
        status = str(meta.get("status") or "").strip().lower() if ok else ""
        if status in EXCLUDED_STATUSES:
            continue
        pages.append(page)
    return pages


def pair_key(a: str, b: str) -> tuple[str, str]:
    return tuple(sorted((a, b)))


def already_queued(queue_path: Path, key: tuple[str, str]) -> bool:
    for row in wc.read_jsonl(queue_path):
        if pair_key(str(row.get("pageA", "")), str(row.get("pageB", ""))) == key:
            return True
    return False


def load_skip_suppressions(skipped_path: Path | None) -> dict[tuple[str, str], tuple[str, str]]:
    """Map sorted (pageA, pageB) -> (pageAHash, pageBHash), keeping only the
    LAST record per pair -- the file is append-only, so later records simply
    overwrite earlier ones during this in-order pass. Malformed rows are
    ignored (fail-open); rows stored unsorted are normalized, not dropped."""
    suppressions: dict[tuple[str, str], tuple[str, str]] = {}
    if skipped_path is None:
        return suppressions
    for row in wc.read_jsonl(skipped_path):
        page_a = row.get("pageA")
        page_b = row.get("pageB")
        hash_a = row.get("pageAHash")
        hash_b = row.get("pageBHash")
        if not all(isinstance(v, str) and v for v in (page_a, page_b, hash_a, hash_b)):
            continue
        key = pair_key(page_a, page_b)
        suppressions[key] = (hash_a, hash_b) if key == (page_a, page_b) else (hash_b, hash_a)
    return suppressions


def current_body_hash(wiki_root: Path, rel: str, cache: dict[str, str | None]) -> str | None:
    """body_hash of the page's CURRENT on-disk content, memoized per scan.
    None (unreadable) never matches a recorded hash, so it re-queues."""
    if rel not in cache:
        try:
            cache[rel] = body_hash((wiki_root / rel).read_text(encoding="utf-8"))
        except OSError:
            cache[rel] = None
    return cache[rel]


def judge_fields(rel: str, key: tuple[str, str], info: dict | None) -> dict:
    """Judge provenance for a queued pair, keyed to the sorted pair order so
    uniqueTo* stay attached to the right page. Empty dict when unjudged, so the
    existing {pageA, pageB, score} queue shape is unchanged for legacy runs."""
    if not info:
        return {}
    # judge_pair was called with (rel, matched_rel); the queue row stores that same
    # order, so uniqueToA belongs to `rel` regardless of the sorted pair key.
    return {
        "judgeVerdict": info.get("verdict", ""),
        "judgeReason": info.get("reason", ""),
        "judgedBy": info.get("engine", ""),
        # 이 경로에서는 항상 `unknown`이다 — 기존 카드 두 장의 생산자는 기록되지 않으므로
        # (실측 0/12쌍) 자기검증인지 확정할 수 없다. 그 사실을 행에 남긴다.
        "judgedMode": info.get("mode", ""),
        "uniqueToA": info.get("uniqueToA", []),
        "uniqueToB": info.get("uniqueToB", []),
    }


def log_judge_outcome(key: tuple[str, str], verdict: str | None, info: dict) -> None:
    """유료 judge 호출 1회의 결과를 dedup.log 에 한 줄로 남긴다 — **transient·식힘의 종점**.

    `wiki_dedup_judge._back_off`가 돌려주는 `engineCooldown`/`cooldownWriteFailed`를 읽는
    소비자가 저장소에 하나도 없던 동안, "judge 가 유료로 실패했다"와 "judge 가 unclear 로
    판정했다"가 로그에서 구분되지 않았다(요약 줄의 `judged=1 queued=0`은 둘 다 같다). 두 식힘
    쓰기가 모두 실패하면 다음 run 이 같은 후보를 다시 유료로 부르는데 그 흔적도 0이었다.
    verify 는 같은 사실을 `verify-log.jsonl`의 `deferred` 행 + `cooldownWriteFailed`로 남긴다 —
    같은 처방이고, 무엇을 남길지는 `judge.diagnostics()` 한 곳이 정한다(규칙을 복제하지 않는다).

    정상 판정이고 degrade 도 없었으면 `diagnostics()`가 빈 dict 라 아무 줄도 남지 않는다
    (scan 당 최대 `maxPairsPerScan` 줄로 유계).
    """
    diag = judge.diagnostics(info)
    if not diag:
        return
    fields = " ".join(
        f"{name}={','.join(str(v) for v in value) if isinstance(value, list) else value}"
        for name, value in diag.items()
    )
    log(f"JUDGE pair={key[0]}|{key[1]} verdict={verdict or '-'} {fields}")


def record_judged_non_duplicate(
    wiki_root: Path,
    skipped_path: Path | None,
    key: tuple[str, str],
    cache: dict[str, str | None],
    info: dict,
    verdict: str,
    suppressions: dict[tuple[str, str], tuple[str, str]] | None = None,
) -> bool:
    """Record a machine non-duplicate verdict (`distinct` or `unclear`) in dedup-skipped.jsonl.

    Same schema and body-hash keying as wiki_dedup_resolve.record_skip, so the
    existing suppression path applies unchanged: this pair is not re-judged (and
    not re-billed to the user) until one of the two bodies changes. `judgedBy`
    keeps machine verdicts distinguishable from resolver skips in the audit trail.
    Unreadable pages record nothing -- a missing hash would suppress forever.

    **`unclear` is suppressed for the same reason `distinct` is.** Both consumed one paid
    call and produced no actionable verdict, and re-asking about the SAME two bodies
    reproduces the same non-answer -- so without a marker the pair is re-judged (re-billed)
    on every scan. This covers both flavors: a model that genuinely could not decide, and a
    judge whose output was unusable after its candidates ran out (`invalid_verdict` /
    `invalid_extractor_json`, see `wiki_dedup_judge._unusable_output`). What is NOT
    suppressed: `duplicate` (the queue row IS its record), and every non-`ok` outcome
    (transient failure, cooldown, CLI absent) -- no judgment happened there, so suppressing
    would hide a pair that was never actually judged. The cost of suppressing is that a real
    duplicate behind an `unclear` waits until one of the bodies changes; the cost of not
    suppressing is an unbounded paid loop, and that is the worse grade.

    Returns whether the durable row was written. `False` means the suppression
    ledger itself failed, which is the same class as the verify workers' ledgers:
    the paid judge call already happened, and without the marker the next scan
    re-judges the identical pair and bills the user again. The caller stops judging
    for the rest of the scan instead of swallowing it. A missing hash (unreadable
    page) is NOT a failure -- nothing was judged worth suppressing.
    """
    hash_a = current_body_hash(wiki_root, key[0], cache)
    hash_b = current_body_hash(wiki_root, key[1], cache)
    if hash_a is None or hash_b is None:
        return True
    if suppressions is not None:
        # Also suppress in-scan: the same pair surfaces again from the other page's
        # own query, and re-judging it would bill the user twice for one verdict.
        suppressions[key] = (hash_a, hash_b)
    if skipped_path is None:
        return False
    try:
        wc.append_jsonl(skipped_path, {
            "pageA": key[0],
            "pageB": key[1],
            "pageAHash": hash_a,
            "pageBHash": hash_b,
            "skippedAt": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "judgeVerdict": verdict,
            "judgeReason": info.get("reason", ""),
            "judgedBy": info.get("engine", ""),
            "judgedMode": info.get("mode", ""),
        })
    except OSError:
        return False
    return True


def run(cwd: str) -> None:
    found = qmd_config.find_project_config(cwd)
    root = Path(found["projectRoot"]).resolve()
    config = found["config"]
    compile_cfg = config.get("compile") if isinstance(config.get("compile"), dict) else {}
    if not compile_cfg.get("enabled"):
        log("SKIP: compile.enabled is false")
        return
    semantic_cfg = compile_cfg.get("semanticDedup") if isinstance(compile_cfg.get("semanticDedup"), dict) else {}
    if not semantic_cfg.get("enabled", True):
        log("SKIP: compile.semanticDedup.enabled is false")
        return

    wiki_rel = config.get("wikiPath", ".auto-context/wiki")
    wiki_root = wc.safe_managed_dir(root, wiki_rel)
    compile_dir = wc.safe_managed_dir(root, ".auto-context/compile")
    if wiki_root is None or compile_dir is None:
        log("ABORT: unsafe_managed_path")
        return
    collection, _ = wc.find_wiki_collection(config)
    if not collection:
        log("SKIP: no wiki collection configured")
        return

    project_key = qmd_sync.project_key(str(root), found.get("configPath"))
    lock = cooldown_dir(project_key)
    if not cooldown_ready(lock):
        return
    touch_cooldown(lock)

    snap_path = snapshot_path(project_key)
    previous = qmd_sync.read_state(snap_path)
    previous_files = previous.get("files", {}) if isinstance(previous.get("files"), dict) else {}

    pages = scan_set(wiki_root)
    scan_set_resolved = {page.resolve() for page in pages}
    current_rels = set()
    to_scan = []
    for page in pages:
        rel = page.relative_to(wiki_root).as_posix()
        current_rels.add(rel)
        try:
            stat = page.stat()
        except OSError:
            continue
        old = previous_files.get(rel)
        if old is None or old.get("mtimeNs") != stat.st_mtime_ns or old.get("size") != stat.st_size:
            to_scan.append((rel, page, stat))

    # Start from the previous snapshot restricted to pages that still exist and
    # are still in-scope; unchanged pages keep their (already-correct) entry.
    current_files = {rel: meta for rel, meta in previous_files.items() if rel in current_rels}

    queue_path = wc.safe_compile_file(root, compile_dir, DEDUP_NEEDED_REL)
    if queue_path is None:
        log("ABORT: unsafe_compile_path")
        return

    skipped_path = wc.safe_compile_file(root, compile_dir, DEDUP_SKIPPED_REL)
    suppressions = load_skip_suppressions(skipped_path)
    hash_cache: dict[str, str | None] = {}

    daemon_url = os.environ.get("QMD_DAEMON_URL", "http://localhost:8483")
    timeout = float(config.get("queryTimeout", 5.0) or 5.0)
    top_k = int(semantic_cfg.get("topK", 3) or 3)
    threshold = float(semantic_cfg.get("autoMergeThreshold", 0.9))
    max_pairs = int(semantic_cfg.get("maxPairsPerScan", 10) or 10)

    # With an LLM judge available the daemon score is demoted to a retrieval floor
    # and the verdict comes from comparing bodies. Without one we keep the legacy
    # score-threshold behavior verbatim -- see wiki_dedup_judge for why the score
    # cannot express duplication on its own.
    # `ATTRIBUTION_NONE`: 이 경로에는 "생성 엔진"이라는 사실이 존재하지 않는다(카드 두 장,
    # 둘째 생산자 미기록). `judge.is_available`과 `judge.judge_pair`에 **같은 값**을 넘겨야
    # 한다 — 갈리면 "judge 없음"으로 선판정해 놓고 실제로는 판정 가능한 상태가 된다.
    judging = judge.is_available(compile_cfg, attribution=judge.ATTRIBUTION_NONE)
    cross_waived = judge.require_waived(compile_cfg, judge.ATTRIBUTION_NONE)
    ledger_blocked = judging and not (
        skipped_path is not None and wc.ledger_writable(skipped_path)
    )
    if ledger_blocked:
        # **유료 judge 호출 전 preflight** — verify worker와 같은 처방이다. 억제 원장에 쓸 수
        # 없으면 `distinct` 판정이 기록되지 않아 다음 scan이 같은 쌍을 다시 판정하고, 매 scan이
        # 유료 호출이다(scan당 `maxPairsPerScan`회). 가장 확실한 종점은 호출을 아예 하지 않는
        # 것이므로 판정 없이 레거시 score 게이트로 degrade한다(무료, `OUTCOME_UNAVAILABLE`과
        # 같은 경로). judge 없이는 score 게이트가 사실상 아무것도 큐하지 않으므로 이 degrade의
        # 대가는 "이번 scan은 중복을 못 찾는다"뿐이다 — 유료 루프보다 낮은 등급이다.
        judging = False
    retrieval_floor = float(semantic_cfg.get("candidateMinScore", 0.3)) if judging else threshold
    judge_budget = judge.max_pairs_per_scan(compile_cfg) if judging else 0

    queued_this_scan = 0
    scanned_ok = 0
    scanned_failed = 0
    suppressed_this_scan = 0
    judged_this_scan = 0
    judged_distinct = 0
    judged_unclear = 0
    judge_stalled = False
    for rel, page, stat in to_scan:
        if queued_this_scan >= max_pairs:
            break  # overflow: leave unadvanced, retried next scan
        if judge_stalled:
            break  # judge transient failure: leave the rest unadvanced for retry
        try:
            text = page.read_text(encoding="utf-8")
        except OSError:
            continue
        body = extract_body_text(text)
        if not body:
            continue  # nothing to compare; leave unadvanced (retry once it has content)
        results = wc.query_wiki_similar(daemon_url, collection, body, top_k, timeout)
        if results is None:
            scanned_failed += 1
            continue  # query failed: leave unadvanced, retried next scan
        scanned_ok += 1
        advance = True
        for result in results:
            if not isinstance(result, dict):
                continue
            score = result.get("score", 0)
            if not isinstance(score, (int, float)) or score < retrieval_floor:
                continue
            matched = wc.resolve_daemon_result_path(root, wiki_root, result.get("file", ""), collection)
            if matched is None:
                continue
            matched_resolved = matched.resolve()
            if matched_resolved == page.resolve():
                continue  # self-match
            if matched_resolved not in scan_set_resolved:
                continue  # excluded status, index.md, or otherwise out of scope
            matched_rel = matched.relative_to(wiki_root).as_posix()
            key = pair_key(rel, matched_rel)
            if already_queued(queue_path, key):
                continue
            recorded = suppressions.get(key)
            if recorded is not None:
                current = (
                    current_body_hash(wiki_root, key[0], hash_cache),
                    current_body_hash(wiki_root, key[1], hash_cache),
                )
                if None not in current and current == recorded:
                    # Both bodies unchanged since the last skip judgment (resolver's
                    # or the judge's): suppress re-queueing. Fall THROUGH to the
                    # next-ranked result (continue, never break) and consume no
                    # maxPairsPerScan budget.
                    suppressed_this_scan += 1
                    continue
            pair_info = None
            if judging:
                if judged_this_scan >= judge_budget:
                    advance = False  # out of judge budget: retry this page next scan
                    break
                matched_text = judge.read_card(matched)
                if matched_text is None:
                    continue
                judged_this_scan += 1
                verdict, info = judge.judge_pair(
                    root, compile_cfg,
                    {"path": rel, "content": text},
                    {"path": matched_rel, "content": matched_text},
                    attribution=judge.ATTRIBUTION_NONE,
                )
                # degrade·유료 실패·식힘 쓰기 실패의 종점(정상 판정이면 무기록).
                log_judge_outcome(key, verdict, info)
                outcome = info.get("outcome")
                if outcome == judge.OUTCOME_TRANSIENT:
                    # No judgment happened. Preserve the work rather than deciding
                    # on a score we know is not a similarity.
                    advance = False
                    judge_stalled = True
                    break
                if outcome == judge.OUTCOME_UNAVAILABLE:
                    judging = False  # permanent: rest of this scan uses the legacy gate
                    if score < threshold:
                        continue
                else:
                    if verdict != "duplicate":
                        # A judged non-duplicate is recorded like a resolver skip, so the
                        # body-hash suppression keeps it from being re-judged (and re-billed)
                        # until one of the two bodies actually changes. `unclear` gets the
                        # SAME treatment as `distinct` -- both burned a paid call and yielded
                        # no actionable verdict, and re-asking the identical bodies reproduces
                        # it (see record_judged_non_duplicate for the full rationale). This is
                        # also the endpoint for a judge whose output was unusable after its
                        # candidates ran out (invalid_verdict / invalid_extractor_json).
                        if verdict in ("distinct", "unclear"):
                            if verdict == "distinct":
                                judged_distinct += 1
                            else:
                                judged_unclear += 1
                            if not record_judged_non_duplicate(
                                wiki_root, skipped_path, key, hash_cache, info, verdict, suppressions
                            ):
                                # 억제 원장 쓰기 실패 → 이 판정은 다음 scan에 재과금된다.
                                # 그 이상 유료 호출을 하지 않고 이번 scan을 멈춘다(잡·스냅샷
                                # 보존). transient judge 실패와 같은 처리다.
                                advance = False
                                judge_stalled = True
                                break
                        continue
                    pair_info = info
            wc.append_jsonl(queue_path, {
                "pageA": rel,
                "pageB": matched_rel,
                "score": score,
                **judge_fields(rel, key, pair_info),
            })
            queued_this_scan += 1
            break  # one queued pair per scanned page is enough for this pass
        if advance:
            current_files[rel] = {"mtimeNs": stat.st_mtime_ns, "size": stat.st_size}

    snapshot = {"version": 1, "projectRoot": str(root), "files": current_files}
    # **삼킨 반환값이 아니다**(분류: 실패 방향이 안전 + 실패가 예외로 표면화). 반환값이
    # 없고 실패는 예외이며 main()이 로그에 EXCEPTION으로 남긴다. 스냅샷이 전진하지 않으면
    # 다음 scan이 같은 카드를 다시 본다 — 유료 judge 재호출은 `dedup-skipped.jsonl`의
    # body-hash 억제가 막고, 큐 중복은 `already_queued`가 막는다.
    qmd_sync.write_state_atomic(snap_path, snapshot)
    log(
        f"pages={len(pages)} scanned_ok={scanned_ok} scanned_failed={scanned_failed} "
        f"queued={queued_this_scan} suppressed={suppressed_this_scan} "
        f"judged={judged_this_scan} judged_distinct={judged_distinct} "
        f"judged_unclear={judged_unclear}"
        + (" judge=off:skipped_ledger_unwritable" if ledger_blocked else "")
        # `crossEngine:"require"`가 이 경로에 적용되지 않았다는 사실의 **종점**. 쌍이 하나도
        # 판정되지 않은 scan(판정 줄 0개)에서도 남아야 하므로 요약 줄에 둔다 — 설정을 적어 둔
        # 사용자가 "왜 require 가 안 걸리나"를 여기서 확인한다(docs/settings.md 와 같은 말).
        + (" crossEngine=require:waived_unattributable_path" if cross_waived else "")
    )


def main() -> int:
    if os.environ.get("QMD_SANDBOX"):
        return 0
    parser = argparse.ArgumentParser()
    parser.add_argument("--cwd", default=os.getcwd())
    args = parser.parse_args()
    try:
        run(args.cwd)
    except Exception as exc:  # fail-open: never break the caller
        log(f"EXCEPTION: {exc!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
